package com.mst.repositories;
import com.mst.models.UserAccount;
import com.mst.models.dto.InventoryTypeRequest;
import java.util.*;
import java.sql.Timestamp;
import org.springframework.jdbc.core.*;
import org.springframework.stereotype.Repository;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;
/** InvDeffrmItemType FormTypeId=0, Inventory screen113. */
@Repository public class DesktopInventoryTypeRepository {
 private final JdbcTemplate jdbc;private static final Set<Integer> TYPES=Set.of(15,16,18),PARENTS=Set.of(1,2,4,6,10,11);
 public DesktopInventoryTypeRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public List<Map<String,Object>> history(UserAccount u){return jdbc.queryForList("EXEC dbo.Sp_ItemType_GetAllMethod @OrganizationId=?, @CompanyId=?, @ParentCategoryIds=?, @Activity=?",u.getOrganizationId(),u.getCompanyId(),"1,2,4,6,10,11","ReadByOrganizationCompanyId").stream().filter(r->TYPES.contains(r.get("Type"))).toList();}
 public Map<String,Object> lookups(UserAccount u){var config=jdbc.queryForList("EXEC dbo.Sp_ConfigrationsAllocation_GetAllMethod @OrganizationId=?, @CompanyId=?, @ConfigDescription=?, @Activity=?",u.getOrganizationId(),u.getCompanyId(),"ItemCodingEnable","GetConfigurationByOrgCompandConfigDescription");return Map.of("autoCode",!config.isEmpty()&&Boolean.parseBoolean(Objects.toString(config.get(0).get("ConfigKey"),"false")),"multiLanguage",new DesktopInventoryCategoryRepository(jdbc).feature(u,7),"parentCategories",jdbc.queryForList("EXEC dbo.Sp_InventoryItemsOther_GetAllMethod @Activity=?","InventoryParentCategories").stream().filter(r->PARENTS.contains(r.get("Id"))).toList(),"itemTypes",jdbc.queryForList("EXEC dbo.Sp_InvLookup_GetAllMethod @OrganizationId=?, @CompanyId=?, @InvLookupTypeId=?, @Activity=?",u.getOrganizationId(),u.getCompanyId(),6,"ReadByInvlookTypeId").stream().filter(r->TYPES.contains(r.get("Id"))).toList());}
 public String code(UserAccount u){return jdbc.queryForObject("EXEC dbo.Sp_ItemType_GetAllMethod @OrganizationId=?, @CompanyId=?, @Activity=?",String.class,u.getOrganizationId(),u.getCompanyId(),"GenerateCode");}
 public Map<String,Object> record(UserAccount u,int id){var rows=jdbc.queryForList("EXEC dbo.Sp_ItemType_GetAllMethod @Id=?, @Activity=?",id,"ReadById");if(rows.size()!=1||!Objects.equals(rows.get(0).get("OrganizationId"),u.getOrganizationId())||!Objects.equals(rows.get(0).get("CompanyId"),u.getCompanyId())||!TYPES.contains(rows.get(0).get("Type"))||!PARENTS.contains(rows.get(0).get("ParentCategoryId")))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Inventory item type not found in this company");return rows.get(0);}
 public Map<String,Object> save(UserAccount u,InventoryTypeRequest r){var old=r.id>0?record(u,r.id):null;var now=new Timestamp(System.currentTimeMillis());Object[] values={r.id,r.typeCode.trim(),r.typeDescription.trim(),r.type,now,u.getId(),now,u.getId(),old==null?null:old.get("PostDate"),old==null?0:old.get("PostUser"),old==null?false:old.get("PostState"),u.getOrganizationId(),u.getCompanyId(),r.parentCategoryId,r.isMother};int id=jdbc.execute("EXEC dbo.Sp_ItemType_"+(r.id==0?"Insert":"Update")+" @Id=?, @TypeCode=?, @TypeDescription=?, @Type=?, @EntryDate=?, @EntryUser=?, @ModifyDate=?, @ModifyUser=?, @PostDate=?, @PostUser=?, @PostState=?, @OrganizationId=?, @CompanyId=?, @ParentCategoryId=?, @IsMother=?",(PreparedStatementCallback<Integer>) s->{for(int i=0;i<values.length;i++)s.setObject(i+1,values[i]);int saved=r.id;boolean result=s.execute();while(true){if(result){try(var rs=s.getResultSet()){if(rs.next()&&rs.getObject(1) instanceof Number n&&n.intValue()>0)saved=n.intValue();}}else if(s.getUpdateCount()==-1)break;result=s.getMoreResults();}if(saved<=0)throw new IllegalStateException("Item type save returned no ID");return saved;});return record(u,id);}
 public Map<String,Object> translations(UserAccount u){
  var owned=new HashSet<>(jdbc.queryForList("SELECT Id FROM ItemType WHERE OrganizationId=? AND CompanyId=?",Integer.class,u.getOrganizationId(),u.getCompanyId()));
  return Map.of("languages",jdbc.queryForList("EXEC dbo.Sp_MultiLanguages_GetAll @MethodType=?, @OrganizationId=?, @CompanyId=?","ReadAll",u.getOrganizationId(),u.getCompanyId()),"types",jdbc.queryForList("EXEC dbo.Sp_ItemType_GetAllMethod @OrganizationId=?, @CompanyId=?, @Activity=?",u.getOrganizationId(),u.getCompanyId(),"ReadByOrganizationCompanyId"),"history",jdbc.queryForList("EXEC dbo.usp_ItemTypeMultiLanguage_History").stream().filter(r->owned.contains(number(r.get("ItemTypeId")))).toList());
 }
 public void saveTranslation(InventoryTypeRequest.Translation r){jdbc.execute("EXEC dbo.Sp_ItemTypeMultiLingo_Insert @Id=?, @ItemTypeId=?, @MultiLanguagesId=?, @TypeDescription=?",(PreparedStatementCallback<Void>) s->{s.setInt(1,0);s.setInt(2,r.ItemTypeId);s.setInt(3,r.MultiLanguagesId);s.setNString(4,r.TypeDescription);boolean result=s.execute();while(true){if(result){try(var rs=s.getResultSet()){while(rs.next()){/* consume original delete/insert result */}}}else if(s.getUpdateCount()==-1)break;result=s.getMoreResults();}return null;});}
 private static int number(Object n){return n==null?0:Integer.parseInt(n.toString());}
 public boolean multiLanguage(UserAccount u){return new DesktopInventoryCategoryRepository(jdbc).feature(u,7);}}
