package com.mst.repositories;
import java.util.*;
import java.sql.Timestamp;
/** Generated CLR defaults from recovered model properties; no business lookup data. */
final class InventoryPosDefaults {
 static Map<String,Object> item(){Map<String,Object> p=new LinkedHashMap<>();
  p.put("ApplyExciese",false);
  p.put("ApplyGST",false);
  p.put("ApplyVAT",false);
  p.put("ItemStatus",false);
  p.put("OtherTax",false);
  p.put("PostState",false);
  p.put("IsCompany",false);
  p.put("IsThirdParty",false);
  p.put("EntryDate",new Timestamp(System.currentTimeMillis()));
  p.put("ModifyDate",new Timestamp(System.currentTimeMillis()));
  p.put("PostDate",new Timestamp(System.currentTimeMillis()));
  p.put("CostPrice",0d);
  p.put("MaxStockLevel",0d);
  p.put("OptimalStockLevel",0d);
  p.put("MinStockLevel",0d);
  p.put("PackQty",0d);
  p.put("PurchasePrice",0d);
  p.put("ReorderLevel",0d);
  p.put("ReOrderQty",0d);
  p.put("RetailPrice",0d);
  p.put("WholeSalePrice",0d);
  p.put("EmptyBagWeight",0d);
  p.put("WeightKgs",java.math.BigDecimal.ZERO);
  p.put("MaxMeaurement",java.math.BigDecimal.ZERO);
  p.put("LeadTimeDay",0);
  p.put("PackSize",0d);
  p.put("PackSizeId",0);
  p.put("AllowMultiUom",false);
  p.put("CropYearId",0);
  p.put("BaseUnitId",0);
  p.put("BranchesId",0);
  p.put("BuyerSupplierId",0);
  p.put("COGSGLAC",0);
  p.put("CompanyId",0);
  p.put("EntryUser",0);
  p.put("ServicesMasterItemId",0);
  p.put("Id",0);
  p.put("ItemCategoryId",0);
  p.put("ItemClassId",0);
  p.put("ItemTypeId",0);
  p.put("ManufactureId",0);
  p.put("ModifyUser",0);
  p.put("OrganizationId",0);
  p.put("PostUser",0);
  p.put("ProjectsId",0);
  p.put("PurchaseGLAC",0);
  p.put("SaleGLAC",0);
  p.put("DepreciationExpenseAcId",0);
  p.put("accumulatedDepreciationAcId",0);
  p.put("ExpenseMaintenanceAccountId",0);
  p.put("CapitalWipAcId",0);
  p.put("UOMScheduleIdCostRate",0);
  p.put("UOMScheduleIdPurRate",0);
  p.put("UOMScheduleIdRetailRate",0);
  p.put("UOMScheduleIdWhsRate",0);
  p.put("ItemQcGradeId",0);
  p.put("AmountCalcType",null);
  p.put("BaseCropYear",null);
  p.put("BuyerPartNo",null);
  p.put("HSCode",null);
  p.put("ItemCode",null);
  p.put("ItemCodeNew",null);
  p.put("ItemName",null);
  p.put("ItemNameOtherLingo",null);
  p.put("ManufacturePartNo",null);
  p.put("Pic1",null);
  p.put("Pic2",null);
  p.put("ProductNo",null);
  p.put("BarcodeImage",null);
  p.put("BarcodeNo",null);
  p.put("ProductType",null);
  p.put("ModelName",null);
  p.put("ItemOriginId",0);
  p.put("ItemAliasName",null);
  p.put("ItemSpecification",null);
  p.put("MaxMeaurementUnitId",0);
  p.put("itemModalId",0);
  p.put("UomLookUpId",0);
  p.put("MasterItemId",0);
  p.put("PurchaseTypeLookUpId",0);
  p.put("IsExpirable",false);
  p.put("IsDiscountable",false);
  p.put("IsTaxable",false);
  p.put("IsImport",false);
  p.put("ShelfLife",0);
  p.put("SaleTaxPurPercent",0d);
  p.put("AtRetailPriceTax",false);
  p.put("AtPurcahsePriceTax",false);
  p.put("ItemWithVarient",false);
  p.put("SaleTaxSalesPercent",0d);
  p.put("WeightSemiFinish",0d);
  p.put("WeightSemiFinishSand",0d);
  p.put("WeightFinishGoods",0d);
  p.put("MotherItemId",0);
  p.put("RackId",0);
  return p;}
 static Map<String,Object> price(){Map<String,Object> p=new LinkedHashMap<>();
  p.put("Id",0);
  p.put("ScheduleDesc",null);
  p.put("ItemId",0);
  p.put("EffectedDate",new Timestamp(System.currentTimeMillis()));
  p.put("EntryDate",new Timestamp(System.currentTimeMillis()));
  p.put("EntryUser",0);
  p.put("ModifyDate",new Timestamp(System.currentTimeMillis()));
  p.put("ModifyUser",0);
  p.put("OrganizationId",0);
  p.put("CompanyId",0);
  p.put("BranchesId",0);
  p.put("ChangedPriceLookUpId",0);
  p.put("PriceTypeId",0);
  p.put("ItemPrice",0d);
  p.put("PackingRate",0d);
  p.put("Margin",0d);
  p.put("PackingUom",0);
  p.put("RateUomId",0);
  p.put("CropYearId",0);
  p.put("IsActive",false);
  return p;}
 static Map<String,Object> reorder(){Map<String,Object> p=new LinkedHashMap<>();
  p.put("EffectiveDate",new Timestamp(System.currentTimeMillis()));
  p.put("EntryDate",new Timestamp(System.currentTimeMillis()));
  p.put("ModifyDate",new Timestamp(System.currentTimeMillis()));
  p.put("MaxQty",0d);
  p.put("MinQty",0d);
  p.put("OptimalQty",0d);
  p.put("ReOrderPoint",0d);
  p.put("BranchesId",0);
  p.put("CompanyId",0);
  p.put("EntryUser",0);
  p.put("Id",0);
  p.put("ItemId",0);
  p.put("ItemUomId",0);
  p.put("ModifyUser",0);
  p.put("OrganizationId",0);
  p.put("SortNo",0);
  return p;}
 static Map<String,Object> feedPrice(){Map<String,Object> p=new LinkedHashMap<>();
  p.put("IsActive",false);
  p.put("IsApproved",false);
  p.put("ApprovedDate",new Timestamp(System.currentTimeMillis()));
  p.put("EffectiveDate",new Timestamp(System.currentTimeMillis()));
  p.put("EntryDate",new Timestamp(System.currentTimeMillis()));
  p.put("ModifyDate",new Timestamp(System.currentTimeMillis()));
  p.put("ItemRate",0d);
  p.put("ApprovedUserId",0);
  p.put("CompanyId",0);
  p.put("DocumentTypeId",0);
  p.put("EntryUserId",0);
  p.put("FinancialYearId",0);
  p.put("Id",0);
  p.put("ItemId",0);
  p.put("ModifyUserId",0);
  p.put("OrganizationId",0);
  p.put("PricingCustomGroupId",0);
  p.put("RateUomId",0);
  return p;}
 static Map<String,Object> account(){Map<String,Object> p=new LinkedHashMap<>();
  p.put("IsActive",false);
  p.put("PostState",false);
  p.put("EntryDate",new Timestamp(System.currentTimeMillis()));
  p.put("ModifyDate",new Timestamp(System.currentTimeMillis()));
  p.put("PostDate",new Timestamp(System.currentTimeMillis()));
  p.put("Account_Level",0);
  p.put("AccountClass",0);
  p.put("AccountTypeId",0);
  p.put("BSNoteId",0);
  p.put("CompanyId",0);
  p.put("EntryUser",0);
  p.put("FinancialYearId",0);
  p.put("Id",0);
  p.put("CurrencyId",0);
  p.put("ModifyUser",0);
  p.put("OrganizationId",0);
  p.put("PLNoteId",0);
  p.put("PostUser",0);
  p.put("ParentCodeId",0);
  p.put("BranchId",0);
  p.put("CustomGroupId",0);
  p.put("AccountCode",null);
  p.put("AccountGroup",null);
  p.put("AccountTitle",null);
  p.put("AccountTitleOtherLingo",null);
  p.put("OtherErpCode",null);
  p.put("ParentAccountCode",null);
  p.put("ContactNo",null);
  p.put("QrCode",null);
  p.put("CityId",0);
  p.put("CustomerGroupId",0);
  return p;}
 static Map<String,Object> accountAllocation(){Map<String,Object> p=new LinkedHashMap<>();
  p.put("IsActive",false);
  p.put("ChartofAccountId",0);
  p.put("CompanyId",0);
  p.put("Id",0);
  p.put("BranchId",0);
  p.put("GLPageNo",null);
  return p;}
 static Map<String,Object> accountOpening(){Map<String,Object> p=new LinkedHashMap<>();
  p.put("PostState",false);
  p.put("EntryDate",new Timestamp(System.currentTimeMillis()));
  p.put("ModifyDate",new Timestamp(System.currentTimeMillis()));
  p.put("PostDate",new Timestamp(System.currentTimeMillis()));
  p.put("YearObCredit",0d);
  p.put("YearObDebit",0d);
  p.put("ChartOfAccountId",0);
  p.put("CompanyId",0);
  p.put("BranchesId",0);
  p.put("EntryUser",0);
  p.put("FinancialYearId",0);
  p.put("Id",0);
  p.put("ModifyUser",0);
  p.put("OrganizationId",0);
  p.put("PostUser",0);
  p.put("ChartOfAccountTitle",null);
  return p;}
}
