package com.mst.repositories;
import com.mst.models.UserAccount;import com.mst.models.dto.SaleOutwardGatePassRequest;import java.sql.*;import java.time.*;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.*;import org.springframework.stereotype.Repository;import org.springframework.web.server.ResponseStatusException;
@Repository public class SaleOutwardGatePassRepository{
 public static final int DOCUMENT_TYPE_ID=91; private final JdbcTemplate jdbc; public SaleOutwardGatePassRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public Map<String,Object> initial(UserAccount u,int y){return Map.ofEntries(Map.entry("nextNo",code(u,y,null,"GenerategpCode","GpSrNo")),Map.entry("orderTypes",q("EXEC dbo.Sp_GatePassOutward_GetAllMethod @OrganizationId=?,@CompanyId=?,@BranchesId=?,@Activity='GetOrderTypeForGpOutward'",u.getOrganizationId(),u.getCompanyId(),u.getBranchesId())),Map.entry("gatePassTypes",q("EXEC dbo.Sp_GatePassType_GetAllMethod @OrganizationId=?,@CompanyId=?,@Activity='Outward'",u.getOrganizationId(),u.getCompanyId())),Map.entry("vehicleTypes",q("SELECT Id,VehicleDescription FROM dbo.VehicleType ORDER BY VehicleDescription")),Map.entry("cities",q("EXEC dbo.SP_City_GetAllMethod @OrganizationId=?,@CompanyId=?,@MethodType='GetAll'",u.getOrganizationId(),u.getCompanyId())),Map.entry("warehouses",q("EXEC dbo.USP_GetWarehousesAllocatedToBranch @OrganizationId=?,@CompanyId=?,@BranchId=?",u.getOrganizationId(),u.getCompanyId(),u.getBranchesId())),Map.entry("customers",q("EXEC dbo.Sp_SupplierCustomer_GetAllMethod @OrganizationId=?,@CompanyId=?,@Activity='ReadByOrganizationIdCompanyIdForBinding'",u.getOrganizationId(),u.getCompanyId())),Map.entry("items",q("EXEC dbo.USP_Item_AllItemsWithModal @OrganizationId=?,@CompanyId=?",u.getOrganizationId(),u.getCompanyId())),Map.entry("openRecords",open(u,y)));}
 public int typeCode(UserAccount u,int y,String type){return code(u,y,type,"GenerateGPTypeCode","GpTypeSrNo");}
 public Map<String,Object> reference(UserAccount u,int y,int type,int code,LocalDate date){
  if(type==84||type==1606){var ids=q("EXEC dbo.Sp_InvDeliveryOrder_GetAllMethod @OrganizationId=?,@CompanyId=?,@DocNo=?,@DocumentTypeId=?,@FinancialYearId=?,@BranchesId=?,@Activity='DeliveryOrderNoCheckinGatePass'",u.getOrganizationId(),u.getCompanyId(),code,type,y,u.getBranchesId());if(ids.isEmpty())throw new IllegalArgumentException("Delivery order number not found");int id=num(ids.get(0).get("Id"));var lines=q("EXEC dbo.Sp_InvDeliveryOrder_GetAllMethod @OrganizationId=?,@CompanyId=?,@Id=?,@DocumentTypeId=?,@Activity='GetTotalWeightFromDeliveryOrder'",u.getOrganizationId(),u.getCompanyId(),id,type);return Map.of("saleOrderId",id,"rows",lines);}
  if(type==81||type==90||type==1605){var rows=q("EXEC dbo.Sp_SupplierCustomer_GetAllMethod @SaleOrderId=?,@DocumentTypeId=?,@OrganizationId=?,@CompanyId=?,@FinancialYearId=?,@BranchesId=?,@GpDate=?,@Activity='GetSupplierBySaleOrderNo'",code,type,u.getOrganizationId(),u.getCompanyId(),y,u.getBranchesId(),date);if(rows.isEmpty())throw new IllegalArgumentException("Order number not found");return Map.of("saleOrderId",num(rows.get(0).get("SaleOrderId")),"rows",rows);}
  return Map.of("saleOrderId",0,"rows",List.of());
 }
 private int code(UserAccount u,int y,String type,String activity,String col){var rows=type==null?q("EXEC dbo.Sp_GatePassOutward_GetAllMethod @OrganizationId=?,@CompanyId=?,@DocumentTypeId=?,@FinancialYearId=?,@BranchesId=?,@Activity=?",u.getOrganizationId(),u.getCompanyId(),DOCUMENT_TYPE_ID,y,u.getBranchesId(),activity):q("EXEC dbo.Sp_GatePassOutward_GetAllMethod @OrganizationId=?,@CompanyId=?,@DocumentTypeId=?,@FinancialYearId=?,@BranchesId=?,@GatepassType=?,@Activity=?",u.getOrganizationId(),u.getCompanyId(),DOCUMENT_TYPE_ID,y,u.getBranchesId(),type,activity);return rows.isEmpty()?1:num(rows.get(0).get(col));}
 public List<Map<String,Object>> open(UserAccount u,int y){return q("EXEC dbo.Sp_GatePassOutward_GetAllMethod @OrganizationId=?,@CompanyId=?,@DocumentTypeId=?,@FinancialYearId=?,@BranchesId=?,@Activity='GetHistoryonlystatusOpen'",u.getOrganizationId(),u.getCompanyId(),DOCUMENT_TYPE_ID,y,u.getBranchesId());}
 public List<Map<String,Object>> history(UserAccount u,int y){return q("EXEC dbo.Sp_GatePassOutward_GetAllMethod @OrganizationId=?,@CompanyId=?,@DocumentTypeId=?,@FinancialYearId=?,@BranchesId=?,@CanViewAllRecord=1,@EntryUser=?,@Activity='ReadByGatePassHistory'",u.getOrganizationId(),u.getCompanyId(),DOCUMENT_TYPE_ID,y,u.getBranchesId(),u.getId());}
 public Map<String,Object> record(UserAccount u,int id){var rows=q("EXEC dbo.Sp_GatePassOutward_GetAllMethod @Id=?,@Activity='ReadById'",id);if(rows.size()!=1||num(rows.get(0).get("OrganizationId"))!=u.getOrganizationId()||num(rows.get(0).get("CompanyId"))!=u.getCompanyId())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Outward gate pass not found in this company");return rows.get(0);}
 public Map<String,Object> save(UserAccount u,int y,SaleOutwardGatePassRequest r){validate(u,r);Map<String,Object> old=r.id>0?record(u,r.id):null;Timestamp now=Timestamp.valueOf(LocalDateTime.now());String p=r.id>0?"Sp_GatePassOutward_Update":"Sp_GatePassOutward_Insert";String sql="EXEC dbo."+p+" @Id=?,@DocumentTypeId=91,@GpSrNo=?,@GpDate=?,@GatepassType=?,@GpTypeSrNo=?,@SupplierCustomerId=?,@OtherSupCust=?,@VehicleType=?,@VehicleNo=?,@BiltyNo=?,@NoOfPackages=?,@OtherRemarks=?,@RefDocumentTypeId=?,@RefDocumentEntryNo=?,@InDateTimeStamp=?,@OutDateTimeStamp=?,@DocAttachment=?,@IsApproved=?,@EntryDate=?,@EntryUser=?,@ModifyDate=?,@ModifyUser=?,@OrganizationId=?,@CompanyId=?,@PostUser=0,@PostState=0,@PostDate=NULL,@CityId=?,@Freight=?,@SupplierContractCode=?,@Status=?,@NetPaid=?,@SupplierWeight=?,@FactoryWeight=?,@DifferenceWeight=?,@WeighBridgeId=?,@WarehouseId=?,@VarietyName=?,@SaleOrderId=?,@Container=?,@Container1=?,@SealNo=?,@SealNo1=?,@DriverName=NULL,@DriverCellNo=NULL,@DriverCNIC=NULL,@WeightDiffRemarks=?,@FinancialYearId=?,@PackUnit=?,@WeightCommapredToSoWt=?,@BranchesId=?,@ItemId=?,@ExportReturnGrnId=0,@GdnId=0,@TransporterId=?,@ReferencePartyId=?,@BiltyDate=?,@UserLogId=NULL";Object[] a={r.id,r.gpSrNo,r.gpDate,text(r.gatepassType),r.gpTypeSrNo,zero(r.supplierCustomerId),text(r.otherSupCust),text(r.vehicleType),text(r.vehicleNo),text(r.biltyNo),r.noOfPackages,text(r.otherRemarks),r.refDocumentTypeId,r.refDocumentEntryNo,r.inDateTimeStamp,r.outDateTimeStamp,text(r.docAttachment),r.approved,old==null?now:old.get("EntryDate"),old==null?u.getId():old.get("EntryUser"),now,u.getId(),u.getOrganizationId(),u.getCompanyId(),zero(r.cityId),r.freight,text(r.supplierContractCode),text(r.status),r.netPaid,r.supplierWeight,r.factoryWeight,r.differenceWeight,zero(r.weighBridgeId),zero(r.warehouseId),text(r.varietyName),zero(r.saleOrderId),text(r.container),text(r.container1),text(r.sealNo),text(r.sealNo1),text(r.weightDiffRemarks),y,r.packUnit,r.weightCommapredToSoWt,u.getBranchesId(),zero(r.itemId),zero(r.transporterId),zero(r.referencePartyId),r.biltyDate};int id=exec(sql,a,r.id);return record(u,id);}
 private void validate(UserAccount u,SaleOutwardGatePassRequest r){if(r.id>0)record(u,r.id);if(r.gpDate==null)throw new IllegalArgumentException("Gate pass date is required");if(text(r.gatepassType).isEmpty()||r.gpTypeSrNo<=0)throw new IllegalArgumentException("Please select GatePass Type");if(r.gpSrNo<=0)throw new IllegalArgumentException("Please select Gate Pass No");if(text(r.vehicleNo).isEmpty())throw new IllegalArgumentException("Please Select Vehicle No");if(text(r.vehicleType).isEmpty())throw new IllegalArgumentException("Please Select Vehicle Type");if(text(r.status).isEmpty())throw new IllegalArgumentException("Please Select Status");if(text(r.docAttachment).isEmpty())throw new IllegalArgumentException("Please Select WeighBridgeStatus");if(r.id==0&&!"Open".equals(r.status))throw new IllegalArgumentException("Status Not Change");if(r.refDocumentTypeId!=92&&r.refDocumentTypeId!=59&&r.saleOrderId<=0)throw new IllegalArgumentException("Order No Not Found");if("Accepted".equals(r.status)&&r.refDocumentTypeId!=1605&&r.factoryWeight<=0)throw new IllegalArgumentException("Factory Weight field required");}
 private List<Map<String,Object>> q(String s,Object...a){return jdbc.queryForList(s,a);}private int exec(String s,Object[]a,int fallback){return jdbc.execute(s,(PreparedStatementCallback<Integer>)p->{for(int i=0;i<a.length;i++)p.setObject(i+1,a[i]);int id=fallback;boolean got=id>0,m=p.execute();while(true){if(m)try(var rs=p.getResultSet()){while(rs.next())if(!got&&rs.getObject(1)instanceof Number n&&n.intValue()>0){id=n.intValue();got=true;}}else if(p.getUpdateCount()==-1)break;m=p.getMoreResults();}return id;});}private static Integer zero(int n){return n>0?n:null;}private static int num(Object o){return o==null?0:Integer.parseInt(o.toString());}private static String text(String s){return s==null?"":s.trim();}
}
