package com.mst.repositories;
import com.mst.models.UserAccount;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;
@Repository public class SaleGdnDirectRepository extends SaleGdnPurchaseReturnRepository{
 public static final int DOCUMENT_TYPE_ID=124; public SaleGdnDirectRepository(JdbcTemplate j){super(j);}@Override protected int documentTypeId(){return DOCUMENT_TYPE_ID;}@Override protected String screenName(){return "frmGdnDirect";}@Override protected String recordLabel(){return "GDN Direct";}
 @Override public Map<String,Object> initial(UserAccount u,int y){Map<String,Object>m=new LinkedHashMap<>();var no=q("EXEC dbo.Sp_InvGdn_GetAllMethod @OrganizationId=?,@CompanyId=?,@DocumentTypeId=?,@FinancialYearId=?,@BranchesId=?,@Activity='GenerateInvGdnCode'",u.getOrganizationId(),u.getCompanyId(),DOCUMENT_TYPE_ID,y,u.getBranchesId());m.put("nextNo",no.isEmpty()?1:no.get(0).get("DocNo"));boolean subsidiaryAccounts=feature(u,4);/* frmGdnDirect:366 */m.put("customers",subsidiaryAccounts?q("EXEC dbo.USP_GetVendorsAndCustomers @OrganizationId=?,@CompanyId=?,@PartyTypeId=2",u.getOrganizationId(),u.getCompanyId()):q("EXEC dbo.Sp_SupplierCustomer_GetAllMethod @OrganizationId=?,@CompanyId=?,@Activity='ReadByOrganizationIdCompanyIdForBinding'",u.getOrganizationId(),u.getCompanyId()));/* SupplierNameFilll, frmGdnDirect:505 */m.put("items",items(u,0));m.put("brands",globalBrands(u));/* BrandDtFillFromGlobal, frmGdnDirect:721 */m.put("warehouses",q("EXEC dbo.USP_GetWarehousesAllocatedToBranch @OrganizationId=?,@CompanyId=?,@BranchId=?",u.getOrganizationId(),u.getCompanyId(),u.getBranchesId()));m.put("crops",q("EXEC dbo.Sp_InvCropYear_GetAllMethod @OrganizationId=?,@CompanyId=?,@Activity='ReadAll'",u.getOrganizationId(),u.getCompanyId()));m.put("jobLots",saleJobLots(u));/* JobLotDtFillFromGlobalAndBind, frmGdnDirect:462 */m.put("packingTypes",q("EXEC dbo.Sp_InvPackingType_GetAllMethod @Activity='ReadAll'"));m.put("cities",q("EXEC dbo.SP_City_GetAllMethod @OrganizationId=?,@CompanyId=?,@MethodType='GetAll'",u.getOrganizationId(),u.getCompanyId()));/* TransportFill, frmGdnDirect:547: feature 4 -> transporter parties bound on Id (not GlAccountId, unlike InvFrmGDN);
    otherwise CoaAllocationGetAllServiceBind dropping AccountTypeId 2, 15 and 11. */
 m.put("transporters",subsidiaryAccounts?transporterParties(u,false):coaAccounts(u,t->t!=2&&t!=15&&t!=11));return m;}
 /* ItemNameFillWithoutOrder, frmGdnDirect:639: CommonServices.ReadAllItems = Sp_Item_GetAllMethod @OrganizationId,@CompanyId,
    @Activity='ReadAllItems' (Item.ReadAllItems:253), no ItemTypeOfTypeId filter - the 14/17 exclusion belongs to InvFrmGDN only.
    Shape = the form's dtItem: Id, ItemName, ItemCode (from ItemCodeNew). */
/* PackUOMFillWithoutOrder, frmGdnDirect:801: CommonServices.GetUomScheduleByItemId = UOMSchedule.SearchByObject =
    Sp_UOMSchedule_GetAllMethod @OrganizationId,@CompanyId,@ItemId,@Activity='ReadByItemID' (IL Inventory.txt:101367).
    This form does not use the global UOM cache that InvFrmGDN uses. */
 @Override public List<Map<String,Object>> uoms(UserAccount u,int itemId){return q("EXEC dbo.Sp_UOMSchedule_GetAllMethod @OrganizationId=?,@CompanyId=?,@ItemId=?,@Activity='ReadByItemID'",u.getOrganizationId(),u.getCompanyId(),itemId);}
 @Override public List<Map<String,Object>> items(UserAccount u,int ignored){List<Map<String,Object>> out=new ArrayList<>();for(var r:q("EXEC dbo.Sp_Item_GetAllMethod @OrganizationId=?,@CompanyId=?,@Activity='ReadAllItems'",u.getOrganizationId(),u.getCompanyId())){Map<String,Object> x=new LinkedHashMap<>();x.put("Id",r.get("Id"));x.put("ItemName",r.get("ItemName"));x.put("ItemCode",r.get("ItemCodeNew"));out.add(x);}return out;}
}
