package com.mst.repositories;
import com.mst.models.dto.*;
import com.mst.security.*;
import com.mst.services.*;
import java.nio.file.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
@EnabledIfSystemProperty(named="inventory.rollback",matches="true")
class InventoryItemManufacturerLiveTest {
 @Test void manufacturerAndLinkedLookupCrudMatchOriginalProceduresAndRollback() throws Exception {
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);var repo=new DesktopInventoryItemManufacturerRepository(jdbc);var lookupRepo=new DesktopInventoryLookupDefinitionRepository(jdbc);var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var service=new DesktopInventoryItemManufacturerService(repo,context,rights);var lookupService=new DesktopInventoryLookupDefinitionService(lookupRepo,context,rights);
  var items=repo.items(u);var manufacturers=repo.manufacturers(u);assertFalse(items.isEmpty());assertEquals(new HashSet<>(jdbc.queryForList("EXEC dbo.Sp_Item_GetAllMethod @OrganizationId=?, @CompanyId=?, @Activity='ReadAllItems'",u.getOrganizationId(),u.getCompanyId())),new HashSet<>(items));assertEquals(jdbc.queryForList("EXEC dbo.Sp_ItemAllocateToManufactures_GetAllMethod @OrganizationId=?, @CompanyId=?, @Activity='ReadAll'",u.getOrganizationId(),u.getCompanyId()),service.history());assertEquals(jdbc.queryForList("EXEC dbo.Sp_InvLookup_GetAllMethod @OrganizationId=?, @CompanyId=?, @InvLookupTypeId=14, @Activity='ReadByInvlookTypeId'",u.getOrganizationId(),u.getCompanyId()),manufacturers);
  var before=jdbc.queryForList("SELECT * FROM ItemAllocateToManufactures ORDER BY Id");var definitionsBefore=jdbc.queryForList("SELECT * FROM InvLookUp ORDER BY Id");var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);tx.setTimeout(90);
  tx.execute(status->{try{
   var other=InventoryOpeningLiveTest.user(jdbc);other.setCompanyId(-1);if(!manufacturers.isEmpty()){var r=new InventoryItemManufacturerRequest();r.itemId=items.stream().map(row->((Number)row.get("Id")).intValue()).filter(id->jdbc.queryForObject("SELECT COUNT(*) FROM Item WHERE Id=? AND OrganizationId=? AND CompanyId=?",Integer.class,id,u.getOrganizationId(),u.getCompanyId())==1).findFirst().orElseThrow();r.manufacturerId=((Number)manufacturers.get(0).get("Id")).intValue();r.active=true;var saved=service.save(r);r.id=((Number)saved.get("Id")).intValue();assertEquals(r.itemId,saved.get("ItemId"));assertEquals(r.manufacturerId,saved.get("ManufactureId"));assertEquals(true,saved.get("IsActive"));r.active=false;assertEquals(false,service.save(r).get("IsActive"));assertThrows(org.springframework.web.server.ResponseStatusException.class,()->repo.record(other,r.id));}else{var invalid=new InventoryItemManufacturerRequest();invalid.itemId=((Number)items.get(0).get("Id")).intValue();invalid.manufacturerId=-1;assertThrows(IllegalArgumentException.class,()->service.save(invalid));}
   var definition=new InventoryLookupDefinitionRequest();definition.typeId=((Number)lookupRepo.types(u).get(0).get("Id")).intValue();definition.code=lookupRepo.code(u,definition.typeId);definition.name="Inventory rollback manufacturer lookup";var lookup=lookupService.save(definition);definition.id=((Number)lookup.get("Id")).intValue();assertEquals(definition.code,lookup.get("Code"));assertEquals(u.getId(),lookup.get("EntryUser"));assertEquals(u.getCompanyId(),lookup.get("CompanyId"));assertEquals(u.getOrganizationId(),lookup.get("OrganizationId"));var entry=lookup.get("EntryDate");definition.name="Inventory rollback lookup updated";var updated=lookupService.save(definition);assertEquals(definition.name,updated.get("LookupName"));assertEquals(entry,updated.get("EntryDate"));assertEquals(u.getId(),updated.get("ModifyUser"));assertFalse(Boolean.TRUE.equals(lookupRepo.record(other,definition.id).get("CanEdit")));assertThrows(org.springframework.security.access.AccessDeniedException.class,()->lookupRepo.save(other,definition));return null;
  }finally{status.setRollbackOnly();}});
  assertEquals(before,jdbc.queryForList("SELECT * FROM ItemAllocateToManufactures ORDER BY Id"));assertEquals(definitionsBefore,jdbc.queryForList("SELECT * FROM InvLookUp ORDER BY Id"));Files.writeString(Path.of("migration/inventory/evidence/item-manufacturers-rollback.txt"),"frmItemAllocateToManufacturer: original items "+items.size()+", manufacturer choices "+manufacturers.size()+" and history match. "+(manufacturers.isEmpty()?"Manufacturer CRUD blocked: original catalog and type14 absent; invalid manufacturer rejected.":"Manufacturer insert/load/update/inactivate and ownership passed.")+" Linked frmInvLookup insert/load/update/code/audit using an existing profile type and foreign-company edit denial passed. ItemAllocateToManufactures and InvLookUp unchanged after rollback. Original shared catalog reads retained; edits ownership-guarded. Rights mocked; browser/native pending.\n");
 }
}

