package com.mst.repositories;
import com.mst.models.dto.InventoryStoreStockRequest;
import com.mst.security.*;
import com.mst.services.InventoryStoreStockService;
import java.math.BigDecimal;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
@EnabledIfSystemProperty(named="inventory.rollback",matches="true")
class InventoryStoreStockLiveTest {
 @Test void reportModesDependentLookupsAndManualRateWriterMatchDesktop()throws Exception{
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);var repo=new InventoryStoreStockRepository(jdbc);var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var service=new InventoryStoreStockService(repo,context,rights);
  var branches=repo.branches(u);assertFalse(branches.isEmpty());var ids=branches.stream().map(row->((Number)row.get("BranchId")).intValue()).toList();String branchCsv=String.join(",",ids.stream().map(String::valueOf).toList());sameRows(jdbc.queryForList("EXEC dbo.USP_Evalaution_DropDown_ByParentCategories @OrganizationId=?, @CompanyId=?, @BranchesIds=?, @InventoryParentCategory='7,8'",u.getOrganizationId(),u.getCompanyId(),branchCsv),service.choices(ids));assertThrows(IllegalArgumentException.class,()->service.choices(List.of(-1)));
  var r=new InventoryStoreStockRequest();r.branchIds=ids;r.parentIds=List.of(7,8);var dates=jdbc.queryForMap("SELECT CONVERT(date,MIN(s.DocDate)) AS FirstDate,CONVERT(date,MAX(s.DocDate)) AS LastDate FROM InventoryStockEvalautionDetail s INNER JOIN Item i ON i.Id=s.ItemId INNER JOIN ItemCategory c ON c.Id=i.ItemCategoryId WHERE s.OrganizationId=? AND s.CompanyId=? AND c.InventoryParentCategoriesId IN (7,8)",u.getOrganizationId(),u.getCompanyId());assertNotNull(dates.get("FirstDate"));r.fromDate=((java.sql.Date)dates.get("FirstDate")).toLocalDate();r.toDate=((java.sql.Date)dates.get("LastDate")).toLocalDate();var counts=new LinkedHashMap<String,Integer>();
  for(String mode:List.of("ItemStockSummary","WarehouseAndItem","ItemAndWarehouse","ItemandPackSizeStockSummary")){r.reportType=mode;String activity=mode.equals("WarehouseAndItem")||mode.equals("ItemAndWarehouse")?"ItemandWarehouseStockSummary":mode;var expected=ReportValueSupport.decimalStrings(jdbc.queryForList("EXEC dbo.Sp_ItemStockReportWithValues_Store @OrganizationId=?, @CompanyId=?, @DateFrom=?, @DateTo=?, @InventoryParentCategoriesIds='7,8', @BranchesIds=?, @IsPackSizeOn=1, @IsPackTypeOn=1, @Activity=?",u.getOrganizationId(),u.getCompanyId(),java.sql.Date.valueOf(r.fromDate),java.sql.Date.valueOf(r.toDate),branchCsv,activity));var actual=repo.load(u,r);sameRows(expected,actual);counts.put(mode,actual.size());}
  r.reportType="ItemStockSummary";var rows=repo.load(u,r);assertFalse(rows.isEmpty());var row=rows.stream().filter(record->InventoryStoreStockRepository.decimal(record.get("BalWeight")).signum()>0).findFirst().orElseThrow();var years=repo.years(u);assertEquals(1,years.size());int year=((Number)years.get(0).get("Id")).intValue();var before=jdbc.queryForList("SELECT * FROM StockSummaryByItem ORDER BY Id");var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);tx.setTimeout(60);
  tx.execute(status->{try{repo.saveRate(u,year,r,row,new BigDecimal("123"));var saved=jdbc.queryForMap("SELECT * FROM StockSummaryByItem WHERE ItemId=? AND ItemUOMId=? AND PackingTypeId=? AND CONVERT(date,DocDate)=?",row.get("ItemId"),row.get("PackUomId"),row.get("PackingTypeId"),java.sql.Date.valueOf(r.toDate));assertEquals(u.getOrganizationId(),saved.get("OrganizationId"));assertEquals(u.getCompanyId(),saved.get("CompanyId"));assertEquals(123d,((Number)saved.get("ItemRate")).doubleValue());assertEquals(InventoryStoreStockRepository.decimal(row.get("BalWeight")).doubleValue()*123d,((Number)saved.get("Amount")).doubleValue(),0.000001);var entry=saved.get("EntryDate");repo.saveRate(u,year,r,row,new BigDecimal("124"));var updated=jdbc.queryForMap("SELECT * FROM StockSummaryByItem WHERE Id=?",saved.get("Id"));assertEquals(124d,((Number)updated.get("ItemRate")).doubleValue());assertEquals(entry,updated.get("EntryDate"));assertEquals(u.getId(),updated.get("ModifyUserId"));assertEquals(2,updated.get("ActionId"));var foreign=InventoryOpeningLiveTest.user(jdbc);foreign.setCompanyId(-1);assertThrows(IllegalArgumentException.class,()->repo.saveRate(foreign,year,r,row,new BigDecimal("125")));return null;}finally{status.setRollbackOnly();}});
  assertEquals(before,jdbc.queryForList("SELECT * FROM StockSummaryByItem ORDER BY Id"));Files.writeString(Path.of("migration/inventory/evidence/store-stock-live.txt"),"Store Stock288: four source modes matched every returned value: "+counts+". Dependent dropdown query and allocated-branch rejection passed. Manual rate insert/load/update, amount calculation, audit, foreign-company-key guard and complete StockSummaryByItem rollback passed. Source manual configuration="+repo.manual(u)+". Writer test directly exercises original writer without changing that configuration. Rights mocked; UI/native, original report outputs, linked store ledger and full service write workflow pending.\n");
 }
 private static void sameRows(List<Map<String,Object>> a,List<Map<String,Object>> b){assertEquals(a.size(),b.size());var left=normalized(a);var right=normalized(b);assertTrue(left.equals(right),"Returned row values differ");}
 private static Map<String,Integer> normalized(List<Map<String,Object>> rows){var result=new HashMap<String,Integer>();for(var row:rows){var normalized=new TreeMap<String,String>();row.forEach((k,v)->normalized.put(k,v instanceof byte[] bytes?Base64.getEncoder().encodeToString(bytes):Objects.toString(v,"<null>")));result.merge(normalized.toString(),1,Integer::sum);}return result;}
}
