package com.mst.repositories;

import com.mst.models.dto.InventoryGridColumn;
import com.mst.security.*;
import com.mst.services.DesktopInventoryGridLayoutService;
import java.nio.file.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@EnabledIfSystemProperty(named="inventory.rollback",matches="true")
class InventoryGridLayoutLiveTest {
 @TempDir Path directory;
 @Test void uomLayoutUsesNativeColumnNamesAndRollsBack()throws Exception{
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);u.setUserName(jdbc.queryForObject("SELECT UserName FROM UserAccount WHERE Id=?",String.class,u.getId()));var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var repo=new DesktopInventoryGridLayoutRepository(jdbc);var service=new DesktopInventoryGridLayoutService(repo,context,rights,directory.toString());
  String name="InvDeffrmItemUomSchedule_grdfrm_"+u.getUserName();var file=directory.resolve(name);var columns=new ArrayList<InventoryGridColumn>();for(String key:List.of("Item","Schedule Unit","Equivalent","QtyEquivalent","BaseRateUom","BasePackUom","BaseSecondaryUom","Active")){var c=new InventoryGridColumn();c.key=key;c.position=columns.size();c.width=130;c.visible=!key.equals("BaseSecondaryUom");columns.add(c);}
  String sql="SELECT Id,ScreenName,Layout,EntryDate,EntryUserId,OrganizationId,CompanyId,CONVERT(varchar(max),LayoutFile,2) FileHex,CONVERT(nvarchar(max),LayoutFileXml) FileXml FROM GridLayout ORDER BY Id";var before=jdbc.queryForList(sql);var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);
  tx.execute(status->{try{assertEquals(8,service.save("uom-schedules",columns).size());var saved=service.load("uom-schedules");assertFalse(saved.stream().filter(c->c.key.equals("BaseSecondaryUom")).findFirst().orElseThrow().visible);assertTrue(Files.readString(file).contains("ID=\"Schedule Unit\""));assertTrue(repo.exists(u,name));service.remove("uom-schedules");assertFalse(Files.exists(file));service.save("uom-schedules",columns);return null;}catch(Exception ex){throw new RuntimeException(ex);}finally{status.setRollbackOnly();}});
  assertFalse(Files.exists(file));assertEquals(before,jdbc.queryForList(sql));verify(rights,atLeastOnce()).require(u,115,"View");verify(rights,never()).require(u,111,"View");Files.writeString(Path.of("migration/inventory/evidence/uom-layout-rollback.txt"),"UOM Schedule: all8 source column keys including Item and Schedule Unit; own115 rights, native user/form/grid filename, visibility and save/load/remove verified. Original GridLayout rows and temporary file restored after rollback. No C:/SCS writes. Native Janus rendering and browser persistence pending.\n");
 }

 @Test void brandLayoutUsesNativeColumnNamesAndRollsBack()throws Exception{
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);u.setUserName(jdbc.queryForObject("SELECT UserName FROM UserAccount WHERE Id=?",String.class,u.getId()));var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var repo=new DesktopInventoryGridLayoutRepository(jdbc);var service=new DesktopInventoryGridLayoutService(repo,context,rights,directory.toString());
  String name="DefineBrand_grdfrm_"+u.getUserName();var file=directory.resolve(name);var columns=new ArrayList<InventoryGridColumn>();for(String key:List.of("BrandCode","BrandName","EntryUser","EntryDate","ModifyUser","ModifyDate")){var c=new InventoryGridColumn();c.key=key;c.position=columns.size();c.width=130;c.visible=!key.equals("ModifyUser");columns.add(c);}
  String sql="SELECT Id,ScreenName,Layout,EntryDate,EntryUserId,OrganizationId,CompanyId,CONVERT(varchar(max),LayoutFile,2) FileHex,CONVERT(nvarchar(max),LayoutFileXml) FileXml FROM GridLayout ORDER BY Id";var before=jdbc.queryForList(sql);var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);
  tx.execute(status->{try{assertEquals(6,service.save("brands",columns).size());var saved=service.load("brands");assertFalse(saved.stream().filter(c->c.key.equals("ModifyUser")).findFirst().orElseThrow().visible);assertTrue(Files.readString(file).contains("ID=\"BrandName\""));assertTrue(repo.exists(u,name));service.remove("brands");assertFalse(Files.exists(file));service.save("brands",columns);return null;}catch(Exception ex){throw new RuntimeException(ex);}finally{status.setRollbackOnly();}});
  assertFalse(Files.exists(file));assertEquals(before,jdbc.queryForList(sql));verify(rights,atLeastOnce()).require(u,876,"View");verify(rights,never()).require(u,111,"View");Files.writeString(Path.of("migration/inventory/evidence/brand-layout-rollback.txt"),"Brand: all6 source column keys including BrandCode and BrandName; own876 rights, native user/form/grid filename, visibility and save/load/remove verified. Original GridLayout rows and temporary file restored after rollback. No C:/SCS writes. Native Janus rendering and browser persistence pending.\n");
 }

 @Test void lotLayoutUsesNativeColumnNamesAndRollsBack()throws Exception{
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);u.setUserName(jdbc.queryForObject("SELECT UserName FROM UserAccount WHERE Id=?",String.class,u.getId()));var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var repo=new DesktopInventoryGridLayoutRepository(jdbc);var service=new DesktopInventoryGridLayoutService(repo,context,rights,directory.toString());
  String name="AcfrmDefineLots_GridDefinelots_"+u.getUserName();var file=directory.resolve(name);var columns=new ArrayList<InventoryGridColumn>();for(String key:List.of("JobLotCode","JobLotDescription","AccountTitle","StartDate","EndDate","JobStatus","JobType","RefDocumentType","RefDocNo","IsCompany","IsThirdParty")){var c=new InventoryGridColumn();c.key=key;c.position=columns.size();c.width=130;c.visible=!key.equals("IsThirdParty");columns.add(c);}
  String sql="SELECT Id,ScreenName,Layout,EntryDate,EntryUserId,OrganizationId,CompanyId,CONVERT(varchar(max),LayoutFile,2) FileHex,CONVERT(nvarchar(max),LayoutFileXml) FileXml FROM GridLayout ORDER BY Id";var before=jdbc.queryForList(sql);var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);
  tx.execute(status->{try{assertEquals(11,service.save("lots",columns).size());var saved=service.load("lots");assertFalse(saved.stream().filter(c->c.key.equals("IsThirdParty")).findFirst().orElseThrow().visible);assertTrue(Files.readString(file).contains("ID=\"JobLotDescription\""));assertTrue(repo.exists(u,name));service.remove("lots");assertFalse(Files.exists(file));service.save("lots",columns);return null;}catch(Exception ex){throw new RuntimeException(ex);}finally{status.setRollbackOnly();}});
  assertFalse(Files.exists(file));assertEquals(before,jdbc.queryForList(sql));verify(rights,atLeastOnce()).require(u,110,"View");verify(rights,never()).require(u,111,"View");Files.writeString(Path.of("migration/inventory/evidence/lot-layout-rollback.txt"),"Lots: all11 source column keys including JobLotCode and JobLotDescription; own110 rights, native user/form/grid filename, visibility and save/load/remove verified. Original GridLayout rows and temporary file restored after rollback. No C:/SCS writes. Native Janus rendering and browser persistence pending.\n");
 }

 @Test void typeLayoutUsesNativeColumnNamesAndRollsBack()throws Exception{
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);u.setUserName(jdbc.queryForObject("SELECT UserName FROM UserAccount WHERE Id=?",String.class,u.getId()));var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var repo=new DesktopInventoryGridLayoutRepository(jdbc);var service=new DesktopInventoryGridLayoutService(repo,context,rights,directory.toString());
  String name="InvDeffrmItemType_grdhistory_"+u.getUserName();var file=directory.resolve(name);var columns=new ArrayList<InventoryGridColumn>();for(String key:List.of("Code","Description","Type","ParentCategory","MotherStatus")){var c=new InventoryGridColumn();c.key=key;c.position=columns.size();c.width=130;c.visible=!key.equals("MotherStatus");columns.add(c);}
  String sql="SELECT Id,ScreenName,Layout,EntryDate,EntryUserId,OrganizationId,CompanyId,CONVERT(varchar(max),LayoutFile,2) FileHex,CONVERT(nvarchar(max),LayoutFileXml) FileXml FROM GridLayout ORDER BY Id";var before=jdbc.queryForList(sql);var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);
  tx.execute(status->{try{assertEquals(5,service.save("item_types",columns).size());var saved=service.load("item_types");assertFalse(saved.stream().filter(c->c.key.equals("MotherStatus")).findFirst().orElseThrow().visible);assertTrue(Files.readString(file).contains("ID=\"Description\""));assertTrue(repo.exists(u,name));service.remove("item_types");assertFalse(Files.exists(file));service.save("item_types",columns);return null;}catch(Exception ex){throw new RuntimeException(ex);}finally{status.setRollbackOnly();}});
  assertFalse(Files.exists(file));assertEquals(before,jdbc.queryForList(sql));verify(rights,atLeastOnce()).require(u,113,"View");verify(rights,never()).require(u,111,"View");Files.writeString(Path.of("migration/inventory/evidence/type-layout-rollback.txt"),"Item Type: all5 source column keys including Code and Description; own113 rights, native user/form/grid filename, visibility and save/load/remove verified. Original GridLayout rows and temporary file restored after rollback. No C:/SCS writes. Native Janus rendering and browser persistence pending.\n");
 }

 @Test void categoryLayoutUsesNativeColumnNamesAndRollsBack()throws Exception{
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);u.setUserName(jdbc.queryForObject("SELECT UserName FROM UserAccount WHERE Id=?",String.class,u.getId()));var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var repo=new DesktopInventoryGridLayoutRepository(jdbc);var service=new DesktopInventoryGridLayoutService(repo,context,rights,directory.toString());
  String name="InvDeffrmItemCatagory_grdfrm_"+u.getUserName();var file=directory.resolve(name);var columns=new ArrayList<InventoryGridColumn>();for(String key:List.of("CategoryCode","CategoryDescription","SerialFrom","SerialTo","CategoryStatus","ParentCategory","CGSAccountTitle","RevenueAccountTitle","InventoryAccountTitle","ClassGroupName","ProductionStage","VarietyNature")){var c=new InventoryGridColumn();c.key=key;c.position=columns.size();c.width=130;c.visible=!key.equals("VarietyNature");columns.add(c);}
  String sql="SELECT Id,ScreenName,Layout,EntryDate,EntryUserId,OrganizationId,CompanyId,CONVERT(varchar(max),LayoutFile,2) FileHex,CONVERT(nvarchar(max),LayoutFileXml) FileXml FROM GridLayout ORDER BY Id";var before=jdbc.queryForList(sql);var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);
  tx.execute(status->{try{assertEquals(12,service.save("definition-categories",columns).size());var saved=service.load("definition-categories");assertFalse(saved.stream().filter(c->c.key.equals("VarietyNature")).findFirst().orElseThrow().visible);assertTrue(Files.readString(file).contains("ID=\"CategoryDescription\""));assertTrue(repo.exists(u,name));service.remove("definition-categories");assertFalse(Files.exists(file));service.save("definition-categories",columns);return null;}catch(Exception ex){throw new RuntimeException(ex);}finally{status.setRollbackOnly();}});
  assertFalse(Files.exists(file));assertEquals(before,jdbc.queryForList(sql));verify(rights,atLeastOnce()).require(u,112,"View");verify(rights,never()).require(u,111,"View");Files.writeString(Path.of("migration/inventory/evidence/category-layout-rollback.txt"),"Category: all12 source column keys including CategoryCode and CategoryDescription; own112 rights, native user/form/grid filename, visibility and save/load/remove verified. Original GridLayout rows and temporary file restored after rollback. No C:/SCS writes. Native Janus rendering and browser persistence pending.\n");
 }

 @Test void posLayoutUsesNativeColumnNamesAndRollsBack()throws Exception{
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);u.setUserName(jdbc.queryForObject("SELECT UserName FROM UserAccount WHERE Id=?",String.class,u.getId()));var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var repo=new DesktopInventoryGridLayoutRepository(jdbc);var service=new DesktopInventoryGridLayoutService(repo,context,rights,directory.toString());
  String name="InvAddItemsPOS_grdhistoryForHistory_"+u.getUserName();var file=directory.resolve(name);var columns=new ArrayList<InventoryGridColumn>();for(String key:List.of("ItemCode","ItemName","ItemCategory","ItemType","StockAccount","SaleAccount","CgsAccount","UserName","NoOfAttachments")){var c=new InventoryGridColumn();c.key=key;c.position=columns.size();c.width=130;c.visible=!key.equals("UserName");columns.add(c);}
  String sql="SELECT Id,ScreenName,Layout,EntryDate,EntryUserId,OrganizationId,CompanyId,CONVERT(varchar(max),LayoutFile,2) FileHex,CONVERT(nvarchar(max),LayoutFileXml) FileXml FROM GridLayout ORDER BY Id";var before=jdbc.queryForList(sql);var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);
  tx.execute(status->{try{assertEquals(9,service.save("pos-items",columns).size());var saved=service.load("pos-items");assertFalse(saved.stream().filter(c->c.key.equals("UserName")).findFirst().orElseThrow().visible);assertTrue(Files.readString(file).contains("ID=\"ItemName\""));assertTrue(repo.exists(u,name));service.remove("pos-items");assertFalse(Files.exists(file));service.save("pos-items",columns);return null;}catch(Exception ex){throw new RuntimeException(ex);}finally{status.setRollbackOnly();}});
  assertFalse(Files.exists(file));assertEquals(before,jdbc.queryForList(sql));verify(rights,atLeastOnce()).require(u,106,"View");verify(rights,never()).require(u,111,"View");Files.writeString(Path.of("migration/inventory/evidence/pos-layout-rollback.txt"),"POS Item: all9 source column keys including ItemCode and ItemName; own106 rights, native user/form/grid filename, visibility and save/load/remove verified. Original GridLayout rows and temporary file restored after rollback. No C:/SCS writes. Native Janus rendering and browser persistence pending.\n");
 }

 @Test void openingLayoutRetainsItsLeadingEditButtonAndRestoresTheOriginalFile()throws Exception{
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);u.setUserName(jdbc.queryForObject("SELECT UserName FROM UserAccount WHERE Id=?",String.class,u.getId()));var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var repo=new DesktopInventoryGridLayoutRepository(jdbc);var service=new DesktopInventoryGridLayoutService(repo,context,rights,directory.toString());
  String name="frmOpeningStockBlancing_DataGridHistory_"+u.getUserName();var file=directory.resolve(name);var columns=new ArrayList<InventoryGridColumn>();for(String key:List.of("DocNo","DocDate","Item","ItemUOM","Crop","JobLot","Warehouse","PackingType","StockCreditAccount","Qty","Weight","Rate","RateUOM","Amount","Remarks","IssueWeight","EntryDate","EntryUser","ModifyDate","ModifyUser","NoOfAttachments")){var c=new InventoryGridColumn();c.key=key;c.position=columns.size();c.width=130;c.visible=true;columns.add(c);}
  String sql="SELECT Id,ScreenName,Layout,EntryDate,EntryUserId,OrganizationId,CompanyId,CONVERT(varchar(max),LayoutFile,2) FileHex,CONVERT(nvarchar(max),LayoutFileXml) FileXml FROM GridLayout ORDER BY Id";var before=jdbc.queryForList(sql);var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);
  tx.execute(status->{try{var saved=service.save("opening-stock",columns);assertEquals(21,saved.size());assertEquals(0,saved.stream().filter(c->c.key.equals("DocNo")).findFirst().orElseThrow().position);var xml=javax.xml.parsers.DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(file.toFile());var xpath=javax.xml.xpath.XPathFactory.newInstance().newXPath();assertEquals("0",xpath.evaluate("string(//Columns/*[@ID='Edit']/Position)",xml));assertEquals("1",xpath.evaluate("string(//Columns/*[@ID='DocNo']/Position)",xml));assertEquals("ButtonCell",xpath.evaluate("string(//Columns/*[@ID='Edit']/ButtonStyle)",xml));assertEquals("true",xpath.evaluate("string(//Columns/*[@ID='Edit']/Visible)",xml));assertEquals("false",xpath.evaluate("string(//Columns/*[@ID='Id']/Visible)",xml));assertEquals(21,service.load("opening-stock").size());service.remove("opening-stock");assertFalse(Files.exists(file));return null;}catch(Exception ex){throw new RuntimeException(ex);}finally{status.setRollbackOnly();}});
  assertEquals(before,jdbc.queryForList(sql));assertFalse(Files.exists(file));verify(rights,atLeastOnce()).require(u,92,"View");
  Files.writeString(Path.of("migration/inventory/evidence/opening-layout-rollback.txt"),"Opening Stock92 history layout: original form/grid/user registration, all21 native data keys, leading visible Edit button at position0, data position offset, hidden Id, save/load/remove and full GridLayout/file rollback passed. Temporary file only, no C:/SCS writes. Rights mocked; browser and native layout rendering pending.\n");
 }
 @Test void storeLedgerUsesItsOwnDesktopLayoutAndScreenBoundary()throws Exception{
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);u.setUserName(jdbc.queryForObject("SELECT UserName FROM UserAccount WHERE Id=?",String.class,u.getId()));var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var repo=new DesktopInventoryGridLayoutRepository(jdbc);var service=new DesktopInventoryGridLayoutService(repo,context,rights,directory.toString());
  String name="InventoryEvaluationItemLedgerForStore_grd_"+u.getUserName();Path file=directory.resolve(name);var columns=new ArrayList<InventoryGridColumn>();
  for(String key:List.of("BranchName","DocNo","TranDate","DocType","Description","WareHouse","RackName","ItemCategory","ItemType","ItemName","PackSize","ItemCondition","QtyIn","QtyOut","BalQty","WeightIn","WeightOut","BalWeight","AmountIn","AmountOut","BalAmount","ItemRate","AvgRate")){var c=new InventoryGridColumn();c.key=key;c.position=columns.size();c.width=130;c.visible=!Set.of("BalQty","BalWeight","BalAmount","AvgRate").contains(key);columns.add(c);}
  String sql="SELECT Id,ScreenName,Layout,EntryDate,EntryUserId,OrganizationId,CompanyId,CONVERT(varchar(max),LayoutFile,2) FileHex,CONVERT(nvarchar(max),LayoutFileXml) FileXml FROM GridLayout ORDER BY Id";var before=jdbc.queryForList(sql);var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);
  tx.execute(status->{try{assertEquals(23,service.save("store-item-ledger",columns).size());var saved=service.load("store-item-ledger");assertFalse(saved.stream().filter(c->c.key.equals("BalQty")).findFirst().orElseThrow().visible);var registration=jdbc.queryForMap("EXEC dbo.USP_GridLayout_ReadById @OrganizationId=?,@CompanyId=?,@Layout=?",u.getOrganizationId(),u.getCompanyId(),name);assertEquals("InventoryEvaluationItemLedgerForStore",registration.get("ScreenName"));assertTrue(Files.readString(file).contains("ID=\"DocumentTypeId\""));service.remove("store-item-ledger");assertFalse(Files.exists(file));service.save("store-item-ledger",columns);return null;}catch(Exception ex){throw new RuntimeException(ex);}finally{status.setRollbackOnly();}});
  assertFalse(Files.exists(file));assertEquals(before,jdbc.queryForList(sql));assertThrows(IllegalArgumentException.class,()->service.load("../unknown"));verify(rights,atLeastOnce()).require(u,288,"View");verify(rights,never()).require(u,111,"View");
  Files.writeString(Path.of("migration/inventory/evidence/store-ledger-layout-rollback.txt"),"Store Item Ledger: all23 native column keys, source form/grid/user file name, source GridLayout registration, hidden balance columns, save/load/remove/recreate and full database/file rollback passed. Original Define Item layout regression test also run. Temporary file only; no C:/SCS writes. Rights mocked; native Janus/browser compatibility pending.\n");
 }
 @Test void desktopLayoutRegistrationAndFileBothRollback()throws Exception{
  var jdbc=InventoryOpeningLiveTest.jdbc();var u=InventoryOpeningLiveTest.user(jdbc);u.setUserName(jdbc.queryForObject("SELECT UserName FROM UserAccount WHERE Id=?",String.class,u.getId()));var context=mock(CurrentUserContext.class);when(context.requireAccountingUser()).thenReturn(u);var rights=mock(DesktopReportRights.class);var repo=new DesktopInventoryGridLayoutRepository(jdbc);var service=new DesktopInventoryGridLayoutService(repo,context,rights,directory.toString());
  String name="InvDefrmAddItem_grdhistory_"+u.getUserName();Path file=directory.resolve(name);String original="<GridEXLayoutData><RootTable><Columns Collection=\"true\" ElementName=\"Column\"><Column0 ID=\"ItemName\"><Key>ItemName</Key><Width>150</Width><CustomFormat>retain</CustomFormat></Column0><Column3 ID=\"Id\"><Key>Id</Key><Visible>false</Visible></Column3></Columns><HeaderLines>2</HeaderLines></RootTable></GridEXLayoutData>";Files.writeString(file,original);
  String snapshotSql="SELECT Id,ScreenName,Layout,EntryDate,EntryUserId,OrganizationId,CompanyId,CONVERT(varchar(max),LayoutFile,2) AS FileHex,CONVERT(nvarchar(max),LayoutFileXml) AS FileXml FROM GridLayout ORDER BY Id";var before=jdbc.queryForList(snapshotSql);var tx=new TransactionTemplate(new DataSourceTransactionManager(jdbc.getDataSource()));tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_SERIALIZABLE);tx.setTimeout(30);
  var columns=new ArrayList<InventoryGridColumn>();for(String key:List.of("ItemCodeNew","ItemName","ItemNameOtherLingo","TypeDescription","CategoryDescription","ParentCategory","ClassGroupName","ItemStatus","StockAc","SaleAc","CgsAc","ItemWithVarient","MotherItem","IsCompany","IsThirdParty","EntryDate","EntryUserName","NoOfAttachments")){var c=new InventoryGridColumn();c.key=key;c.position=columns.size();c.width=120;c.visible=true;columns.add(c);}columns.get(1).width=234;columns.get(2).visible=false;
  tx.execute(status->{try{
   assertEquals(18,service.save(columns).size());var registration=jdbc.queryForMap("EXEC dbo.USP_GridLayout_ReadById @OrganizationId=?, @CompanyId=?, @Layout=?",u.getOrganizationId(),u.getCompanyId(),name);assertEquals(u.getId(),registration.get("EntryUserId"));assertEquals("InvDefrmAddItem",registration.get("ScreenName"));assertNull(registration.get("LayoutFile"));assertNull(registration.get("LayoutFileXml"));assertEquals(234,service.load().stream().filter(c->c.key.equals("ItemName")).findFirst().orElseThrow().width);assertFalse(service.load().stream().filter(c->c.key.equals("ItemNameOtherLingo")).findFirst().orElseThrow().visible);String xml=Files.readString(file);assertTrue(xml.contains("<CustomFormat>retain</CustomFormat>"));assertTrue(xml.contains("<HeaderLines>2</HeaderLines>"));assertTrue(xml.contains("ID=\"Id\""));
   var other=InventoryOpeningLiveTest.user(jdbc);other.setUserName(u.getUserName());other.setCompanyId(-1);assertFalse(repo.exists(other,name));
   service.remove();assertFalse(Files.exists(file));assertFalse(repo.exists(u,name));assertTrue(service.load().isEmpty());
   assertEquals(18,service.save(columns).size());assertTrue(Files.exists(file));return null;
  }catch(Exception ex){throw new RuntimeException(ex);}finally{status.setRollbackOnly();}});
  assertEquals(before,jdbc.queryForList(snapshotSql));assertEquals(original,Files.readString(file));
  var invalid=new ArrayList<>(columns);invalid.remove(0);assertThrows(IllegalArgumentException.class,()->service.save(invalid));
  String validUser=u.getUserName();u.setUserName("../escape");assertThrows(IllegalArgumentException.class,service::load);u.setUserName(validUser);
  verify(rights,atLeastOnce()).require(u,111,"View");
  Files.writeString(Path.of("migration/inventory/evidence/general-item-grid-layout-rollback.txt"),"Define Item history grid: original GridLayout procedures and user/company registration; visibility, width, XML preservation, delete/recreate, tenant lookup isolation and path validation passed. Full original GridLayout rows and temporary native XML restored after rollback. No C:/SCS files touched by this test. Rights mocked. Desktop Janus/browser compatibility remains unverified.\n");
 }
}
