package com.mst.repositories;

import static org.junit.jupiter.api.Assertions.*;
import com.mst.models.UserAccount;
import java.nio.file.*;
import java.time.LocalDate;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

@EnabledIfSystemProperty(named="sale.live",matches="true")
class SaleGdnRollbackLiveTest {
 @Test void insertLoadUpdateDeleteAndRollback() throws Exception {
  var p=new Properties();try(var in=Files.newInputStream(Path.of("src/main/resources/application.properties"))){p.load(in);}var ds=new DriverManagerDataSource(p.getProperty("spring.datasource.url"),p.getProperty("spring.datasource.username"),p.getProperty("spring.datasource.password"));var j=new JdbcTemplate(ds);j.setQueryTimeout(120);
  var a=j.queryForMap("SELECT ID,OrganizationId,CompanyId,BranchesId,AppId FROM UserAccount WHERE UserName='numan'");var u=new UserAccount();u.setId(n(a.get("ID")));u.setOrganizationId(n(a.get("OrganizationId")));u.setCompanyId(n(a.get("CompanyId")));u.setBranchesId(n(a.get("BranchesId")));u.setAppId(n(a.get("AppId")));
  var repo=new SaleGdnRepository(j);var initial=repo.initial(u,58);int doc=n(initial.get("nextNo")),before=j.queryForObject("SELECT COUNT(*) FROM InvGdn WHERE OrganizationId=78 AND CompanyId=78 AND DocumentTypeId=86",Integer.class),city=((List<Map<String,Object>>)initial.get("cities")).stream().map(x->n(x.get("Id"))).filter(x->x>0).findFirst().orElseThrow();Map<Integer,String> cropNames=new HashMap<>();for(var x:(List<Map<String,Object>>)initial.get("crops"))cropNames.put(n(x.get("Id")),String.valueOf(x.get("CropYear")));
  var candidates=j.queryForList("SELECT TOP 300 d.* FROM InvDeliveryOrderDetail d JOIN InvDeliveryOrder h ON h.Id=d.InvDeliveryOrderId WHERE h.OrganizationId=78 AND h.CompanyId=78 AND d.SaleOrderDetailId>0 AND d.WarehouseId>0 AND d.PackUomId>0 AND d.CropYearId>0 AND d.JobLotId>0 AND d.InvPackingTypeId>0 ORDER BY d.Id DESC");Map<String,Object> order=null;double available=0;for(var x:candidates){String crop=cropNames.get(n(x.get("CropYearId")));if(crop==null)continue;var stock=j.queryForList("EXEC dbo.USP_GetStockByFifoMethod @OrganizationId=78,@CompanyId=78,@ItemId=?,@DocDate=?,@PackUomId=?,@WarehouseId=?,@CropYearId=?,@JobLotId=?,@PackingTypeId=?,@CropYear=?,@DocumentTypeId=86,@Id=0",n(x.get("ItemId")),LocalDate.now().toString(),n(x.get("PackUomId")),n(x.get("WarehouseId")),n(x.get("CropYearId")),n(x.get("JobLotId")),n(x.get("InvPackingTypeId")),crop);available=stock.stream().mapToDouble(z->d(z.get("NetBalWeight"))).sum();if(available>.01){order=x;break;}}assertNotNull(order,"No delivery-order detail with matching FIFO stock was found");int customer=n(order.get("SupplierCustomerId")),cropId=n(order.get("CropYearId"));String crop=cropNames.get(cropId);double weight=Math.min(.01,available/10d),qty=.001;
  var detail=new LinkedHashMap<String,Object>();detail.put("Id",0);detail.put("ActionTypeId",1);detail.put("OrderId",n(order.get("InvDeliveryOrderId")));detail.put("SaleOrderId",n(order.get("SaleOrderId")));detail.put("SaleOrderDetailId",n(order.get("SaleOrderDetailId")));detail.put("WarehouseId",n(order.get("WarehouseId")));detail.put("ItemId",n(order.get("ItemId")));detail.put("Item","Rollback stock item");detail.put("PackingTypeId",n(order.get("InvPackingTypeId")));detail.put("CropYear",crop);detail.put("CropYearId",cropId);detail.put("JobLotId",n(order.get("JobLotId")));detail.put("ItemQty",qty);detail.put("ItemUomId",n(order.get("PackUomId")));detail.put("GrossWeight",weight);detail.put("EBWPerUnit",0d);detail.put("EBWTotal",0d);detail.put("WtCut",0d);detail.put("WtCutTotal",0d);detail.put("AdLsWeight",0d);detail.put("NetBillWeight",weight);detail.put("StockWeight",weight);detail.put("CityId",city);detail.put("AreaCity","Rollback City");detail.put("RefDocumentTypeId",0);detail.put("RefDocIdNo",0);detail.put("RefDocSubIdNo",0);
  var request=new LinkedHashMap<String,Object>();request.put("DocNo",doc);request.put("DocDate",LocalDate.now().toString());request.put("SupplierCustomerId",customer);request.put("StockPartyId",customer);request.put("GpNo",0);request.put("FactoryWeight",weight);request.put("VehicleNo","ROLLBACK-86");request.put("BiltyNo","RB");request.put("RemarksHeader","CODEX GDN ROLLBACK TEST");request.put("details",new ArrayList<>(List.of(detail)));request.put("expenses",List.of());request.put("id",0);
  var tx=new TransactionTemplate(new DataSourceTransactionManager(ds));tx.execute(status->{int id=repo.save(u,58,request);assertTrue(id>0);var saved=repo.record(u,id);assertEquals(86,n(saved.get("DocumentTypeId")));var rows=(List<Map<String,Object>>)saved.get("details");assertEquals(1,rows.size());detail.put("Id",n(rows.get(0).get("Id")));detail.put("ActionTypeId",2);detail.put("ItemQty",0.03d);request.put("id",id);assertEquals(id,repo.save(u,58,request));repo.delete(u,id);assertThrows(Exception.class,()->repo.record(u,id));status.setRollbackOnly();return null;});
  int after=j.queryForObject("SELECT COUNT(*) FROM InvGdn WHERE OrganizationId=78 AND CompanyId=78 AND DocumentTypeId=86",Integer.class);assertEquals(before,after);Files.createDirectories(Path.of("migration/sale/evidence"));Files.writeString(Path.of("migration/sale/evidence/gdn-rollback.txt"),"Document 86 insert, tenant-safe load, update, desktop delete procedure and transaction rollback executed against GoldenAcedb for Numan 78/78/58 year 58. Header/detail/inventory/FIFO/validation/in-transit procedure chain ran and final InvGdn count remained "+after+" (before "+before+").\n");
 }
 static int n(Object o){return o instanceof Number?((Number)o).intValue():0;}
 static double d(Object o){return o instanceof Number?((Number)o).doubleValue():0;}
}
