package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Banking print request models. Generated by gen_print_endpoints.py. */
public final class BankingPrintRequests {
    private BankingPrintRequests() { }

    /** Request for /reports/print/01-fcy-ex-rate-forwward-booking-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt01FcyExRateForwwardBookingSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** bankId -> @BankId (optional) */
        public Integer bankId;
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("bankId", bankId);
            args.put("branchesId", branchesId);
            return args;
        }
    }

    /** Request for /reports/print/102-payment-receipts-voucher-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt102PaymentReceiptsVoucherSlipRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/102-bank-receipt-voucher */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt102BankReceiptVoucherRequest {
        /** id -> @Id (optional) */
        public Integer id;
        /** fromDocNo -> @VoucherCodeF (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @VoucherCodeT (optional) */
        public Integer toDocNo;
        /** documentTypeIds -> @DocumentTypeIds (optional); comma separated */
        public String documentTypeIds;
        /** ids -> @Ids (optional); comma separated */
        public String ids;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("documentTypeIds", documentTypeIds);
            args.put("ids", ids);
            return args;
        }
    }

    /** Request for /reports/print/105-01-bank-summary-ledger */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt10501BankSummaryLedgerRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** accountIds -> @AccountIds (optional); comma separated */
        public String accountIds;
        /** accountTypeIds -> @AccountTypeIds (optional); comma separated */
        public String accountTypeIds;
        /** accountTypeId -> @AccountTypeId (optional) */
        public Integer accountTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("accountIds", accountIds);
            args.put("accountTypeIds", accountTypeIds);
            args.put("accountTypeId", accountTypeId);
            return args;
        }
    }

    /** Request for /reports/print/105-02-bank-summary-ledger */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt10502BankSummaryLedgerRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** accountIds -> @AccountIds (optional); comma separated */
        public String accountIds;
        /** accountTypeIds -> @AccountTypeIds (optional); comma separated */
        public String accountTypeIds;
        /** accountTypeId -> @AccountTypeId (optional) */
        public Integer accountTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("accountIds", accountIds);
            args.put("accountTypeIds", accountTypeIds);
            args.put("accountTypeId", accountTypeId);
            return args;
        }
    }

    /** Request for /reports/print/105c-fcy-general-ledger */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt105CFcyGeneralLedgerRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @EndDate (optional); yyyy-MM-dd */
        public String toDate;
        /** accountId -> @AccountId (optional) */
        public Integer accountId;
        /** accountIds -> @AccountIds (optional); comma separated */
        public String accountIds;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** languageId -> @LanguageId (optional) */
        public Integer languageId;
        /** subsidiaryAccountId -> @SubsidiaryAccountId (optional) */
        public Integer subsidiaryAccountId;
        /** subsidiaryTypeId -> @SubsidiaryTypeId (optional) */
        public Integer subsidiaryTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("accountId", accountId);
            args.put("accountIds", accountIds);
            args.put("isApproved", isApproved);
            args.put("languageId", languageId);
            args.put("subsidiaryAccountId", subsidiaryAccountId);
            args.put("subsidiaryTypeId", subsidiaryTypeId);
            return args;
        }
    }

    /** Request for /reports/print/105d-fcy-general-ledger */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt105DFcyGeneralLedgerRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @EndDate (optional); yyyy-MM-dd */
        public String toDate;
        /** accountId -> @AccountId (optional) */
        public Integer accountId;
        /** accountIds -> @AccountIds (optional); comma separated */
        public String accountIds;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** languageId -> @LanguageId (optional) */
        public Integer languageId;
        /** subsidiaryAccountId -> @SubsidiaryAccountId (optional) */
        public Integer subsidiaryAccountId;
        /** subsidiaryTypeId -> @SubsidiaryTypeId (optional) */
        public Integer subsidiaryTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("accountId", accountId);
            args.put("accountIds", accountIds);
            args.put("isApproved", isApproved);
            args.put("languageId", languageId);
            args.put("subsidiaryAccountId", subsidiaryAccountId);
            args.put("subsidiaryTypeId", subsidiaryTypeId);
            return args;
        }
    }

    /** Request for /reports/print/123-pdc-inventory-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt123PdcInventorySlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            return args;
        }
    }

    /** Request for /reports/print/127-pdc-inventory-pending-guri-wise */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt127PdcInventoryPendingGuriWiseRequest {
        /** accountId -> @GLCrAccountId (optional) */
        public Integer accountId;
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** cheqDateFrom -> @DateFromCheq (optional); yyyy-MM-dd */
        public String cheqDateFrom;
        /** cheqDateTo -> @DateToCheq (optional); yyyy-MM-dd */
        public String cheqDateTo;
        /** chartOfAccountId -> @GLDrAccountId (optional) */
        public Integer chartOfAccountId;
        /** status -> @CheqStatus (optional) */
        public String status;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("accountId", accountId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("cheqDateFrom", cheqDateFrom);
            args.put("cheqDateTo", cheqDateTo);
            args.put("chartOfAccountId", chartOfAccountId);
            args.put("status", status);
            return args;
        }
    }

    /** Request for /reports/print/153-fcy-payables-and-receivables */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt153FCYPayablesAndReceivablesRequest {
        /** companyIds -> @CompanyIds (optional); comma separated */
        public String companyIds;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** fromdate -> @FromDate (required); yyyy-MM-dd */
        public String fromdate;
        /** todate -> @ToDate (required); yyyy-MM-dd */
        public String todate;
        /** accountTypeId -> @AccountTypeId (optional) */
        public Integer accountTypeId;
        /** actionId -> @ResultTypId (optional) */
        public Integer actionId;
        /** activityId -> @TransTypeId (optional) */
        public Integer activityId;
        /** exchangeRateUSD -> @ExchangeRateUSD (required) */
        public String exchangeRateUSD;
        /** exchangeRateEURO -> @ExchangeRateEURO (required) */
        public String exchangeRateEURO;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("companyIds", companyIds);
            args.put("branchesIds", branchesIds);
            args.put("fromdate", fromdate);
            args.put("todate", todate);
            args.put("accountTypeId", accountTypeId);
            args.put("actionId", actionId);
            args.put("activityId", activityId);
            args.put("exchangeRateUSD", exchangeRateUSD);
            args.put("exchangeRateEURO", exchangeRateEURO);
            return args;
        }
    }

    /** Request for /reports/print/156-fcy-general-ledger */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt156FcyGeneralLedgerRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** accountTypeId -> @AccountTypeId (optional) */
        public Integer accountTypeId;
        /** accountId -> @AccountId (required) */
        public Integer accountId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("accountTypeId", accountTypeId);
            args.put("accountId", accountId);
            return args;
        }
    }

    /** Request for /reports/print/176-fcy-adjustment-voucher-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt176FcyAdjustmentVoucherSlipRequest {
        /** fromDate -> @VoucherDateF (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @VoucherDateT (optional); yyyy-MM-dd */
        public String toDate;
        /** id -> @Id (required) */
        public Integer id;
        /** fromDocNo -> @VoucherCodeF (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @VoucherCodeT (optional) */
        public Integer toDocNo;
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** accountId -> @DebitAccountId (optional) */
        public Integer accountId;
        /** creditAccountId -> @CreditAccountId (optional) */
        public Integer creditAccountId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("id", id);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("accountId", accountId);
            args.put("creditAccountId", creditAccountId);
            return args;
        }
    }

    /** Request for /reports/print/1801-loan-registration-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1801LoanRegistrationSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/350-fcy-journal-voucher-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt350FcyJournalVoucherSlipRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** voucherHeadId -> @Id (required) */
        public Integer voucherHeadId;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("voucherHeadId", voucherHeadId);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/481-stock-reconcilation-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt481StockReconcilationRegisterRequest {
        /** fromDate -> @DateFrom (required); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (required); yyyy-MM-dd */
        public String toDate;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** parentCategoryIds -> @ParentCategoryIds (optional); comma separated */
        public String parentCategoryIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemId", itemId);
            args.put("warehouseId", warehouseId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("itemTypeId", itemTypeId);
            args.put("parentCategoryIds", parentCategoryIds);
            return args;
        }
    }

    /** Request for /reports/print/598-payment-and-receipts-customers-and-supplir-wise */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt598PaymentAndReceiptsCustomersAndSupplirWiseRequest {
        /** fromDate -> @FromDate (required); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (required); yyyy-MM-dd */
        public String toDate;
        /** activity -> @TransType (optional) */
        public String activity;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("activity", activity);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/document-type-id-loan-facility-agreement-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptDocumentTypeIdLoanFacilityAgreementSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            return args;
        }
    }
}
