package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** CommissionTrading print request models. Generated by gen_print_endpoints.py. */
public final class CommissionTradingPrintRequests {
    private CommissionTradingPrintRequests() { }

    /** Request for /reports/print/1056-01-commission-agent-trade-bill-purchase-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt105601CommissionAgentTradeBillPurchaseSlipRequest {
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("itemId", itemId);
            return args;
        }
    }

    /** Request for /reports/print/1056-02-commission-agent-trade-bill-sale-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt105602CommissionAgentTradeBillSaleSlipRequest {
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("itemId", itemId);
            return args;
        }
    }

    /** Request for /reports/print/1056-03-commission-agent-trade-bill-sale-slip-ii */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt105603CommissionAgentTradeBillSaleSlipIIRequest {
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("itemId", itemId);
            return args;
        }
    }

    /** Request for /reports/print/1056-commission-agent-trade-bill-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1056CommissionAgentTradeBillSlipRequest {
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("itemId", itemId);
            return args;
        }
    }

    /** Request for /reports/print/1056a-commission-bill-income-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1056ACommissionBillIncomeSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1702-commission-trade-loading-delivery-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1702CommissionTradeLoadingDeliveryRegisterRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (optional) */
        public Integer id;
        /** customerId -> @CustomerId (optional) */
        public Integer customerId;
        /** supplierId -> @SupplierId (optional) */
        public Integer supplierId;
        /** commissionAgentId -> @BrokerId (optional) */
        public Integer commissionAgentId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** languageId -> @LanguageId (optional) */
        public Integer languageId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("customerId", customerId);
            args.put("supplierId", supplierId);
            args.put("commissionAgentId", commissionAgentId);
            args.put("itemId", itemId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            args.put("languageId", languageId);
            return args;
        }
    }

    /** Request for /reports/print/1702-commission-trade-loading-delivery-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1702CommissionTradeLoadingDeliverySlipRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (optional) */
        public Integer id;
        /** customerId -> @CustomerId (optional) */
        public Integer customerId;
        /** supplierId -> @SupplierId (optional) */
        public Integer supplierId;
        /** commissionAgentId -> @BrokerId (optional) */
        public Integer commissionAgentId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** languageId -> @LanguageId (optional) */
        public Integer languageId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("customerId", customerId);
            args.put("supplierId", supplierId);
            args.put("commissionAgentId", commissionAgentId);
            args.put("itemId", itemId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            args.put("languageId", languageId);
            return args;
        }
    }

    /** Request for /reports/print/1702a-commission-trade-loading-delivery-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1702ACommissionTradeLoadingDeliverySlipRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (optional) */
        public Integer id;
        /** customerId -> @CustomerId (optional) */
        public Integer customerId;
        /** supplierId -> @SupplierId (optional) */
        public Integer supplierId;
        /** commissionAgentId -> @BrokerId (optional) */
        public Integer commissionAgentId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** languageId -> @LanguageId (optional) */
        public Integer languageId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("customerId", customerId);
            args.put("supplierId", supplierId);
            args.put("commissionAgentId", commissionAgentId);
            args.put("itemId", itemId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            args.put("languageId", languageId);
            return args;
        }
    }

    /** Request for /reports/print/1704-commission-transaction-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1704CommissionTransactionRegisterRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (optional) */
        public Integer id;
        /** customerId -> @CustomerId (optional) */
        public Integer customerId;
        /** supplierId -> @SupplierId (optional) */
        public Integer supplierId;
        /** commissionAgentId -> @CommissionAgentId (optional) */
        public Integer commissionAgentId;
        /** subBrokerId -> @SubBrokerId (optional) */
        public Integer subBrokerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** languageId -> @LanguageId (optional) */
        public Integer languageId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("customerId", customerId);
            args.put("supplierId", supplierId);
            args.put("commissionAgentId", commissionAgentId);
            args.put("subBrokerId", subBrokerId);
            args.put("itemId", itemId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            args.put("languageId", languageId);
            return args;
        }
    }

    /** Request for /reports/print/1704-comm-trade-transaction-customer-expense-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1704CommTradeTransactionCustomerExpenseSubReportRequest {
        /** id -> @CommTradeTransactionHeaderId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1704-comm-trade-transaction-header-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1704CommTradeTransactionHeaderSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** customerId -> @CustomerId (optional) */
        public Integer customerId;
        /** supplierId -> @SupplierId (optional) */
        public Integer supplierId;
        /** commissionAgentId -> @CommissionAgentId (optional) */
        public Integer commissionAgentId;
        /** subBrokerId -> @SubBrokerId (optional) */
        public Integer subBrokerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** languageId -> @LanguageId (optional) */
        public Integer languageId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("customerId", customerId);
            args.put("supplierId", supplierId);
            args.put("commissionAgentId", commissionAgentId);
            args.put("subBrokerId", subBrokerId);
            args.put("itemId", itemId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            args.put("languageId", languageId);
            return args;
        }
    }

    /** Request for /reports/print/1704-01-comm-trade-transaction-slip-with-supplier */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt170401CommTradeTransactionSlipWithSupplierRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (optional) */
        public Integer id;
        /** customerId -> @CustomerId (optional) */
        public Integer customerId;
        /** supplierId -> @SupplierId (optional) */
        public Integer supplierId;
        /** commissionAgentId -> @CommissionAgentId (optional) */
        public Integer commissionAgentId;
        /** subBrokerId -> @SubBrokerId (optional) */
        public Integer subBrokerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** languageId -> @LanguageId (optional) */
        public Integer languageId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("customerId", customerId);
            args.put("supplierId", supplierId);
            args.put("commissionAgentId", commissionAgentId);
            args.put("subBrokerId", subBrokerId);
            args.put("itemId", itemId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            args.put("languageId", languageId);
            return args;
        }
    }

    /** Request for /reports/print/1704-01-comm-trade-transaction-supplier-summary-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt170401CommTradeTransactionSupplierSummarySubReportRequest {
        /** id -> @CommTradeTransactionHeaderId (required) */
        public Integer id;
        /** languageId -> @LanguageId (required) */
        public Integer languageId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("languageId", languageId);
            return args;
        }
    }

    /** Request for /reports/print/1705-commission-order-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1705CommissionOrderRegisterRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (optional) */
        public Integer id;
        /** customerId -> @CustomerId (optional) */
        public Integer customerId;
        /** supplierId -> @SupplierId (optional) */
        public Integer supplierId;
        /** commissionAgentId -> @CommissionAgentId (optional) */
        public Integer commissionAgentId;
        /** subBrokerId -> @SubBrokerId (optional) */
        public Integer subBrokerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("customerId", customerId);
            args.put("supplierId", supplierId);
            args.put("commissionAgentId", commissionAgentId);
            args.put("subBrokerId", subBrokerId);
            args.put("itemId", itemId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            return args;
        }
    }

    /** Request for /reports/print/1705-commission-trade-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1705CommissionTradeOrderSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** customerId -> @CustomerId (optional) */
        public Integer customerId;
        /** supplierId -> @SupplierId (optional) */
        public Integer supplierId;
        /** commissionAgentId -> @CommissionAgentId (optional) */
        public Integer commissionAgentId;
        /** subBrokerId -> @SubBrokerId (optional) */
        public Integer subBrokerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("customerId", customerId);
            args.put("supplierId", supplierId);
            args.put("commissionAgentId", commissionAgentId);
            args.put("subBrokerId", subBrokerId);
            args.put("itemId", itemId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            return args;
        }
    }

    /** Request for /reports/print/1706-commission-bill-supplier-customer-and-income-transactions */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1706CommissionBillSupplierCustomerAndIncomeTransactionsRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/238-inv-purchase-invoice-store-bill-with-tax */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt238InvPurchaseInvoiceStoreBillWithTaxRequest {
        /** id -> @PihId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/477-inventory-transaction */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt477InventoryTransactionRequest {
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** cropYear -> @CropYear (optional) */
        public String cropYear;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** parentCategoryId -> @InventoryParentCategoriesId (optional) */
        public Integer parentCategoryId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("warehouseId", warehouseId);
            args.put("jobLotId", jobLotId);
            args.put("documentTypeId", documentTypeId);
            args.put("cropYear", cropYear);
            args.put("packingTypeId", packingTypeId);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("itemTypeId", itemTypeId);
            args.put("parentCategoryId", parentCategoryId);
            return args;
        }
    }

    /** Request for /reports/print/478-evaluation-transaction */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt478EvaluationTransactionRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** cropYear -> @CropYear (optional) */
        public String cropYear;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** stockUOM -> @SaleValue (optional) */
        public String stockUOM;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("cropYear", cropYear);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("stockUOM", stockUOM);
            args.put("documentTypeId", documentTypeId);
            return args;
        }
    }

    /** Request for /reports/print/479-01-item-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt47901ItemStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("packingTypeId", packingTypeId);
            args.put("rateUOM", rateUOM);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            args.put("actionId", actionId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/479-02-itemand-warehouse-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt47902ItemandWarehouseStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("packingTypeId", packingTypeId);
            args.put("rateUOM", rateUOM);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            args.put("actionId", actionId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/479-03-warehouse-and-item-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt47903WarehouseAndItemStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("packingTypeId", packingTypeId);
            args.put("rateUOM", rateUOM);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            args.put("actionId", actionId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/479-04-job-lotand-item-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt47904JobLotandItemStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("packingTypeId", packingTypeId);
            args.put("rateUOM", rateUOM);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            args.put("actionId", actionId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/479-05-warehouseand-joblotand-item-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt47905WarehouseandJoblotandItemStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("packingTypeId", packingTypeId);
            args.put("rateUOM", rateUOM);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            args.put("actionId", actionId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/479-06-warehouseand-itemand-joblot-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt47906WarehouseandItemandJoblotStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("packingTypeId", packingTypeId);
            args.put("rateUOM", rateUOM);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            args.put("actionId", actionId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/479-07-itemand-pack-size-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt47907ItemandPackSizeStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("packingTypeId", packingTypeId);
            args.put("rateUOM", rateUOM);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            args.put("actionId", actionId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/479-08-itemand-item-attribute-varient-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt47908ItemandItemAttributeVarientStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("packingTypeId", packingTypeId);
            args.put("rateUOM", rateUOM);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            args.put("actionId", actionId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/479-09-itemand-pack-sizeand-item-attribute-varient-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt47909ItemandPackSizeandItemAttributeVarientStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("packingTypeId", packingTypeId);
            args.put("rateUOM", rateUOM);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            args.put("actionId", actionId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/480-01-item-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt48001ItemStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** parentCategoryId -> @ParentCategoryId (optional) */
        public Integer parentCategoryId;
        /** ids -> @ParentCategoryIds (optional); comma separated */
        public String ids;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("parentCategoryId", parentCategoryId);
            args.put("ids", ids);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("rateUOM", rateUOM);
            args.put("packingTypeId", packingTypeId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/480-02-itemand-warehouse-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt48002ItemandWarehouseStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** parentCategoryId -> @ParentCategoryId (optional) */
        public Integer parentCategoryId;
        /** ids -> @ParentCategoryIds (optional); comma separated */
        public String ids;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("parentCategoryId", parentCategoryId);
            args.put("ids", ids);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("rateUOM", rateUOM);
            args.put("packingTypeId", packingTypeId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/480-03-warehouse-and-item-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt48003WarehouseAndItemStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** parentCategoryId -> @ParentCategoryId (optional) */
        public Integer parentCategoryId;
        /** ids -> @ParentCategoryIds (optional); comma separated */
        public String ids;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("parentCategoryId", parentCategoryId);
            args.put("ids", ids);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("rateUOM", rateUOM);
            args.put("packingTypeId", packingTypeId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/480-06-job-lotand-item-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt48006JobLotandItemStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** parentCategoryId -> @ParentCategoryId (optional) */
        public Integer parentCategoryId;
        /** ids -> @ParentCategoryIds (optional); comma separated */
        public String ids;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("parentCategoryId", parentCategoryId);
            args.put("ids", ids);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("rateUOM", rateUOM);
            args.put("packingTypeId", packingTypeId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/480-07-item-warehouse-and-joblot-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt48007ItemWarehouseAndJoblotStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** parentCategoryId -> @ParentCategoryId (optional) */
        public Integer parentCategoryId;
        /** ids -> @ParentCategoryIds (optional); comma separated */
        public String ids;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("parentCategoryId", parentCategoryId);
            args.put("ids", ids);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("rateUOM", rateUOM);
            args.put("packingTypeId", packingTypeId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/480-08-itemand-pack-size-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt48008ItemandPackSizeStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** parentCategoryId -> @ParentCategoryId (optional) */
        public Integer parentCategoryId;
        /** ids -> @ParentCategoryIds (optional); comma separated */
        public String ids;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("parentCategoryId", parentCategoryId);
            args.put("ids", ids);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("rateUOM", rateUOM);
            args.put("packingTypeId", packingTypeId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/480-09-itemand-item-attribute-varient-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt48009ItemandItemAttributeVarientStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** parentCategoryId -> @ParentCategoryId (optional) */
        public Integer parentCategoryId;
        /** ids -> @ParentCategoryIds (optional); comma separated */
        public String ids;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("parentCategoryId", parentCategoryId);
            args.put("ids", ids);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("rateUOM", rateUOM);
            args.put("packingTypeId", packingTypeId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/480-10-itemand-pack-sizeand-item-attribute-varient-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt48010ItemandPackSizeandItemAttributeVarientStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** parentCategoryId -> @ParentCategoryId (optional) */
        public Integer parentCategoryId;
        /** ids -> @ParentCategoryIds (optional); comma separated */
        public String ids;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** packingTypeId -> @PackingTypeId (optional) */
        public Integer packingTypeId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** allowWipItem -> @AllowWipItem (optional) */
        public String allowWipItem;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("parentCategoryId", parentCategoryId);
            args.put("ids", ids);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("rateUOM", rateUOM);
            args.put("packingTypeId", packingTypeId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("allowWipItem", allowWipItem);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/556-commission-trade-loading-delivery-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt556CommissionTradeLoadingDeliverySlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** customerId -> @CustomerId (optional) */
        public Integer customerId;
        /** supplierId -> @SupplierId (optional) */
        public Integer supplierId;
        /** commissionAgentId -> @BrokerId (optional) */
        public Integer commissionAgentId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** languageId -> @LanguageId (optional) */
        public Integer languageId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("customerId", customerId);
            args.put("supplierId", supplierId);
            args.put("commissionAgentId", commissionAgentId);
            args.put("itemId", itemId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            args.put("languageId", languageId);
            return args;
        }
    }

    /** Request for /reports/print/comm-trade-loading-delivery-expense-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptCommTradeLoadingDeliveryExpenseSubReportRequest {
        /** id -> @CommTradeLoadingDeliveryId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/comm-trade-loading-delivery-pm-expense-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptCommTradeLoadingDeliveryPMExpenseSubReportRequest {
        /** id -> @CommTradeLoadingDeliveryId (required) */
        public Integer id;
        /** languageId -> @LanguageId (required) */
        public Integer languageId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("languageId", languageId);
            return args;
        }
    }

    /** Request for /reports/print/comm-trade-transaction-pm-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptCommTradeTransactionPMSubReportRequest {
        /** id -> @CommTradeTransactionHeaderId (required) */
        public Integer id;
        /** languageId -> @LanguageId (required) */
        public Integer languageId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("languageId", languageId);
            return args;
        }
    }

    /** Request for /reports/print/inv-commission-agent-bill-other-exp */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptInvCommissionAgentBillOtherExpRequest {
        /** id -> @PihId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }
}
