package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** CommissionAgent print request models. Generated by gen_print_endpoints.py. */
public final class CommissionAgentPrintRequests {
    private CommissionAgentPrintRequests() { }

    /** Request for /reports/print/1050-buyer-inquiry-booking-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1050BuyerInquiryBookingSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1055-gdn-buyer-dispatch-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1055GdnBuyerDispatchSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1054-grn-supplier-loading-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1054GrnSupplierLoadingSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1054-01-grn-supplier-loading-challan-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt105401GrnSupplierLoadingChallanSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1052-purchase-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1052PurchaseOrderSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1053-sale-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1053SaleOrderSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1050a-buyer-inquiry-booking-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1050ABuyerInquiryBookingSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1051-supplier-offer-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1051SupplierOfferSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }
}
