package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Dashboard print request models. Generated by gen_print_endpoints.py. */
public final class DashboardPrintRequests {
    private DashboardPrintRequests() { }

    /** Request for /reports/print/121-02-receivables-and-receipt-schedule */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt12102ReceivablesAndReceiptScheduleRequest {
        /** inventoryParentCategories -> @ParentCategoryId (required) */
        public String inventoryParentCategories;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** dueDateFrom -> @DueDateFrom (optional); yyyy-MM-dd */
        public String dueDateFrom;
        /** dueDateTo -> @DueDateTo (optional); yyyy-MM-dd */
        public String dueDateTo;
        /** effectedDate -> @SaleFromDate (optional); yyyy-MM-dd */
        public String effectedDate;
        /** effectedDateTo -> @SaleToDate (optional); yyyy-MM-dd */
        public String effectedDateTo;
        /** balanceFrom -> @BalanceFrom (optional); yyyy-MM-dd */
        public String balanceFrom;
        /** balanceTo -> @BalanceTo (optional); yyyy-MM-dd */
        public String balanceTo;
        /** customGroupId -> @CustomGroupId (optional) */
        public Integer customGroupId;
        /** customerGroupId -> @PartyGroupId (optional) */
        public Integer customerGroupId;
        /** controlAccountIds -> @ControlAccountIds (optional); comma separated */
        public String controlAccountIds;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;
        /** reportTypeId -> @TradeTypeId (optional) */
        public Integer reportTypeId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("dueDateFrom", dueDateFrom);
            args.put("dueDateTo", dueDateTo);
            args.put("effectedDate", effectedDate);
            args.put("effectedDateTo", effectedDateTo);
            args.put("balanceFrom", balanceFrom);
            args.put("balanceTo", balanceTo);
            args.put("customGroupId", customGroupId);
            args.put("customerGroupId", customerGroupId);
            args.put("controlAccountIds", controlAccountIds);
            args.put("actionId", actionId);
            args.put("reportTypeId", reportTypeId);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/842-item-and-pm-item-map-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt842ItemAndPMItemMapSlipRequest {
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** pmItemId -> @PmItemId (optional) */
        public Integer pmItemId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("itemId", itemId);
            args.put("pmItemId", pmItemId);
            return args;
        }
    }

    /** Request for /reports/print/121-03-purchase-analytics-item-wise */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt12103PurchaseAnalyticsItemWiseRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** cropYear -> @CropYear (optional) */
        public String cropYear;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** reportType -> @ReportType (required) */
        public String reportType;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemCategoryId", itemCategoryId);
            args.put("itemTypeId", itemTypeId);
            args.put("jobLotId", jobLotId);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("cropYear", cropYear);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("branchesIds", branchesIds);
            args.put("reportType", reportType);
            return args;
        }
    }

    /** Request for /reports/print/121-04-purchase-analytics-supplier-wise */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt12104PurchaseAnalyticsSupplierWiseRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** cropYear -> @CropYear (optional) */
        public String cropYear;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** reportType -> @ReportType (required) */
        public String reportType;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemCategoryId", itemCategoryId);
            args.put("itemTypeId", itemTypeId);
            args.put("jobLotId", jobLotId);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("cropYear", cropYear);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("branchesIds", branchesIds);
            args.put("reportType", reportType);
            return args;
        }
    }

    /** Request for /reports/print/audit-activiy-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptAuditActiviyReportRequest {

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            return args;
        }
    }
}
