package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** FeedMill print request models. Generated by gen_print_endpoints.py. */
public final class FeedMillPrintRequests {
    private FeedMillPrintRequests() { }

    /** Request for /reports/print/1100-purchase-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1100PurchaseOrderSlipRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @Todate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** status -> @Status (optional) */
        public String status;
        /** id -> @Id (required) */
        public Integer id;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("status", status);
            args.put("id", id);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("isApproved", isApproved);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            return args;
        }
    }

    /** Request for /reports/print/1110-sale-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1110SaleOrderSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1110-customer-discount-policy-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1110CustomerDiscountPolicySlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1115-inv-rep-sale-bill-customer */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1115InvRepSaleBillCustomerRequest {
        /** id -> @Id (optional) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1863-purchase-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1863PurchaseOrderSlipRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @Todate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** status -> @Status (optional) */
        public String status;
        /** id -> @Id (required) */
        public Integer id;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategories (optional) */
        public String inventoryParentCategories;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("status", status);
            args.put("id", id);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("isApproved", isApproved);
            args.put("documentTypeId", documentTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemTypeId", itemTypeId);
            return args;
        }
    }

    /** Request for /reports/print/481-item-pricing-schedule-list-group-wise */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt481ItemPricingScheduleListGroupWiseRequest {
        /** itemId -> @ItemId (required) */
        public Integer itemId;
        /** itemUomId -> @RateUomId (required) */
        public Integer itemUomId;
        /** groupId -> @PricingCustomGroupId (required) */
        public Integer groupId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("itemId", itemId);
            args.put("itemUomId", itemUomId);
            args.put("groupId", groupId);
            return args;
        }
    }

    /** Request for /reports/print/inv-purchase-invoice-item-expense-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptInvPurchaseInvoiceItemExpenseSubReportRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/purchase-invoice-supplier-expense-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptPurchaseInvoiceSupplierExpenseSubReportRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/sale-order-payment-terms-detail-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptSaleOrderPaymentTermsDetailSubReportRequest {
        /** orderId -> @OrderId (required) */
        public Integer orderId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("orderId", orderId);
            return args;
        }
    }
}
