package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Hrm print request models. Generated by gen_print_endpoints.py. */
public final class HrmPrintRequests {
    private HrmPrintRequests() { }

    /** Request for /reports/print/1003-daily-attendance */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1003DailyAttendanceRequest {
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** date -> @Date (optional); yyyy-MM-dd */
        public String date;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** designationId -> @DesignationId (optional) */
        public Integer designationId;
        /** shiftId -> @ShiftId (optional) */
        public Integer shiftId;
        /** locationId -> @LocationId (optional) */
        public Integer locationId;
        /** employeeCategoryId -> @EmployeeCategoryId (optional) */
        public Integer employeeCategoryId;
        /** sectionId -> @SectionId (optional) */
        public Integer sectionId;
        /** isMissing -> @IsMissing (optional) */
        public Boolean isMissing;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("departmentId", departmentId);
            args.put("date", date);
            args.put("employeeId", employeeId);
            args.put("designationId", designationId);
            args.put("shiftId", shiftId);
            args.put("locationId", locationId);
            args.put("employeeCategoryId", employeeCategoryId);
            args.put("sectionId", sectionId);
            args.put("isMissing", isMissing);
            return args;
        }
    }

    /** Request for /reports/print/1112-employee-registration-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1112EmployeeRegistrationSlipRequest {
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("employeeId", employeeId);
            return args;
        }
    }

    /** Request for /reports/print/1008-employee-advance-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1008EmployeeAdvanceSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1010-over-time-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1010OverTimeSlipRequest {
        /** id -> @Id (optional) */
        public Integer id;
        /** sectionId -> @SectionId (optional) */
        public Integer sectionId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** requestedById -> @RequestById (optional) */
        public Integer requestedById;
        /** toDate -> @RequestToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDate -> @RequestFromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** gpDateT -> @OverTimeToDate (optional); yyyy-MM-dd */
        public String gpDateT;
        /** gpDateF -> @OverTimeFromDate (optional); yyyy-MM-dd */
        public String gpDateF;
        /** entryDateFrom -> @EntryFromDate (optional); yyyy-MM-dd */
        public String entryDateFrom;
        /** entryDateTo -> @EntryToDate (optional); yyyy-MM-dd */
        public String entryDateTo;
        /** modifyDateFrom -> @ModifyFromDate (optional); yyyy-MM-dd */
        public String modifyDateFrom;
        /** modifyDateTo -> @ModifyToDate (optional); yyyy-MM-dd */
        public String modifyDateTo;
        /** approvedDateFrom -> @ApprovedFromDate (optional); yyyy-MM-dd */
        public String approvedDateFrom;
        /** approvedDateTo -> @ApprovedToDate (optional); yyyy-MM-dd */
        public String approvedDateTo;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("sectionId", sectionId);
            args.put("departmentId", departmentId);
            args.put("requestedById", requestedById);
            args.put("toDate", toDate);
            args.put("fromDate", fromDate);
            args.put("gpDateT", gpDateT);
            args.put("gpDateF", gpDateF);
            args.put("entryDateFrom", entryDateFrom);
            args.put("entryDateTo", entryDateTo);
            args.put("modifyDateFrom", modifyDateFrom);
            args.put("modifyDateTo", modifyDateTo);
            args.put("approvedDateFrom", approvedDateFrom);
            args.put("approvedDateTo", approvedDateTo);
            args.put("actionId", actionId);
            return args;
        }
    }

    /** Request for /reports/print/1113-daily-lateand-early-departure */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1113DailyLateandEarlyDepartureRequest {
        /** partyLocationId -> @PartyLocationId (optional) */
        public Integer partyLocationId;
        /** date -> @Date (optional); yyyy-MM-dd */
        public String date;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("partyLocationId", partyLocationId);
            args.put("date", date);
            return args;
        }
    }

    /** Request for /reports/print/1114-duty-roster-employee-wise */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1114DutyRosterEmployeeWiseRequest {
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** date -> @Date (optional); yyyy-MM-dd */
        public String date;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("employeeId", employeeId);
            args.put("date", date);
            return args;
        }
    }

    /** Request for /reports/print/1004-employee-attendance */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1004EmployeeAttendanceRequest {
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("employeeId", employeeId);
            args.put("departmentId", departmentId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            return args;
        }
    }

    /** Request for /reports/print/1005-monthly-attendance-register-new */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1005MonthlyAttendanceRegisterNewRequest {
        /** month -> @Month (required) */
        public Integer month;
        /** year -> @Year (required) */
        public Integer year;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("month", month);
            args.put("year", year);
            args.put("employeeId", employeeId);
            args.put("departmentId", departmentId);
            return args;
        }
    }

    /** Request for /reports/print/1001-employee-attendence-monthly */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1001EmployeeAttendenceMonthlyRequest {
        /** month -> @Month (required) */
        public Integer month;
        /** year -> @Year (required) */
        public Integer year;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** sectionId -> @SectionId (optional) */
        public Integer sectionId;
        /** partyLocationId -> @PartyLocationId (optional) */
        public Integer partyLocationId;
        /** shiftId -> @ShiftId (optional) */
        public Integer shiftId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("month", month);
            args.put("year", year);
            args.put("employeeId", employeeId);
            args.put("departmentId", departmentId);
            args.put("sectionId", sectionId);
            args.put("partyLocationId", partyLocationId);
            args.put("shiftId", shiftId);
            return args;
        }
    }

    /** Request for /reports/print/1002-attendance-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1002AttendanceRegisterRequest {
        /** month -> @Month (required) */
        public Integer month;
        /** year -> @Year (required) */
        public Integer year;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** shiftId -> @ShiftId (optional) */
        public Integer shiftId;
        /** sectionId -> @SectionId (optional) */
        public Integer sectionId;
        /** partyLocationId -> @PartyLocationId (optional) */
        public Integer partyLocationId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("month", month);
            args.put("year", year);
            args.put("departmentId", departmentId);
            args.put("employeeId", employeeId);
            args.put("shiftId", shiftId);
            args.put("sectionId", sectionId);
            args.put("partyLocationId", partyLocationId);
            return args;
        }
    }

    /** Request for /reports/print/1101-employee-list-department-wise-active-inactive */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1101EmployeeListDepartmentWiseActiveInactiveRequest {
        /** shiftId -> @ShiftId (optional) */
        public Integer shiftId;
        /** sectionId -> @SectionId (optional) */
        public Integer sectionId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** branchesId -> @BranchId (optional) */
        public Integer branchesId;
        /** designationId -> @DesignationId (optional) */
        public Integer designationId;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** active -> @Active (optional) */
        public String active;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("shiftId", shiftId);
            args.put("sectionId", sectionId);
            args.put("departmentId", departmentId);
            args.put("branchesId", branchesId);
            args.put("designationId", designationId);
            args.put("employeeId", employeeId);
            args.put("active", active);
            return args;
        }
    }

    /** Request for /reports/print/1101-01-employee-list-department-wise-active-inactive */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt110101EmployeeListDepartmentWiseActiveInactiveRequest {
        /** shiftId -> @ShiftId (optional) */
        public Integer shiftId;
        /** sectionId -> @SectionId (optional) */
        public Integer sectionId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** branchesId -> @BranchId (optional) */
        public Integer branchesId;
        /** partyLocationId -> @DesignationId (optional) */
        public Integer partyLocationId;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** isApproved -> @Active (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("shiftId", shiftId);
            args.put("sectionId", sectionId);
            args.put("departmentId", departmentId);
            args.put("branchesId", branchesId);
            args.put("partyLocationId", partyLocationId);
            args.put("employeeId", employeeId);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/1011-employee-over-time-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1011EmployeeOverTimeSlipRequest {
        /** month -> @Month (required) */
        public Integer month;
        /** year -> @Year (required) */
        public Integer year;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** dutyRoasterId -> @Id (optional) */
        public Integer dutyRoasterId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("month", month);
            args.put("year", year);
            args.put("employeeId", employeeId);
            args.put("dutyRoasterId", dutyRoasterId);
            return args;
        }
    }

    /** Request for /reports/print/1003-01-daily-attendance */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt100301DailyAttendanceRequest {
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** date -> @Date (optional); yyyy-MM-dd */
        public String date;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** designationId -> @DesignationId (optional) */
        public Integer designationId;
        /** shiftId -> @ShiftId (optional) */
        public Integer shiftId;
        /** locationId -> @LocationId (optional) */
        public Integer locationId;
        /** employeeCategoryId -> @EmployeeCategoryId (optional) */
        public Integer employeeCategoryId;
        /** sectionId -> @SectionId (optional) */
        public Integer sectionId;
        /** isMissing -> @IsMissing (optional) */
        public Boolean isMissing;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("departmentId", departmentId);
            args.put("date", date);
            args.put("employeeId", employeeId);
            args.put("designationId", designationId);
            args.put("shiftId", shiftId);
            args.put("locationId", locationId);
            args.put("employeeCategoryId", employeeCategoryId);
            args.put("sectionId", sectionId);
            args.put("isMissing", isMissing);
            return args;
        }
    }

    /** Request for /reports/print/1006-attendance-summery */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1006AttendanceSummeryRequest {
        /** month -> @Month (required) */
        public Integer month;
        /** year -> @Year (required) */
        public Integer year;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** sectionId -> @SectionId (optional) */
        public Integer sectionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("month", month);
            args.put("year", year);
            args.put("departmentId", departmentId);
            args.put("employeeId", employeeId);
            args.put("sectionId", sectionId);
            return args;
        }
    }

    /** Request for /reports/print/1007-daily-shift-strength-attendence-dpt */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1007DailyShiftStrengthAttendenceDptRequest {
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** shiftId -> @ShiftId (optional) */
        public Integer shiftId;
        /** docDate -> @date (optional); yyyy-MM-dd */
        public String docDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("departmentId", departmentId);
            args.put("shiftId", shiftId);
            args.put("docDate", docDate);
            return args;
        }
    }

    /** Request for /reports/print/1009-employee-over-time-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1009EmployeeOverTimeRegisterRequest {
        /** fromDate -> @FromDate (required); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (required); yyyy-MM-dd */
        public String toDate;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("employeeId", employeeId);
            args.put("departmentId", departmentId);
            return args;
        }
    }

    /** Request for /reports/print/1100-employee-salary-sheet */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1100EmployeeSalarySheetRequest {
        /** payrollId -> @PayrollId (optional) */
        public Integer payrollId;
        /** month -> @Month (required) */
        public Integer month;
        /** year -> @Year (required) */
        public Integer year;
        /** monthValue -> @MonthValue (required) */
        public String monthValue;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("payrollId", payrollId);
            args.put("month", month);
            args.put("year", year);
            args.put("monthValue", monthValue);
            return args;
        }
    }

    /** Request for /reports/print/1110-employee-salary-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1110EmployeeSalarySlipRequest {
        /** month -> @Month (required) */
        public Integer month;
        /** year -> @Year (required) */
        public Integer year;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** debitAccountId -> @DebitAccountId (optional) */
        public Integer debitAccountId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("month", month);
            args.put("year", year);
            args.put("employeeId", employeeId);
            args.put("departmentId", departmentId);
            args.put("debitAccountId", debitAccountId);
            return args;
        }
    }

    /** Request for /reports/print/1110b-employee-salary-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1110BEmployeeSalarySlipRequest {
        /** month -> @Month (required) */
        public Integer month;
        /** year -> @Year (required) */
        public Integer year;
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** debitAccountId -> @DebitAccountId (optional) */
        public Integer debitAccountId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("month", month);
            args.put("year", year);
            args.put("employeeId", employeeId);
            args.put("departmentId", departmentId);
            args.put("debitAccountId", debitAccountId);
            return args;
        }
    }

    /** Request for /reports/print/1111-employee-registration-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1111EmployeeRegistrationRegisterRequest {
        /** employeeId -> @EmployeeId (optional) */
        public Integer employeeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("employeeId", employeeId);
            return args;
        }
    }

    /** Request for /reports/print/1115-employee-salary-sheet */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1115EmployeeSalarySheetRequest {
        /** payrollId -> @PayrollId (optional) */
        public Integer payrollId;
        /** month -> @Month (required) */
        public Integer month;
        /** year -> @Year (required) */
        public Integer year;
        /** monthValue -> @MonthValue (required) */
        public String monthValue;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("payrollId", payrollId);
            args.put("month", month);
            args.put("year", year);
            args.put("monthValue", monthValue);
            return args;
        }
    }

    /** Request for /reports/print/1116-payroll-posting-for-multi-approval-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1116PayrollPostingForMultiApprovalReportRequest {
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** employeeCategoryId -> @EmployeeCategoryId (optional) */
        public Integer employeeCategoryId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** pageSize -> @PageSize (optional) */
        public Integer pageSize;
        /** pageNumber -> @PageNumber (optional) */
        public Integer pageNumber;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("employeeCategoryId", employeeCategoryId);
            args.put("departmentId", departmentId);
            args.put("isApproved", isApproved);
            args.put("pageSize", pageSize);
            args.put("pageNumber", pageNumber);
            return args;
        }
    }

    /** Request for /reports/print/employee-attendence-monthly */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptEmployeeAttendenceMonthlyRequest {
        /** month -> @Month (required) */
        public Integer month;
        /** grd -> @EmployeeId (required) */
        public String grd;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** sectionId -> @SectionId (optional) */
        public Integer sectionId;
        /** partyLocationId -> @PartyLocationId (optional) */
        public Integer partyLocationId;
        /** shiftId -> @ShiftId (optional) */
        public Integer shiftId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("month", month);
            args.put("grd", grd);
            args.put("departmentId", departmentId);
            args.put("sectionId", sectionId);
            args.put("partyLocationId", partyLocationId);
            args.put("shiftId", shiftId);
            return args;
        }
    }
}
