package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Import print request models. Generated by gen_print_endpoints.py. */
public final class ImportPrintRequests {
    private ImportPrintRequests() { }

    /** Request for /reports/print/231-im-lc-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt231ImLcOrderSlipRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** id -> @LcOrderId (optional) */
        public Integer id;
        /** fromDate -> @FromOrderDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToOrderDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @LcOrderNoFrom (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @LcOrderNoTo (optional) */
        public Integer toDocNo;
        /** status -> @Status (optional) */
        public String status;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("id", id);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("status", status);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            return args;
        }
    }

    /** Request for /reports/print/803-im-g-rn-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt803ImGRnSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** container1 -> @ContainerNo (optional) */
        public String container1;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("warehouseId", warehouseId);
            args.put("jobLotId", jobLotId);
            args.put("container1", container1);
            return args;
        }
    }

    /** Request for /reports/print/804-purchase-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt804PurchaseOrderSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** loadingPortId -> @LoadingPortId (optional) */
        public Integer loadingPortId;
        /** destinationPortId -> @DestinationPortId (optional) */
        public Integer destinationPortId;
        /** container1 -> @ContainerNo (optional) */
        public String container1;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("loadingPortId", loadingPortId);
            args.put("destinationPortId", destinationPortId);
            args.put("container1", container1);
            return args;
        }
    }

    /** Request for /reports/print/806-im-invoice-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt806ImInvoiceSlipRequest {
        /** id -> @Id (optional) */
        public Integer id;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/807-im-invoice-register-with-avg-rates */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt807ImInvoiceRegisterWithAvgRatesRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            return args;
        }
    }

    /** Request for /reports/print/808-import-contract-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt808ImportContractRegisterRequest {
        /** id -> @Id (optional) */
        public Integer id;
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** status -> @Status (optional) */
        public String status;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("status", status);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/809-import-packing-list-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt809ImportPackingListRegisterRequest {
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** id -> @Id (optional) */
        public Integer id;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** loadingPortId -> @LoadingPortId (optional) */
        public Integer loadingPortId;
        /** destinationPortId -> @DestinationPortId (optional) */
        public Integer destinationPortId;
        /** container1 -> @ContainerNo (optional) */
        public String container1;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("id", id);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("loadingPortId", loadingPortId);
            args.put("destinationPortId", destinationPortId);
            args.put("container1", container1);
            return args;
        }
    }

    /** Request for /reports/print/810-import-purchase-order */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt810ImportPurchaseOrderRequest {
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** id -> @Id (optional) */
        public Integer id;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** fcyId -> @CurrencyId (optional) */
        public Integer fcyId;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("id", id);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("fcyId", fcyId);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/811-import-grn-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt811ImportGrnRegisterRequest {
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** id -> @Id (optional) */
        public Integer id;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** container1 -> @ContainerNo (optional) */
        public String container1;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("id", id);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("warehouseId", warehouseId);
            args.put("jobLotId", jobLotId);
            args.put("container1", container1);
            return args;
        }
    }

    /** Request for /reports/print/900-proforma-invoice-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt900ProformaInvoiceSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @DocNoFrom (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @DocNoTo (optional) */
        public Integer toDocNo;
        /** exporterId -> @exporterId (optional) */
        public Integer exporterId;
        /** importerId -> @importerId (optional) */
        public Integer importerId;
        /** id -> @proformaMasterId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("exporterId", exporterId);
            args.put("importerId", importerId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/902-import-invoice-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt902ImportInvoiceSlipRequest {
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** actionId -> @IsForPackingList (optional) */
        public Integer actionId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @DocNoFrom (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @DocNoTo (optional) */
        public Integer toDocNo;
        /** exporterId -> @exporterId (optional) */
        public Integer exporterId;
        /** importerId -> @importerId (optional) */
        public Integer importerId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("actionId", actionId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("exporterId", exporterId);
            args.put("importerId", importerId);
            return args;
        }
    }

    /** Request for /reports/print/im-lc-order-payment-detail-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptImLcOrderPaymentDetailSubReportRequest {
        /** id -> @ImLcOrderId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/import-invoice-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptImportInvoiceSubReportRequest {
        /** id -> @InvoiceMasterId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }
}
