package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Inventory print request models. Generated by gen_print_endpoints.py. */
public final class InventoryPrintRequests {
    private InventoryPrintRequests() { }

    /** Request for /reports/print/326-get-items-from-min-and-max-rate-schedule */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt326GetItemsFromMinAndMaxRateScheduleRequest {
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** effectedDate -> @EffectedDate (optional); yyyy-MM-dd */
        public String effectedDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("itemCategoryId", itemCategoryId);
            args.put("itemTypeId", itemTypeId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("effectedDate", effectedDate);
            return args;
        }
    }

    /** Request for /reports/print/326-01-items-from-min-and-max-rate-schedule-form-history */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt32601ItemsFromMinAndMaxRateScheduleFormHistoryRequest {
        /** itemId -> @ItemId (required) */
        public Integer itemId;
        /** rateUOM -> @RateUomId (optional) */
        public String rateUOM;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("itemId", itemId);
            args.put("rateUOM", rateUOM);
            return args;
        }
    }

    /** Request for /reports/print/417-inventory-stock-transactions-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt417InventoryStockTransactionsReportRequest {
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** parentCategoryId -> @InventoryParentCategoriesId (optional) */
        public Integer parentCategoryId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemTypeIds -> @ItemTypeIds (optional); comma separated */
        public String itemTypeIds;
        /** warehouseIds -> @WarehouseIds (optional); comma separated */
        public String warehouseIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("documentTypeId", documentTypeId);
            args.put("itemId", itemId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("warehouseId", warehouseId);
            args.put("jobLotId", jobLotId);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("parentCategoryId", parentCategoryId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("itemTypeId", itemTypeId);
            args.put("itemTypeIds", itemTypeIds);
            args.put("warehouseIds", warehouseIds);
            return args;
        }
    }

    /** Request for /reports/print/200-items-list */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt200ItemsListRequest {
        /** itemCategory -> @ItemCategoryId (required) */
        public String itemCategory;
        /** itemTypes -> @ItemTypeId (required) */
        public String itemTypes;
        /** itemClass -> @ItemClassId (required) */
        public String itemClass;
        /** purchaseGLAccount -> @PurchaseGLAC (required) */
        public String purchaseGLAccount;
        /** saleGLAccount -> @SaleGLAC (required) */
        public String saleGLAccount;
        /** cGSGLAccount -> @COGSGLAC (required) */
        public String cGSGLAccount;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("itemCategory", itemCategory);
            args.put("itemTypes", itemTypes);
            args.put("itemClass", itemClass);
            args.put("purchaseGLAccount", purchaseGLAccount);
            args.put("saleGLAccount", saleGLAccount);
            args.put("cGSGLAccount", cGSGLAccount);
            return args;
        }
    }

    /** Request for /reports/print/255-gate-pass-general */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt255GatePassGeneralRequest {
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** reqType -> @WeighableStatus (optional) */
        public String reqType;
        /** status -> @Status (optional) */
        public String status;
        /** gpSrNoF -> @GpNoFrom (optional) */
        public String gpSrNoF;
        /** gpSrNoT -> @GpNoTo (optional) */
        public String gpSrNoT;
        /** pendingForView -> @OnlyPending (optional) */
        public String pendingForView;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("reqType", reqType);
            args.put("status", status);
            args.put("gpSrNoF", gpSrNoF);
            args.put("gpSrNoT", gpSrNoT);
            args.put("pendingForView", pendingForView);
            return args;
        }
    }

    /** Request for /reports/print/274-1-pre-bookin-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt2741PreBookinRegisterRequest {
        /** appId -> @AppId (required) */
        public Integer appId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (optional) */
        public Integer id;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** parentCategoryId -> @InventoryParentCategoriesId (optional) */
        public Integer parentCategoryId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** documentTypeIds -> @DocumentTypeIds (optional); comma separated */
        public String documentTypeIds;
        /** status -> @Status (optional) */
        public String status;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;
        /** costCenterId -> @CostCenterId (optional) */
        public Integer costCenterId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("appId", appId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("parentCategoryId", parentCategoryId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("itemTypeId", itemTypeId);
            args.put("documentTypeIds", documentTypeIds);
            args.put("status", status);
            args.put("isApproved", isApproved);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("actionId", actionId);
            args.put("costCenterId", costCenterId);
            return args;
        }
    }

    /** Request for /reports/print/292-supplier-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt292SupplierRegisterRequest {
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** countryId -> @CountryId (optional) */
        public Integer countryId;
        /** cityId -> @CityId (optional) */
        public Integer cityId;
        /** accountId -> @GlAccountId (optional) */
        public Integer accountId;
        /** partyTypeId -> @PartyTypeId (optional) */
        public Integer partyTypeId;
        /** customerGroupId -> @CustomerGroupId (optional) */
        public Integer customerGroupId;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;
        /** isTaxable -> @IsTaxable (optional) */
        public Boolean isTaxable;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("countryId", countryId);
            args.put("cityId", cityId);
            args.put("accountId", accountId);
            args.put("partyTypeId", partyTypeId);
            args.put("customerGroupId", customerGroupId);
            args.put("actionId", actionId);
            args.put("isTaxable", isTaxable);
            return args;
        }
    }

    /** Request for /reports/print/292-01-supplier-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt29201SupplierRegisterRequest {
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** countryId -> @CountryId (optional) */
        public Integer countryId;
        /** cityId -> @CityId (optional) */
        public Integer cityId;
        /** accountId -> @GlAccountId (optional) */
        public Integer accountId;
        /** partyTypeId -> @PartyTypeId (optional) */
        public Integer partyTypeId;
        /** customerGroupId -> @CustomerGroupId (optional) */
        public Integer customerGroupId;
        /** isTaxable -> @IsTaxable (optional) */
        public Boolean isTaxable;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("countryId", countryId);
            args.put("cityId", cityId);
            args.put("accountId", accountId);
            args.put("partyTypeId", partyTypeId);
            args.put("customerGroupId", customerGroupId);
            args.put("isTaxable", isTaxable);
            return args;
        }
    }

    /** Request for /reports/print/293-supplier-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt293SupplierSlipRequest {
        /** id -> @SupplierCustomerId (required) */
        public Integer id;
        /** groupAccountId -> @GroupId (optional) */
        public Integer groupAccountId;
        /** countryId -> @CountryId (optional) */
        public Integer countryId;
        /** cityId -> @CityId (optional) */
        public Integer cityId;
        /** accountId -> @GlAccountId (optional) */
        public Integer accountId;
        /** partyTypeId -> @PartyTypeId (optional) */
        public Integer partyTypeId;
        /** customerGroupId -> @CustomerGroupId (optional) */
        public Integer customerGroupId;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;
        /** isTaxable -> @IsTaxable (optional) */
        public Boolean isTaxable;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("groupAccountId", groupAccountId);
            args.put("countryId", countryId);
            args.put("cityId", cityId);
            args.put("accountId", accountId);
            args.put("partyTypeId", partyTypeId);
            args.put("customerGroupId", customerGroupId);
            args.put("actionId", actionId);
            args.put("isTaxable", isTaxable);
            return args;
        }
    }

    /** Request for /reports/print/bar-code-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptBarCodeReportRequest {
        /** ids -> @LookupTypeIds (required); comma separated */
        public String ids;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("ids", ids);
            return args;
        }
    }
}
