package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Logistics print request models. Generated by gen_print_endpoints.py. */
public final class LogisticsPrintRequests {
    private LogisticsPrintRequests() { }

    /** Request for /reports/print/1300-logistic-rate-negotiation-slip-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1300LogisticRateNegotiationSlipSlipRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1301-agreement-header-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1301AgreementHeaderSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1302-logistic-rate-negotiation-transporter-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1302LogisticRateNegotiationTransporterSlipRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1303-purchase-order-header-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1303PurchaseOrderHeaderSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1304-services-bill-header-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1304ServicesBillHeaderSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/1305-freight-voucher-outward-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1305FreightVoucherOutwardSlipRequest {
        /** id -> @Id (required) */
        public Integer id;
        /** headerId -> @MasterDocId (optional) */
        public Integer headerId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("headerId", headerId);
            return args;
        }
    }

    /** Request for /reports/print/logistic-rate-negotiation-source-document-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptLogisticRateNegotiationSourceDocumentSubReportRequest {
        /** id -> @logisticRateNegotiationHeaderId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/logistic-rate-negotiation-transporter-source-document-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptLogisticRateNegotiationTransporterSourceDocumentSubReportRequest {
        /** id -> @logisticRateNegotiationHeaderId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }
}
