package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** PackingMaterial print request models. Generated by gen_print_endpoints.py. */
public final class PackingMaterialPrintRequests {
    private PackingMaterialPrintRequests() { }

    /** Request for /reports/print/214-grn-packing-material-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt214GRNPackingMaterialSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/214-01-grn-packing-material-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt21401GrnPackingMaterialSlipRequest {
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/231-purchase-bill-packing-material-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt231PurchaseBillPackingMaterialSlipRequest {
        /** id -> @PihId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/231-01-purchase-bill-pm-slip-with-grn-detail */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt23101PurchaseBillPmSlipWithGrnDetailRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/294-sale-bill-direct-without-so */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt294SaleBillDirectWithoutSORequest {
        /** id -> @PihId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/215-export-return-grn-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt215ExportReturnGrnSlipRequest {
        /** documentTypeIds -> @DocumentTypeIds (optional); comma separated */
        public String documentTypeIds;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @DocNoFrom (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @DocNoTo (optional) */
        public Integer toDocNo;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** transporterId -> @TransporterId (optional) */
        public Integer transporterId;
        /** exImInvoiceId -> @ExImInvoiceId (optional) */
        public Integer exImInvoiceId;
        /** lcOrderId -> @LCOrderId (optional) */
        public Integer lcOrderId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** id -> @GrnId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeIds", documentTypeIds);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("transporterId", transporterId);
            args.put("exImInvoiceId", exImInvoiceId);
            args.put("lcOrderId", lcOrderId);
            args.put("itemId", itemId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/341-grn-packing-material-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt341GrnPackingMaterialRegisterRequest {
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/402-inv-stock-inventory-transactions-a */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt402InvStockInventoryTransactionsARequest {
        /** fromdate -> @DateFrom (required); yyyy-MM-dd */
        public String fromdate;
        /** todate -> @DateTo (required); yyyy-MM-dd */
        public String todate;
        /** uom -> @PackUom (required) */
        public String uom;
        /** packingType -> @PackingTypeId (required) */
        public String packingType;
        /** itemClaas -> @ItemClassGroupId (required) */
        public String itemClaas;
        /** category -> @ItemCategoryId (required) */
        public String category;
        /** itemtype -> @ItemTypeId (required) */
        public String itemtype;
        /** parentCategory -> @InventoryParentCategoriesId (required) */
        public String parentCategory;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromdate", fromdate);
            args.put("todate", todate);
            args.put("uom", uom);
            args.put("packingType", packingType);
            args.put("itemClaas", itemClaas);
            args.put("category", category);
            args.put("itemtype", itemtype);
            args.put("parentCategory", parentCategory);
            return args;
        }
    }

    /** Request for /reports/print/357-purchase-order-register-pm */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt357PurchaseOrderRegisterPMRequest {
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** orderId -> @OrderId (optional) */
        public Integer orderId;
        /** fromDate -> @StartOrderDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @EndOrderDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @PoSrFrom (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @PoSrTo (optional) */
        public Integer toDocNo;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** status -> @Status (optional) */
        public String status;
        /** actionTypeId -> @PostState (optional) */
        public Integer actionTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("orderId", orderId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("isApproved", isApproved);
            args.put("status", status);
            args.put("actionTypeId", actionTypeId);
            return args;
        }
    }

    /** Request for /reports/print/357-01-purchase-order-register-pm */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt35701PurchaseOrderRegisterPMRequest {
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** orderId -> @OrderId (optional) */
        public Integer orderId;
        /** fromDate -> @StartOrderDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @EndOrderDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @PoSrFrom (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @PoSrTo (optional) */
        public Integer toDocNo;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** status -> @Status (optional) */
        public String status;
        /** actionTypeId -> @PostState (optional) */
        public Integer actionTypeId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("orderId", orderId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("isApproved", isApproved);
            args.put("status", status);
            args.put("actionTypeId", actionTypeId);
            return args;
        }
    }

    /** Request for /reports/print/215-purchase-order-packing-material-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt215PurchaseOrderPackingMaterialSlipRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @OrderId (required) */
        public Integer id;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** status -> @Status (optional) */
        public String status;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("status", status);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/215-stock-adjustment-pm-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt215StockAdjustmentPMSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** actionId -> @AdjustmentTypeId (optional) */
        public Integer actionId;
        /** cropYearId -> @CropYearId (optional) */
        public Integer cropYearId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("id", id);
            args.put("itemId", itemId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("actionId", actionId);
            args.put("cropYearId", cropYearId);
            return args;
        }
    }

    /** Request for /reports/print/415-inv-stock-transfer-packing-material-and-store-slipand-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt415InvStockTransferPackingMaterialAndStoreSlipandRegisterRequest {
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromWarehouseId -> @FromWarehouseId (optional) */
        public Integer fromWarehouseId;
        /** toWarehouseId -> @ToWarehouseId (optional) */
        public Integer toWarehouseId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("itemId", itemId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromWarehouseId", fromWarehouseId);
            args.put("toWarehouseId", toWarehouseId);
            return args;
        }
    }

    /** Request for /reports/print/419-party-to-party-packing-material-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt419PartyToPartyPackingMaterialSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/665-inv-stock-conversion-packing-material-summery */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt665InvStockConversionPackingMaterialSummeryRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/671-01-packing-material-requirement-planning-detail */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt67101PackingMaterialRequirementPlanningDetailRequest {
        /** fromDate -> @LoadingDate (required); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @LoadingToDate (required); yyyy-MM-dd */
        public String toDate;
        /** skipZero -> @OnlyRequired (optional) */
        public String skipZero;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** activity -> @Activity (optional) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("skipZero", skipZero);
            args.put("itemId", itemId);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/671-packing-material-requirement-planning */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt671PackingMaterialRequirementPlanningRequest {
        /** fromDate -> @LoadingDate (required); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @LoadingToDate (required); yyyy-MM-dd */
        public String toDate;
        /** skipZero -> @OnlyRequired (optional) */
        public String skipZero;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** activity -> @Activity (optional) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("skipZero", skipZero);
            args.put("itemId", itemId);
            args.put("activity", activity);
            return args;
        }
    }
}
