package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Pos print request models. Generated by gen_print_endpoints.py. */
public final class PosPrintRequests {
    private PosPrintRequests() { }

    /** Request for /reports/print/324-sales-item-pricing-list */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt324SalesItemPricingListRequest {
        /** effectedDate -> @EffectedDate (required); yyyy-MM-dd */
        public String effectedDate;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** cropYearId -> @CropYearId (optional) */
        public Integer cropYearId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("effectedDate", effectedDate);
            args.put("itemId", itemId);
            args.put("cropYearId", cropYearId);
            return args;
        }
    }

    /** Request for /reports/print/324a-sales-pricing-list */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt324ASalesPricingListRequest {
        /** id -> @PriceTypeId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/325-item-pricing-list */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt325ItemPricingListRequest {
        /** parentCategoryId -> @InventoryParentCategoriesId (optional) */
        public Integer parentCategoryId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** cropYearId -> @CropYearId (optional) */
        public Integer cropYearId;
        /** ids -> @Ids (optional); comma separated */
        public String ids;
        /** isApproved -> @IsActive (optional) */
        public Boolean isApproved;
        /** effectedDate -> @EffectiveDate (optional); yyyy-MM-dd */
        public String effectedDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("parentCategoryId", parentCategoryId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("itemTypeId", itemTypeId);
            args.put("itemId", itemId);
            args.put("cropYearId", cropYearId);
            args.put("ids", ids);
            args.put("isApproved", isApproved);
            args.put("effectedDate", effectedDate);
            return args;
        }
    }

    /** Request for /reports/print/325-01-item-pricing-list */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt32501ItemPricingListRequest {
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** effectedDate -> @EffectedDate (optional); yyyy-MM-dd */
        public String effectedDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("itemCategoryId", itemCategoryId);
            args.put("itemTypeId", itemTypeId);
            args.put("effectedDate", effectedDate);
            return args;
        }
    }
}
