package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Production print request models. Generated by gen_print_endpoints.py. */
public final class ProductionPrintRequests {
    private ProductionPrintRequests() { }

    /** Request for /reports/print/666-daily-plant-consumed-hours-form-history-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt666DailyPlantConsumedHoursFormHistoryReportRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** entryDateFrom -> @EntryFromDate (optional); yyyy-MM-dd */
        public String entryDateFrom;
        /** entryDateTo -> @EntryToDate (optional); yyyy-MM-dd */
        public String entryDateTo;
        /** modifyDateFrom -> @ModifyFromDate (optional); yyyy-MM-dd */
        public String modifyDateFrom;
        /** modifyDateTo -> @ModifyToDate (optional); yyyy-MM-dd */
        public String modifyDateTo;
        /** jobOrderId -> @JobOrderId (optional) */
        public Integer jobOrderId;
        /** id -> @Id (optional) */
        public Integer id;
        /** reasonId -> @ReasonId (optional) */
        public Integer reasonId;
        /** monthDate -> @MonthDate (optional); yyyy-MM-dd */
        public String monthDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("entryDateFrom", entryDateFrom);
            args.put("entryDateTo", entryDateTo);
            args.put("modifyDateFrom", modifyDateFrom);
            args.put("modifyDateTo", modifyDateTo);
            args.put("jobOrderId", jobOrderId);
            args.put("id", id);
            args.put("reasonId", reasonId);
            args.put("monthDate", monthDate);
            return args;
        }
    }

    /** Request for /reports/print/627-production-output-allocation-with-export-invoice */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt627ProductionOutputAllocationWithExportInvoiceRequest {
        /** jobOrderId -> @JobOrderId (optional) */
        public Integer jobOrderId;
        /** invoiceId -> @ExImInvoiceId (optional) */
        public Integer invoiceId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("invoiceId", invoiceId);
            return args;
        }
    }

    /** Request for /reports/print/601-inv-food-production-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt601InvFoodProductionSlipRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** jobOrderFrom -> @JobOrderFrom (optional); yyyy-MM-dd */
        public String jobOrderFrom;
        /** jobOrderTo -> @JobOrderTo (optional); yyyy-MM-dd */
        public String jobOrderTo;
        /** jobOrderId -> @JobOrderId (optional) */
        public Integer jobOrderId;
        /** reqType -> @EntryType (required) */
        public String reqType;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("warehouseId", warehouseId);
            args.put("jobOrderFrom", jobOrderFrom);
            args.put("jobOrderTo", jobOrderTo);
            args.put("jobOrderId", jobOrderId);
            args.put("reqType", reqType);
            return args;
        }
    }

    /** Request for /reports/print/606-inv-food-production-packing-and-over-head-report-by-job-order */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt606InvFoodProductionPackingAndOverHeadReportByJobOrderRequest {
        /** reportType -> @ReportType (required) */
        public String reportType;
        /** jobOrderId -> @JobOrderId (optional) */
        public Integer jobOrderId;
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("reportType", reportType);
            args.put("jobOrderId", jobOrderId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/602a-production-summery-with-values */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt602AProductionSummeryWithValuesRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;
        /** plantId -> @PlantId (optional) */
        public Integer plantId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("plantId", plantId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("branchesIds", branchesIds);
            args.put("actionId", actionId);
            return args;
        }
    }

    /** Request for /reports/print/613-production-summery-with-exp-values */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt613ProductionSummeryWithExpValuesRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("actionId", actionId);
            return args;
        }
    }

    /** Request for /reports/print/615-production-summery */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt615ProductionSummeryRequest {
        /** id -> @JobOrderId (required) */
        public Integer id;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("actionId", actionId);
            return args;
        }
    }

    /** Request for /reports/print/623-inv-food-production-consumption-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt623InvFoodProductionConsumptionReportRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** jobOrderFrom -> @JobOrderFrom (optional); yyyy-MM-dd */
        public String jobOrderFrom;
        /** jobOrderTo -> @JobOrderTo (optional); yyyy-MM-dd */
        public String jobOrderTo;
        /** jobOrderId -> @JobOrderId (optional) */
        public Integer jobOrderId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("warehouseId", warehouseId);
            args.put("jobOrderFrom", jobOrderFrom);
            args.put("jobOrderTo", jobOrderTo);
            args.put("jobOrderId", jobOrderId);
            return args;
        }
    }

    /** Request for /reports/print/620-production-job-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt620ProductionJobOrderSlipRequest {
        /** id -> @hId (optional) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/605-stock-conversion-summary-new */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt605StockConversionSummaryNewRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/812-production-kam-pack-material-consumption */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt812ProductionKamPackMaterialConsumptionRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** pmItemId -> @PmItemId (optional) */
        public Integer pmItemId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("pmItemId", pmItemId);
            args.put("itemId", itemId);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/604-food-production-comparison */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt604FoodProductionComparisonRequest {
        /** reportType -> @ProductionType (required) */
        public String reportType;
        /** fromDocNo -> @DocNoFrom (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @DocNoTo (optional) */
        public Integer toDocNo;
        /** itemId -> @PlantId (optional) */
        public Integer itemId;
        /** jobOrderId -> @JobOrderId (optional) */
        public Integer jobOrderId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("reportType", reportType);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("itemId", itemId);
            args.put("jobOrderId", jobOrderId);
            return args;
        }
    }

    /** Request for /reports/print/625-food-production-doc-wise-summery-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt625FoodProductionDocWiseSummeryReportRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;
        /** plantId -> @PlantId (optional) */
        public Integer plantId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("plantId", plantId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/164-wages-summary-by-contractor-and-job-order */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt164WagesSummaryByContractorAndJobOrderRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** accountId -> @WagesAccountId (optional) */
        public Integer accountId;
        /** contractorId -> @ContractorId (optional) */
        public Integer contractorId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** documentTypeId -> @ReferenceDocumentTypeId (optional) */
        public Integer documentTypeId;
        /** debitAccountId -> @DebitAccountId (optional) */
        public Integer debitAccountId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;
        /** stockPartyId -> @StockPartyId (optional) */
        public Integer stockPartyId;
        /** jobOrderId -> @JobOrderId (optional) */
        public Integer jobOrderId;
        /** refDocumentTypeIds -> @ReferenceDocumentTypeIds (optional); comma separated */
        public String refDocumentTypeIds;
        /** isApproved -> @FreeOfCost (optional) */
        public Boolean isApproved;
        /** reportType -> @ActivityName (optional) */
        public String reportType;
        /** skipZero -> @BranchWise (optional) */
        public String skipZero;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("accountId", accountId);
            args.put("contractorId", contractorId);
            args.put("itemId", itemId);
            args.put("documentTypeId", documentTypeId);
            args.put("debitAccountId", debitAccountId);
            args.put("branchesIds", branchesIds);
            args.put("actionId", actionId);
            args.put("stockPartyId", stockPartyId);
            args.put("jobOrderId", jobOrderId);
            args.put("refDocumentTypeIds", refDocumentTypeIds);
            args.put("isApproved", isApproved);
            args.put("reportType", reportType);
            args.put("skipZero", skipZero);
            return args;
        }
    }

    /** Request for /reports/print/461-boiler-consumption-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt461BoilerConsumptionSlipRequest {
        /** financialYearId -> @FinancialYearId (optional) */
        public Integer financialYearId;
        /** id -> @Id (required) */
        public Integer id;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("financialYearId", financialYearId);
            args.put("id", id);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            return args;
        }
    }

    /** Request for /reports/print/553-production-register-with-activity */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt553ProductionRegisterWithActivityRequest {
        /** jobOrderId -> @InvJobOrderId (optional) */
        public Integer jobOrderId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** entryDateFrom -> @EntryFromDate (optional); yyyy-MM-dd */
        public String entryDateFrom;
        /** entryDateTo -> @EntryToDate (optional); yyyy-MM-dd */
        public String entryDateTo;
        /** plantId -> @PlantId (optional) */
        public Integer plantId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockAccountId -> @ItemStockAccountId (optional) */
        public Integer stockAccountId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** parentCategoryId -> @ParentCategoriesId (optional) */
        public Integer parentCategoryId;
        /** accountId -> @WipAccountId (optional) */
        public Integer accountId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("entryDateFrom", entryDateFrom);
            args.put("entryDateTo", entryDateTo);
            args.put("plantId", plantId);
            args.put("itemId", itemId);
            args.put("stockAccountId", stockAccountId);
            args.put("warehouseId", warehouseId);
            args.put("parentCategoryId", parentCategoryId);
            args.put("accountId", accountId);
            args.put("branchesIds", branchesIds);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/554-production-register-with-activity-out-put-by-packing-material */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt554ProductionRegisterWithActivityOutPutByPackingMaterialRequest {
        /** jobOrderId -> @InvJobOrderId (optional) */
        public Integer jobOrderId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** entryDateFrom -> @EntryFromDate (optional); yyyy-MM-dd */
        public String entryDateFrom;
        /** entryDateTo -> @EntryToDate (optional); yyyy-MM-dd */
        public String entryDateTo;
        /** plantId -> @PlantId (optional) */
        public Integer plantId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockAccountId -> @ItemStockAccountId (optional) */
        public Integer stockAccountId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** parentCategoryId -> @ParentCategoriesId (optional) */
        public Integer parentCategoryId;
        /** accountId -> @WipAccountId (optional) */
        public Integer accountId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("entryDateFrom", entryDateFrom);
            args.put("entryDateTo", entryDateTo);
            args.put("plantId", plantId);
            args.put("itemId", itemId);
            args.put("stockAccountId", stockAccountId);
            args.put("warehouseId", warehouseId);
            args.put("parentCategoryId", parentCategoryId);
            args.put("accountId", accountId);
            args.put("branchesIds", branchesIds);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/562-production-register-with-activity */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt562ProductionRegisterWithActivityRequest {
        /** jobOrderId -> @InvJobOrderId (optional) */
        public Integer jobOrderId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** entryDateFrom -> @EntryFromDate (optional); yyyy-MM-dd */
        public String entryDateFrom;
        /** entryDateTo -> @EntryToDate (optional); yyyy-MM-dd */
        public String entryDateTo;
        /** plantId -> @PlantId (optional) */
        public Integer plantId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockAccountId -> @ItemStockAccountId (optional) */
        public Integer stockAccountId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** parentCategoryId -> @ParentCategoriesId (optional) */
        public Integer parentCategoryId;
        /** accountId -> @WipAccountId (optional) */
        public Integer accountId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("entryDateFrom", entryDateFrom);
            args.put("entryDateTo", entryDateTo);
            args.put("plantId", plantId);
            args.put("itemId", itemId);
            args.put("stockAccountId", stockAccountId);
            args.put("warehouseId", warehouseId);
            args.put("parentCategoryId", parentCategoryId);
            args.put("accountId", accountId);
            args.put("branchesIds", branchesIds);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/602-production-summery */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt602ProductionSummeryRequest {
        /** plantId -> @PlantId (optional) */
        public Integer plantId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("plantId", plantId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("branchesIds", branchesIds);
            args.put("actionId", actionId);
            return args;
        }
    }

    /** Request for /reports/print/602-01-production-summery-with-lab */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt60201ProductionSummeryWithLabRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;
        /** plantId -> @PlantId (optional) */
        public Integer plantId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("plantId", plantId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/603-production-pending-invoice */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt603ProductionPendingInvoiceRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WareHouseId (optional) */
        public Integer warehouseId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("documentTypeId", documentTypeId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/607-food-production-issuance-grn-wise-by-job-order-id */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt607FoodProductionIssuanceGrnWiseByJobOrderIdRequest {
        /** jobOrderId -> @InvJobOrderId (optional) */
        public Integer jobOrderId;
        /** plantId -> @PlantId (optional) */
        public Integer plantId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemUomId -> @PackUomId (optional) */
        public Integer itemUomId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("plantId", plantId);
            args.put("itemId", itemId);
            args.put("itemUomId", itemUomId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/613-01-production-befor-settlement-summery-2 */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt61301ProductionBeforSettlementSummery2Request {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("actionId", actionId);
            return args;
        }
    }

    /** Request for /reports/print/613-02-production-settlement-with-reference-document-detail-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt61302ProductionSettlementWithReferenceDocumentDetailReportRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("actionId", actionId);
            return args;
        }
    }

    /** Request for /reports/print/615-01-production-befor-settlement-summery-3 */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt61501ProductionBeforSettlementSummery3Request {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;
        /** actionId -> @ActionId (optional) */
        public Integer actionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            args.put("actionId", actionId);
            return args;
        }
    }

    /** Request for /reports/print/663-purchase-order-detail-register-rice */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt663PurchaseOrderDetailRegisterRiceRequest {
        /** actionId -> @PendingUsed (optional) */
        public Integer actionId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** packingTypeId -> @InvPackingTypeId (optional) */
        public Integer packingTypeId;
        /** cropYear -> @CropYear (optional) */
        public String cropYear;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("actionId", actionId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("jobLotId", jobLotId);
            args.put("packingTypeId", packingTypeId);
            args.put("cropYear", cropYear);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/666-01-monthly-plant-consumed-hours-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt66601MonthlyPlantConsumedHoursReportRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** entryDateFrom -> @EntryFromDate (optional); yyyy-MM-dd */
        public String entryDateFrom;
        /** entryDateTo -> @EntryToDate (optional); yyyy-MM-dd */
        public String entryDateTo;
        /** modifyDateFrom -> @ModifyFromDate (optional); yyyy-MM-dd */
        public String modifyDateFrom;
        /** modifyDateTo -> @ModifyToDate (optional); yyyy-MM-dd */
        public String modifyDateTo;
        /** jobOrderId -> @JobOrderId (optional) */
        public Integer jobOrderId;
        /** id -> @Id (optional) */
        public Integer id;
        /** reasonId -> @ReasonId (optional) */
        public Integer reasonId;
        /** monthDate -> @MonthDate (optional); yyyy-MM-dd */
        public String monthDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("entryDateFrom", entryDateFrom);
            args.put("entryDateTo", entryDateTo);
            args.put("modifyDateFrom", modifyDateFrom);
            args.put("modifyDateTo", modifyDateTo);
            args.put("jobOrderId", jobOrderId);
            args.put("id", id);
            args.put("reasonId", reasonId);
            args.put("monthDate", monthDate);
            return args;
        }
    }

    /** Request for /reports/print/672-job-order-summary-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt672JobOrderSummaryReportRequest {
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("isApproved", isApproved);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            return args;
        }
    }

    /** Request for /reports/print/921-i-01-production-costing-form-history-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt921I01ProductionCostingFormHistoryReportRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            return args;
        }
    }

    /** Request for /reports/print/922-prodcution-foh-allocate-to-job-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt922ProdcutionFohAllocateToJobOrderSlipRequest {
        /** id -> @Id (required) */
        public Integer id;
        /** plantId -> @PlantId (optional) */
        public Integer plantId;
        /** jobOrderId -> @JobOrderId (optional) */
        public Integer jobOrderId;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("plantId", plantId);
            args.put("jobOrderId", jobOrderId);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/production-job-order-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptProductionJobOrderSubReportRequest {
        /** productionJobOrderId -> @ProductionJobOrderId (required) */
        public Integer productionJobOrderId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("productionJobOrderId", productionJobOrderId);
            return args;
        }
    }

    /** Request for /reports/print/production-manual-costing-by-product-detail-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptProductionManualCostingByProductDetailSubReportRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            return args;
        }
    }

    /** Request for /reports/print/production-manual-costing-input-detail-sub-repirt */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptProductionManualCostingInputDetailSubRepirtRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            return args;
        }
    }

    /** Request for /reports/print/inv-production-job-order-slip-a */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptInvProductionJobOrderSlipARequest {

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            return args;
        }
    }

    /** Request for /reports/print/usp-inv-production-job-order-lab-standard-detail-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptUspInvProductionJobOrderLabStandardDetailSubReportRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("jobOrderId", jobOrderId);
            return args;
        }
    }
}
