package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Salt print request models. Generated by gen_print_endpoints.py. */
public final class SaltPrintRequests {
    private SaltPrintRequests() { }

    /** Request for /reports/print/1818-production-salt-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1818ProductionSaltSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** id -> @Id (required) */
        public Integer id;
        /** warehouseId -> @WareHouseId (optional) */
        public Integer warehouseId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** productionNo -> @ProductionNo (optional) */
        public String productionNo;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("id", id);
            args.put("warehouseId", warehouseId);
            args.put("jobLotId", jobLotId);
            args.put("itemId", itemId);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("productionNo", productionNo);
            return args;
        }
    }

    /** Request for /reports/print/1818-production-salt-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1818ProductionSaltRegisterRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** id -> @Id (optional) */
        public Integer id;
        /** warehouseId -> @WareHouseId (optional) */
        public Integer warehouseId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** productionNo -> @ProductionNo (optional) */
        public String productionNo;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("id", id);
            args.put("warehouseId", warehouseId);
            args.put("jobLotId", jobLotId);
            args.put("itemId", itemId);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("productionNo", productionNo);
            return args;
        }
    }
}
