package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Store print request models. Generated by gen_print_endpoints.py. */
public final class StorePrintRequests {
    private StorePrintRequests() { }

    /** Request for /reports/print/148-delivery-challan-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt148DeliveryChallanSlipRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/262-delivery-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt262DeliveryOrderSlipRequest {
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/451-department-request-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt451DepartmentRequestSlipRequest {
        /** financialYearId -> @FinancialYearId (optional) */
        public Integer financialYearId;
        /** reportId -> @Id (required) */
        public Integer reportId;
        /** refDocumentTypeId -> @DepartmentId (optional) */
        public Integer refDocumentTypeId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** assetId -> @AssetId (optional) */
        public Integer assetId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** pageSize -> @PageSize (optional) */
        public Integer pageSize;
        /** pageNumber -> @PageNumber (optional) */
        public Integer pageNumber;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("financialYearId", financialYearId);
            args.put("reportId", reportId);
            args.put("refDocumentTypeId", refDocumentTypeId);
            args.put("itemId", itemId);
            args.put("assetId", assetId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("isApproved", isApproved);
            args.put("pageSize", pageSize);
            args.put("pageNumber", pageNumber);
            args.put("itemConditionId", itemConditionId);
            return args;
        }
    }

    /** Request for /reports/print/1615-department-request-to-consumable-store-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1615DepartmentRequestToConsumableStoreSlipRequest {
        /** financialYearId -> @FinancialYearId (optional) */
        public Integer financialYearId;
        /** id -> @Id (required) */
        public Integer id;
        /** refDocumentTypeId -> @DepartmentId (optional) */
        public Integer refDocumentTypeId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** assetId -> @AssetId (optional) */
        public Integer assetId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** pageSize -> @PageSize (optional) */
        public Integer pageSize;
        /** pageNumber -> @PageNumber (optional) */
        public Integer pageNumber;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("financialYearId", financialYearId);
            args.put("id", id);
            args.put("refDocumentTypeId", refDocumentTypeId);
            args.put("itemId", itemId);
            args.put("assetId", assetId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("isApproved", isApproved);
            args.put("pageSize", pageSize);
            args.put("pageNumber", pageNumber);
            args.put("itemConditionId", itemConditionId);
            return args;
        }
    }

    /** Request for /reports/print/212-goods-receipts-notes-store-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt212GoodsReceiptsNotesStoreSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/336-grn-store-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt336GrnStoreRegisterRequest {
        /** documentTypeIds -> @DocumentTypeId (optional); comma separated */
        public String documentTypeIds;
        /** baseDocumentTypeId -> @BaseDocumentTypeId (optional) */
        public Integer baseDocumentTypeId;
        /** refDocumentTypeIds -> @BaseDocumentTypeIds (optional); comma separated */
        public String refDocumentTypeIds;
        /** id -> @grnId (optional) */
        public Integer id;
        /** fromDate -> @GrnDateF (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @GrnDateT (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** fromDocNo -> @GrnNoF (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @GrnNoT (optional) */
        public Integer toDocNo;
        /** gpSrNoF -> @GpSrNoF (optional) */
        public String gpSrNoF;
        /** gpSrNoT -> @GpSrNoT (optional) */
        public String gpSrNoT;
        /** orderNoFrom -> @PoNoFrom (optional); yyyy-MM-dd */
        public String orderNoFrom;
        /** orderNoTo -> @PoNoTo (optional); yyyy-MM-dd */
        public String orderNoTo;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** transporterId -> @TransporterId (optional) */
        public Integer transporterId;
        /** areaCity -> @AreaCity (optional) */
        public String areaCity;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** pendingForView -> @OnlyPending (optional) */
        public String pendingForView;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeIds", documentTypeIds);
            args.put("baseDocumentTypeId", baseDocumentTypeId);
            args.put("refDocumentTypeIds", refDocumentTypeIds);
            args.put("id", id);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("gpSrNoF", gpSrNoF);
            args.put("gpSrNoT", gpSrNoT);
            args.put("orderNoFrom", orderNoFrom);
            args.put("orderNoTo", orderNoTo);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("transporterId", transporterId);
            args.put("areaCity", areaCity);
            args.put("branchesIds", branchesIds);
            args.put("pendingForView", pendingForView);
            return args;
        }
    }

    /** Request for /reports/print/454-inv-purchase-deman-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt454InvPurchaseDemanSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/145a-purchase-invoice-return-store-party-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt145APurchaseInvoiceReturnStorePartySlipRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** id -> @Id (optional) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/145-purchase-invoice-return-store-item-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt145PurchaseInvoiceReturnStoreItemSlipRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** id -> @Id (optional) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/147-purchase-pre-bill-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt147PurchasePreBillSlipRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/409-inv-stock-adjustment-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt409InvStockAdjustmentSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** actionId -> @AdjustmentTypeId (optional) */
        public Integer actionId;
        /** cropYearId -> @CropYearId (optional) */
        public Integer cropYearId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("id", id);
            args.put("itemId", itemId);
            args.put("jobLotId", jobLotId);
            args.put("warehouseId", warehouseId);
            args.put("actionId", actionId);
            args.put("cropYearId", cropYearId);
            return args;
        }
    }

    /** Request for /reports/print/406-inv-stock-transfer-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt406InvStockTransferSlipRequest {
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromWarehouseId -> @FromWarehouseId (optional) */
        public Integer fromWarehouseId;
        /** toWarehouseId -> @ToWarehouseId (optional) */
        public Integer toWarehouseId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** toJobLotId -> @ToJobLotId (optional) */
        public Integer toJobLotId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("itemId", itemId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromWarehouseId", fromWarehouseId);
            args.put("toWarehouseId", toWarehouseId);
            args.put("jobLotId", jobLotId);
            args.put("toJobLotId", toJobLotId);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/407-inv-stock-transfer-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt407InvStockTransferSlipRequest {
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromWarehouseId -> @FromWarehouseId (optional) */
        public Integer fromWarehouseId;
        /** toWarehouseId -> @ToWarehouseId (optional) */
        public Integer toWarehouseId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** toJobLotId -> @ToJobLotId (optional) */
        public Integer toJobLotId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("itemId", itemId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromWarehouseId", fromWarehouseId);
            args.put("toWarehouseId", toWarehouseId);
            args.put("jobLotId", jobLotId);
            args.put("toJobLotId", toJobLotId);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/452-inv-gs-store-issuance-header-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt452InvGsStoreIssuanceHeaderSlipRequest {
        /** financialYearId -> @FinancialYearId (optional) */
        public Integer financialYearId;
        /** id -> @Id (required) */
        public Integer id;
        /** refDocumentTypeId -> @DepartmentId (optional) */
        public Integer refDocumentTypeId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** assetId -> @AssetId (optional) */
        public Integer assetId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** warehouseId -> @WareHouseId (optional) */
        public Integer warehouseId;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** accountId -> @AccountId (optional) */
        public Integer accountId;
        /** invoiceId -> @InvoiceId (optional) */
        public Integer invoiceId;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;
        /** ids -> @Ids (optional); comma separated */
        public String ids;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("financialYearId", financialYearId);
            args.put("id", id);
            args.put("refDocumentTypeId", refDocumentTypeId);
            args.put("itemId", itemId);
            args.put("assetId", assetId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("warehouseId", warehouseId);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("accountId", accountId);
            args.put("invoiceId", invoiceId);
            args.put("itemConditionId", itemConditionId);
            args.put("ids", ids);
            return args;
        }
    }

    /** Request for /reports/print/1616-store-issuance-to-consumable-store-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1616StoreIssuanceToConsumableStoreSlipRequest {
        /** financialYearId -> @FinancialYearId (optional) */
        public Integer financialYearId;
        /** id -> @Id (required) */
        public Integer id;
        /** refDocumentTypeId -> @DepartmentId (optional) */
        public Integer refDocumentTypeId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** assetId -> @AssetId (optional) */
        public Integer assetId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** warehouseId -> @WareHouseId (optional) */
        public Integer warehouseId;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** accountId -> @AccountId (optional) */
        public Integer accountId;
        /** invoiceId -> @InvoiceId (optional) */
        public Integer invoiceId;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;
        /** ids -> @Ids (optional); comma separated */
        public String ids;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("financialYearId", financialYearId);
            args.put("id", id);
            args.put("refDocumentTypeId", refDocumentTypeId);
            args.put("itemId", itemId);
            args.put("assetId", assetId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("warehouseId", warehouseId);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("accountId", accountId);
            args.put("invoiceId", invoiceId);
            args.put("itemConditionId", itemConditionId);
            args.put("ids", ids);
            return args;
        }
    }

    /** Request for /reports/print/457-store-issuance-return-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt457StoreIssuanceReturnSlipRequest {
        /** frm -> @Id (required) */
        public String frm;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** assetId -> @AssetId (optional) */
        public Integer assetId;
        /** warehouseId -> @WareHouseId (optional) */
        public Integer warehouseId;
        /** refDocumentTypeId -> @DepartmentId (optional) */
        public Integer refDocumentTypeId;
        /** accountId -> @AccountId (optional) */
        public Integer accountId;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("frm", frm);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("itemId", itemId);
            args.put("assetId", assetId);
            args.put("warehouseId", warehouseId);
            args.put("refDocumentTypeId", refDocumentTypeId);
            args.put("accountId", accountId);
            args.put("itemConditionId", itemConditionId);
            return args;
        }
    }

    /** Request for /reports/print/458-store-purchase-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt458StorePurchaseRegisterRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** id -> @Id (optional) */
        public Integer id;
        /** projectsId -> @ProjectId (optional) */
        public Integer projectsId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** fromDocNo -> @GrnNoFrom (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @GrnNoTo (optional) */
        public Integer toDocNo;
        /** gpSrNoF -> @GpSrNoFrom (optional) */
        public String gpSrNoF;
        /** gpSrNoT -> @GpSrNoTo (optional) */
        public String gpSrNoT;
        /** orderNoFrom -> @PoNoFrom (optional); yyyy-MM-dd */
        public String orderNoFrom;
        /** orderNoTo -> @PoNoTo (optional); yyyy-MM-dd */
        public String orderNoTo;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("id", id);
            args.put("projectsId", projectsId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemId", itemId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("gpSrNoF", gpSrNoF);
            args.put("gpSrNoT", gpSrNoT);
            args.put("orderNoFrom", orderNoFrom);
            args.put("orderNoTo", orderNoTo);
            args.put("warehouseId", warehouseId);
            return args;
        }
    }

    /** Request for /reports/print/144-inv-gdn-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt144InvGdnSlipRequest {
        /** fromDate -> @GrnDateF (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @GrnDateT (optional); yyyy-MM-dd */
        public String toDate;
        /** id -> @gdnId (required) */
        public Integer id;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** fromDocNo -> @GpSrNoF (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @GpSrNoT (optional) */
        public Integer toDocNo;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("id", id);
            args.put("documentTypeId", documentTypeId);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("supplierCustomerId", supplierCustomerId);
            return args;
        }
    }

    /** Request for /reports/print/149-inv-gdn-store-pm-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt149InvGdnStorePmSlipRequest {
        /** fromDate -> @GrnDateF (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @GrnDateT (optional); yyyy-MM-dd */
        public String toDate;
        /** id -> @gdnId (required) */
        public Integer id;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** fromDocNo -> @GpSrNoF (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @GpSrNoT (optional) */
        public Integer toDocNo;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("id", id);
            args.put("documentTypeId", documentTypeId);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("supplierCustomerId", supplierCustomerId);
            return args;
        }
    }

    /** Request for /reports/print/201-purchase-order-general-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt201PurchaseOrderGeneralSlipRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @OrderId (required) */
        public Integer id;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** status -> @Status (optional) */
        public String status;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("status", status);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/202-01-itemand-warehouse-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt20201ItemandWarehouseStockSummaryRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** rateUOM -> @IsPackTypeOn (optional) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** stockPartyId -> @StockPartyId (optional) */
        public Integer stockPartyId;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** storeRackId -> @RackId (optional) */
        public Integer storeRackId;
        /** activity -> @Activity (required) */
        public String activity;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("stockUOM", stockUOM);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("rateUOM", rateUOM);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            args.put("actionId", actionId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("stockPartyId", stockPartyId);
            args.put("itemConditionId", itemConditionId);
            args.put("branchesIds", branchesIds);
            args.put("storeRackId", storeRackId);
            args.put("activity", activity);
            return args;
        }
    }

    /** Request for /reports/print/212-01-goods-receipts-notes-empty-bags-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt21201GoodsReceiptsNotesEmptyBagsSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/239-sale-invoice-store-bill-with-tax */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt239SaleInvoiceStoreBillWithTaxRequest {
        /** id -> @PihId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/401-stock-evalaution-detail-generate-stocks-register-store */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt401StockEvalautionDetailGenerateStocksRegisterStoreRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** parentCategoryId -> @ParentCategoryId (optional) */
        public Integer parentCategoryId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;
        /** storeRackId -> @RackId (optional) */
        public Integer storeRackId;
        /** reportType -> @ReportType (optional) */
        public String reportType;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("parentCategoryId", parentCategoryId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("itemConditionId", itemConditionId);
            args.put("storeRackId", storeRackId);
            args.put("reportType", reportType);
            return args;
        }
    }

    /** Request for /reports/print/402-inv-stock-inventory-transactions-a-store */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt402InvStockInventoryTransactionsAStoreRequest {
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;
        /** storeRackId -> @RackId (optional) */
        public Integer storeRackId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("warehouseId", warehouseId);
            args.put("documentTypeId", documentTypeId);
            args.put("itemTypeId", itemTypeId);
            args.put("itemConditionId", itemConditionId);
            args.put("storeRackId", storeRackId);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/403-inv-stock-inventory-transactions-stocks-store */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt403InvStockInventoryTransactionsStocksStoreRequest {
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;
        /** storeRackId -> @RackId (optional) */
        public Integer storeRackId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("itemId", itemId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("warehouseId", warehouseId);
            args.put("documentTypeId", documentTypeId);
            args.put("itemTypeId", itemTypeId);
            args.put("itemConditionId", itemConditionId);
            args.put("storeRackId", storeRackId);
            args.put("branchesIds", branchesIds);
            return args;
        }
    }

    /** Request for /reports/print/422-01-stock-report-without-value-document-wise-store */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt42201StockReportWithoutValueDocumentWiseStoreRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional); comma separated */
        public String ids;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("branchesIds", branchesIds);
            args.put("itemId", itemId);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("ids", ids);
            return args;
        }
    }

    /** Request for /reports/print/422-inventory-evaluation-ledger-store */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt422InventoryEvaluationLedgerStoreRequest {
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** warehouseId -> @WarehouseId (optional) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** purchaseGLAC -> @ItemStockAc (optional) */
        public String purchaseGLAC;
        /** itemClassGroupId -> @ItemClassGroupId (optional) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** stockUOM -> @SaleValue (optional) */
        public String stockUOM;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** ids -> @Ids (optional); comma separated */
        public String ids;
        /** storeRackId -> @RackId (optional) */
        public Integer storeRackId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("itemTypeId", itemTypeId);
            args.put("itemCategoryId", itemCategoryId);
            args.put("warehouseId", warehouseId);
            args.put("itemId", itemId);
            args.put("purchaseGLAC", purchaseGLAC);
            args.put("itemClassGroupId", itemClassGroupId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("stockUOM", stockUOM);
            args.put("documentTypeId", documentTypeId);
            args.put("itemConditionId", itemConditionId);
            args.put("branchesIds", branchesIds);
            args.put("ids", ids);
            args.put("storeRackId", storeRackId);
            return args;
        }
    }

    /** Request for /reports/print/450-department-request-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt450DepartmentRequestRegisterRequest {
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** id -> @Id (optional) */
        public Integer id;
        /** refDocumentTypeId -> @DepartmentId (optional) */
        public Integer refDocumentTypeId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** assetId -> @AssetId (optional) */
        public Integer assetId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;
        /** pageSize -> @PageSize (optional) */
        public Integer pageSize;
        /** pageNumber -> @PageNumber (optional) */
        public Integer pageNumber;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("documentTypeId", documentTypeId);
            args.put("id", id);
            args.put("refDocumentTypeId", refDocumentTypeId);
            args.put("itemId", itemId);
            args.put("assetId", assetId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("isApproved", isApproved);
            args.put("pageSize", pageSize);
            args.put("pageNumber", pageNumber);
            args.put("itemConditionId", itemConditionId);
            return args;
        }
    }

    /** Request for /reports/print/456-purchase-demand-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt456PurchaseDemandRegisterRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @DocNoFrom (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @DocNoTo (optional) */
        public Integer toDocNo;
        /** parentCategoryId -> @ParentCategoryId (optional) */
        public Integer parentCategoryId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional) */
        public String inventoryParentCategories;
        /** itemCategoryId -> @ItemCategoryId (optional) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional) */
        public Integer itemTypeId;
        /** jobLotId -> @JobLotId (optional) */
        public Integer jobLotId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** departmentId -> @DepartmentId (optional) */
        public Integer departmentId;
        /** assetId -> @FixedAssetsRegisterId (optional) */
        public Integer assetId;
        /** status -> @Status (optional) */
        public String status;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("parentCategoryId", parentCategoryId);
            args.put("inventoryParentCategories", inventoryParentCategories);
            args.put("itemCategoryId", itemCategoryId);
            args.put("itemTypeId", itemTypeId);
            args.put("jobLotId", jobLotId);
            args.put("itemId", itemId);
            args.put("departmentId", departmentId);
            args.put("assetId", assetId);
            args.put("status", status);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/465-store-send-receipt-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt465StoreSendReceiptSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/475-inv-gs-store-issuance-header-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt475InvGsStoreIssuanceHeaderSlipRequest {
        /** financialYearId -> @FinancialYearId (optional) */
        public Integer financialYearId;
        /** id -> @Id (required) */
        public Integer id;
        /** refDocumentTypeId -> @DepartmentId (optional) */
        public Integer refDocumentTypeId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** assetId -> @AssetId (optional) */
        public Integer assetId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** warehouseId -> @WareHouseId (optional) */
        public Integer warehouseId;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** accountId -> @AccountId (optional) */
        public Integer accountId;
        /** invoiceId -> @InvoiceId (required) */
        public Integer invoiceId;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;
        /** ids -> @Ids (optional); comma separated */
        public String ids;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("financialYearId", financialYearId);
            args.put("id", id);
            args.put("refDocumentTypeId", refDocumentTypeId);
            args.put("itemId", itemId);
            args.put("assetId", assetId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("warehouseId", warehouseId);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("accountId", accountId);
            args.put("invoiceId", invoiceId);
            args.put("itemConditionId", itemConditionId);
            args.put("ids", ids);
            return args;
        }
    }

    /** Request for /reports/print/90-sale-order-store-and-pm-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt90SaleOrderStoreAndPmSlipRequest {
        /** branchesId -> @BranchesId (optional) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** id -> @OrderId (required) */
        public Integer id;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** documentTypeId -> @DocumentTypeId (required) */
        public Integer documentTypeId;
        /** status -> @OrderStatus (optional) */
        public String status;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** isApproved -> @IsApproved (optional) */
        public Boolean isApproved;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("projectsId", projectsId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("id", id);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("documentTypeId", documentTypeId);
            args.put("status", status);
            args.put("itemId", itemId);
            args.put("isApproved", isApproved);
            return args;
        }
    }

    /** Request for /reports/print/delivery-challan-header-expense-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptDeliveryChallanHeaderExpenseSubReportRequest {
        /** id -> @DeliveryChallanHeaderId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/purchase-pre-bill-header-expense-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptPurchasePreBillHeaderExpenseSubReportRequest {
        /** id -> @PurchasePreBillHeaderId (required) */
        public Integer id;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            return args;
        }
    }

    /** Request for /reports/print/store-issuance-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptStoreIssuanceSubReportRequest {
        /** id -> @Id (optional) */
        public Integer id;
        /** refDocumentTypeId -> @DepartmentId (optional) */
        public Integer refDocumentTypeId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** assetId -> @AssetId (optional) */
        public Integer assetId;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** warehouseId -> @WareHouseId (optional) */
        public Integer warehouseId;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** accountId -> @AccountId (optional) */
        public Integer accountId;
        /** invoiceId -> @InvoiceId (optional) */
        public Integer invoiceId;
        /** itemConditionId -> @ItemConditionId (optional) */
        public Integer itemConditionId;
        /** ids -> @Ids (optional); comma separated */
        public String ids;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("id", id);
            args.put("refDocumentTypeId", refDocumentTypeId);
            args.put("itemId", itemId);
            args.put("assetId", assetId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("warehouseId", warehouseId);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("accountId", accountId);
            args.put("invoiceId", invoiceId);
            args.put("itemConditionId", itemConditionId);
            args.put("ids", ids);
            return args;
        }
    }
}
