package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Tax print request models. Generated by gen_print_endpoints.py. */
public final class TaxPrintRequests {
    private TaxPrintRequests() { }

    /** Request for /reports/print/389-get-pre-invoices-and-forwarding-date-for-commercial-invoices */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt389GetPreInvoicesAndForwardingDateForCommercialInvoicesRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** exImLcOrderId -> @ContractId (optional) */
        public Integer exImLcOrderId;
        /** ids -> @Ids (optional); comma separated */
        public String ids;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** fcyId -> @FcurrencyId (optional) */
        public Integer fcyId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** packingExpiryDate -> @PackingExpiryDate (optional); yyyy-MM-dd */
        public String packingExpiryDate;
        /** productionNo -> @ProductionNo (optional) */
        public String productionNo;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("exImLcOrderId", exImLcOrderId);
            args.put("ids", ids);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("fcyId", fcyId);
            args.put("itemId", itemId);
            args.put("packingExpiryDate", packingExpiryDate);
            args.put("productionNo", productionNo);
            args.put("zeroBalanceType", zeroBalanceType);
            return args;
        }
    }

    /** Request for /reports/print/546-get-proforma-data-for-invoices */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt546GetProformaDataForInvoicesRequest {
        /** branchesId -> @BranchesId (required) */
        public Integer branchesId;
        /** documentTypeIds -> @DocumentTypeIds (required); comma separated */
        public String documentTypeIds;
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** ids -> @Ids (optional); comma separated */
        public String ids;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** fcyId -> @FcurrencyId (optional) */
        public Integer fcyId;
        /** itemId -> @ItemId (optional) */
        public Integer itemId;
        /** zeroBalanceType -> @SkipZero (optional) */
        public String zeroBalanceType;
        /** contractScheduleIds -> @ScheduleIds (optional); comma separated */
        public String contractScheduleIds;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("documentTypeIds", documentTypeIds);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("ids", ids);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("fcyId", fcyId);
            args.put("itemId", itemId);
            args.put("zeroBalanceType", zeroBalanceType);
            args.put("contractScheduleIds", contractScheduleIds);
            return args;
        }
    }

    /** Request for /reports/print/568-commission-agent-fcy-ledger */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt568CommissionAgentFcyLedgerRequest {
        /** fromDate -> @FromDate (required); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (required); yyyy-MM-dd */
        public String toDate;
        /** commissionAgentId -> @CommissionAgentId (optional) */
        public Integer commissionAgentId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("commissionAgentId", commissionAgentId);
            return args;
        }
    }

    /** Request for /reports/print/569-commercial-invoice-shipments */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt569CommercialInvoiceShipmentsRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("supplierCustomerId", supplierCustomerId);
            return args;
        }
    }

    /** Request for /reports/print/570-shipmentdata-for-brokery-tax */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt570ShipmentdataForBrokeryTaxRequest {
        /** fromDate -> @FromDate (required); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (required); yyyy-MM-dd */
        public String toDate;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            return args;
        }
    }

    /** Request for /reports/print/618-01-do-weight-wb-weight-diff */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt61801DoWeightWbWeightDiffRequest {
        /** eximInvoiceId -> @InvoiceId (optional) */
        public Integer eximInvoiceId;
        /** exImLcOrderId -> @ContractId (optional) */
        public Integer exImLcOrderId;
        /** fromDate -> @GpDateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @gpDateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** pageNumber -> @PageNumber (optional) */
        public Integer pageNumber;
        /** pageSize -> @PageSize (optional) */
        public Integer pageSize;
        /** status -> @InvoiceStatus (optional) */
        public String status;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("eximInvoiceId", eximInvoiceId);
            args.put("exImLcOrderId", exImLcOrderId);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("pageNumber", pageNumber);
            args.put("pageSize", pageSize);
            args.put("status", status);
            return args;
        }
    }
}
