package com.mst.controllers.ERPPrint.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.LinkedHashMap;
import java.util.Map;

/** Weighbridge print request models. Generated by gen_print_endpoints.py. */
public final class WeighbridgePrintRequests {
    private WeighbridgePrintRequests() { }

    /** Request for /reports/print/280-weigh-bridge-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt280WeighBridgeSlipRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** gpSrNoF -> @GpSrNoF (optional) */
        public String gpSrNoF;
        /** gpSrNoT -> @GpSrNoT (optional) */
        public String gpSrNoT;
        /** id -> @Id (required) */
        public Integer id;
        /** ids -> @Ids (optional); comma separated */
        public String ids;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** gpDocumentTypeId -> @ReferenceDocTypeId (optional) */
        public Integer gpDocumentTypeId;
        /** gpId -> @ReferenceDocNoId (optional) */
        public Integer gpId;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** vehicleNo -> @VehicleNo (optional) */
        public String vehicleNo;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("gpSrNoF", gpSrNoF);
            args.put("gpSrNoT", gpSrNoT);
            args.put("id", id);
            args.put("ids", ids);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("gpDocumentTypeId", gpDocumentTypeId);
            args.put("gpId", gpId);
            args.put("documentTypeId", documentTypeId);
            args.put("vehicleNo", vehicleNo);
            return args;
        }
    }

    /** Request for /reports/print/281-weigh-bridge-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt281WeighBridgeRegisterRequest {
        /** branchesId -> @BranchId (optional) */
        public Integer branchesId;
        /** id -> @mId (optional) */
        public Integer id;
        /** fromDate -> @DateFrom (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @TicketNoFrom (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @TicketNoTo (optional) */
        public Integer toDocNo;
        /** gpSrNoF -> @GpNoFrom (optional) */
        public String gpSrNoF;
        /** gpSrNoT -> @GpNoTo (optional) */
        public String gpSrNoT;
        /** vehicleNo -> @VehicleNo (optional) */
        public String vehicleNo;
        /** refDocumentTypeIds -> @RefDocumentTypeIds (optional); comma separated */
        public String refDocumentTypeIds;
        /** branchesIds -> @BranchesIds (optional); comma separated */
        public String branchesIds;
        /** activity -> @WeighBridgeType (optional) */
        public String activity;
        /** supplierCustomerId -> @SupplierCustomerId (optional) */
        public Integer supplierCustomerId;
        /** documentTypeId -> @DocumentTypeId (optional) */
        public Integer documentTypeId;
        /** orderNoFrom -> @OrderNoFrom (optional); yyyy-MM-dd */
        public String orderNoFrom;
        /** orderNoTo -> @OrderNoTo (optional); yyyy-MM-dd */
        public String orderNoTo;
        /** companyName -> @WbPartyName (optional) */
        public String companyName;
        /** status -> @GpStatus (optional) */
        public String status;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("branchesId", branchesId);
            args.put("id", id);
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("gpSrNoF", gpSrNoF);
            args.put("gpSrNoT", gpSrNoT);
            args.put("vehicleNo", vehicleNo);
            args.put("refDocumentTypeIds", refDocumentTypeIds);
            args.put("branchesIds", branchesIds);
            args.put("activity", activity);
            args.put("supplierCustomerId", supplierCustomerId);
            args.put("documentTypeId", documentTypeId);
            args.put("orderNoFrom", orderNoFrom);
            args.put("orderNoTo", orderNoTo);
            args.put("companyName", companyName);
            args.put("status", status);
            return args;
        }
    }

    /** Request for /reports/print/281-weigh-bridge-slip-with-pics */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt281WeighBridgeSlipWithPicsRequest {
        /** fromDate -> @FromDate (optional); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional); yyyy-MM-dd */
        public String toDate;
        /** gpSrNoF -> @GpSrNoF (optional) */
        public String gpSrNoF;
        /** gpSrNoT -> @GpSrNoT (optional) */
        public String gpSrNoT;
        /** success -> @Id (required) */
        public String success;
        /** ids -> @Ids (optional); comma separated */
        public String ids;
        /** fromDocNo -> @FromDocNo (optional) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional) */
        public Integer toDocNo;
        /** gpDocumentTypeId -> @ReferenceDocTypeId (optional) */
        public Integer gpDocumentTypeId;
        /** gpId -> @ReferenceDocNoId (optional) */
        public Integer gpId;
        /** vehicleNo -> @VehicleNo (optional) */
        public String vehicleNo;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("fromDate", fromDate);
            args.put("toDate", toDate);
            args.put("gpSrNoF", gpSrNoF);
            args.put("gpSrNoT", gpSrNoT);
            args.put("success", success);
            args.put("ids", ids);
            args.put("fromDocNo", fromDocNo);
            args.put("toDocNo", toDocNo);
            args.put("gpDocumentTypeId", gpDocumentTypeId);
            args.put("gpId", gpId);
            args.put("vehicleNo", vehicleNo);
            return args;
        }
    }

    /** Request for /reports/print/wb-transation-by-gpid-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptWbTransationByGPIDSubReportRequest {
        /** gpId -> @GpId (required) */
        public Integer gpId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("gpId", gpId);
            return args;
        }
    }

    /** Request for /reports/print/wb-transation-by-outward-gpid-sub-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RptWbTransationByOutwardGPIDSubReportRequest {
        /** gpId -> @GpId (required) */
        public Integer gpId;

        public Map<String, Object> toArgs() {
            Map<String, Object> args = new LinkedHashMap<>();
            args.put("gpId", gpId);
            return args;
        }
    }
}
