#spring.datasource.url=jdbc:mysql://localhost:3306/ctx_alfateh?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/ctx_bismillah?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/ctx_hadi?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/ctx_afzal?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/ctx_waqas?autoReconnect=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/ctx_azam?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Karachi
#spring.datasource.url=jdbc:mysql://localhost:3306/ctx_ahmad_usmanwala?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Karachi
#spring.datasource.url=jdbc:mysql://localhost:3306/ctx_amjid_chodri?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Karachi
#spring.datasource.url=jdbc:mysql://localhost:3306/ctx_ishtiaq?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Karachi
# SQL Server Database Configuration for GoldenAcedb
#spring.datasource.url=jdbc:sqlserver://46.224.162.244:1433;databaseName=GoldenAcedb;encrypt=true;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=scs@2019_1421

spring.datasource.url=jdbc:sqlserver://MUHAMMADASIF-PC\\SQLEXPRESS;databaseName=GoldenAcedb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sql
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.open-in-view=true
spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true
# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.org.hibernate.envers.default_catalog=app_twenty
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.root=INFO
logging.file.name=${user.dir}/logs/application.log
logging.pattern.file=%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n
# ===============================
# = Thymeleaf configurations
# ===============================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
logging.level.net.sf.jasperreports=DEBUG
mvn spring-boot:run -Dlogging.level.net.sf.jasperreports=DEBUG
spring.thymeleaf.cache=false
spring.http.multipart.max-file-size=20MB
spring.http.multipart.max-request-size=20MB
server.address=0.0.0.0
server.port=8025
server.servlet.session.timeout=43200
server.servlet.session.cookie.max-age=43200
server.session.timeout=43200
server.session.cookie.max-age=43200
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=asifmidrees@gmail.com
spring.mail.password=idrees1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
send.email.flag=flase
recipient.email=ifrahimiba2007@gmail.com
#server.ip=http://43.206.83.97:8040/
server.ip=http://192.168.0.112:8025/
branchId=2
#43.206.83.97
#recipient.email=info@magroup.pk
#recipient.email=mr.muzamilali@gmail.com
#recipient.email=saifytarar@gmail.com
# server.servlet.context-path=/
contact.images.path=C:\\contact_images\\img
sqlDumpFile=C://wamp64//bin//mysql//mysql5.7.19//bin//mysqldump.exe 
sqlDumpFileJar=C:\\wamp64\\bin\\mysql\\mysql5.7.19\\bin\\mysqldump.exe 
# C:\wamp64\bin\mariadb\mariadb10.4.10\bin
jasperFile=C:\\japser\\creditList.jrxml 
#sqlAuditFile =  C://wamp65//bin//mysql//mysql5.7.19//bin//mysqldump.exe
checkSecondWeight=0
#baseUrl=http://45.8.148.212:8040/
#baseUrl=http://localhost:8025/
baseUrl=http://localhost:8025/
serverUrl=http://localhost:8025/
#serverUrl=http://45.8.148.212:8038/
#baseUrl=http://42.206.83.911:8025/
secondWeight=0
bezkoder.app.jwtSecret=bezKoderSecretKey
#bezkoder.app.jwtExpirationMs=15000
bezkoder.app.jwtExpirationMs=86400000
bezkoder.app.jwtRefreshExpirationMs=86400000
#CAMERA 1
hikvision.api.url=http://192.168.1.11/ISAPI
hikvision.api.username=admin
hikvision.api.password=Admin123
#CAMERA 2
hikvision.api.url1=http://192.168.1.11/ISAPI
hikvision.api.username1=admin
hikvision.api.password1=Admin123
#CAMERA 3
hikvision.api.url2=http://192.168.1.11/ISAPI
hikvision.api.username2=admin
hikvision.api.password2=Admin123
hikvision.api.token=aaaaaaa
hikvision.image.save.path=D:\\Images\\image.jpg
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.http=DEBUG
#ash.in.hand=33121021001
cash.in.hand=33121121001

