package com.mst.reports.prints;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Print buttons of the cmagt screens: one endpoint per desktop report, each returning the PDF.
 * Body = the report's arguments exactly as its contract (seeder / BLL trace) names them;
 * OrganizationId and CompanyId are taken from the session, never from the body.
 * GENERATED by migration/rpt-to-jasper/gen_print_endpoints.py - re-run it rather than editing by hand.
 */
@RestController
public class CmagtPrintController {

    private final ReportPdfService reportPdfService;

    public CmagtPrintController(ReportPdfService reportPdfService) {
        this.reportPdfService = reportPdfService;
    }

    /**
     * 1050-Print on cmagt/buyer_inquiry_booking.html
     * Template: 1050_BuyerInquiryBookingSlip.rpt  (jasper/converted/1050_BuyerInquiryBookingSlip.jrxml)
     * Procedure: [cmagt].[USP_inquiryBookingMaster_Slip]
     * Desktop: InquiryBookingMaster.BuyerInquiryBooking_Slip
     */
    @RequestMapping(value = "/reports/print/1050-buyer-inquiry-booking-slip", method = RequestMethod.POST)
    public void print1050BuyerInquiryBookingSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1050BuyerInquiryBookingSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1050BuyerInquiryBookingSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "1050_BuyerInquiryBookingSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1050-buyer-inquiry-booking-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1050BuyerInquiryBookingSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 1055-Print on cmagt/goods_dispatching_note_cmagt.html
     * Template: 1055_GdnBuyerDispatchSlip.rpt  (jasper/converted/1055_GdnBuyerDispatchSlip.jrxml)
     * Procedure: [cmagt].[USP_gdnBuyerDispatchMaster_Slip]
     * Desktop: gdnBuyerDispatchMaster.gdnBuyerDispatchMaster_Slip
     */
    @RequestMapping(value = "/reports/print/1055-gdn-buyer-dispatch-slip", method = RequestMethod.POST)
    public void print1055GdnBuyerDispatchSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1055GdnBuyerDispatchSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1055GdnBuyerDispatchSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "1055_GdnBuyerDispatchSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1055-gdn-buyer-dispatch-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1055GdnBuyerDispatchSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 1054-Print on cmagt/grn_loading_challan_cmagt.html
     * Template: 1054_GrnSupplierLoadingSlip.rpt  (jasper/converted/1054_GrnSupplierLoadingSlip.jrxml)
     * Procedure: [cmagt].[usp_grnSupplierLoadingMaster_Slip]
     * Desktop: grnSupplierLoadingMaster.grnSupplierLoading_Slip
     */
    @RequestMapping(value = "/reports/print/1054-grn-supplier-loading-slip", method = RequestMethod.POST)
    public void print1054GrnSupplierLoadingSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1054GrnSupplierLoadingSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1054GrnSupplierLoadingSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "1054_GrnSupplierLoadingSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1054-grn-supplier-loading-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1054GrnSupplierLoadingSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 1054_01-Print on cmagt/grn_loading_challan_cmagt.html
     * Template: 1054_01_GrnSupplierLoadingChallanSlip.rpt  (jasper/converted/1054_01_GrnSupplierLoadingChallanSlip.jrxml)
     * Procedure: [cmagt].[usp_grnSupplierLoadingMaster_Slip]
     * Desktop: grnSupplierLoadingMaster.grnSupplierLoading_Slip
     */
    @RequestMapping(value = "/reports/print/1054-01-grn-supplier-loading-challan-slip", method = RequestMethod.POST)
    public void print105401GrnSupplierLoadingChallanSlip(HttpServletResponse response, @RequestBody(required = false) Rpt105401GrnSupplierLoadingChallanSlipRequest request) throws IOException {
        if (request == null) request = new Rpt105401GrnSupplierLoadingChallanSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "1054_01_GrnSupplierLoadingChallanSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1054-01-grn-supplier-loading-challan-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt105401GrnSupplierLoadingChallanSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 1052-Print on cmagt/purchase_order_cmagt.html
     * Template: 1052_PurchaseOrderSlip.rpt  (jasper/converted/1052_PurchaseOrderSlip.jrxml)
     * Procedure: [cmagt].[USP_purchaseOrderMaster_Slip]
     * Desktop: purchaseOrderMaster.purchaseOrder_Slip
     */
    @RequestMapping(value = "/reports/print/1052-purchase-order-slip", method = RequestMethod.POST)
    public void print1052PurchaseOrderSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1052PurchaseOrderSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1052PurchaseOrderSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "1052_PurchaseOrderSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1052-purchase-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1052PurchaseOrderSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 1053-Print on cmagt/sale_order_cmagt.html
     * Template: 1053_saleOrderSlip.rpt  (jasper/converted/1053_saleOrderSlip.jrxml)
     * Procedure: [cmagt].[usp_saleOrderMaster_Slip]
     * Desktop: saleOrderMaster.saleOrder_Slip
     */
    @RequestMapping(value = "/reports/print/1053-sale-order-slip", method = RequestMethod.POST)
    public void print1053SaleOrderSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1053SaleOrderSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1053SaleOrderSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "1053_saleOrderSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1053-sale-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1053SaleOrderSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 1050A-Print on cmagt/sub_buyer_inquiry_booking.html
     * Template: 1050A_BuyerInquiryBookingSlip.rpt  (jasper/converted/1050A_BuyerInquiryBookingSlip.jrxml)
     * Procedure: [cmagt].[USP_inquiryBookingMaster_Slip]
     * Desktop: InquiryBookingMaster.BuyerInquiryBooking_Slip
     */
    @RequestMapping(value = "/reports/print/1050a-buyer-inquiry-booking-slip", method = RequestMethod.POST)
    public void print1050ABuyerInquiryBookingSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1050ABuyerInquiryBookingSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1050ABuyerInquiryBookingSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "1050A_BuyerInquiryBookingSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1050a-buyer-inquiry-booking-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1050ABuyerInquiryBookingSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 1051-Print on cmagt/supplier_offer_cmagt.html
     * Template: 1051_SupplierOfferSlip.rpt  (jasper/converted/1051_SupplierOfferSlip.jrxml)
     * Procedure: [cmagt].[USP_purchaseOrderMaster_Slip]
     * Desktop: purchaseOrderMaster.purchaseOrder_Slip
     */
    @RequestMapping(value = "/reports/print/1051-supplier-offer-slip", method = RequestMethod.POST)
    public void print1051SupplierOfferSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1051SupplierOfferSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1051SupplierOfferSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "1051_SupplierOfferSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1051-supplier-offer-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1051SupplierOfferSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }
}
