package com.mst.reports.prints;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Print buttons of the dashboard screens: one endpoint per desktop report, each returning the PDF.
 * Body = the report's arguments exactly as its contract (seeder / BLL trace) names them;
 * OrganizationId and CompanyId are taken from the session, never from the body.
 * GENERATED by migration/rpt-to-jasper/gen_print_endpoints.py - re-run it rather than editing by hand.
 */
@RestController
public class DashboardPrintController {

    private final ReportPdfService reportPdfService;

    public DashboardPrintController(ReportPdfService reportPdfService) {
        this.reportPdfService = reportPdfService;
    }

    /**
     * 121_02 Print / 121_02_ReceivablesAndReceiptSchedule.rpt on accounts/reports/receivables_receipt_schedule.html, dashboard/receivables_receipt_schedule.html
     * Template: 121_02_ReceivablesAndReceiptSchedule.rpt  (jasper/converted/121_02_ReceivablesAndReceiptSchedule.jrxml)
     * Procedure: usp_ReceivablesAndReceiptsSchedule
     * Desktop: VoucherReports.ReceivablesAndReceiptsSchedule
     */
    @RequestMapping(value = "/reports/print/121-02-receivables-and-receipt-schedule", method = RequestMethod.POST)
    public void print12102ReceivablesAndReceiptSchedule(HttpServletResponse response, @RequestBody(required = false) Rpt12102ReceivablesAndReceiptScheduleRequest request) throws IOException {
        if (request == null) request = new Rpt12102ReceivablesAndReceiptScheduleRequest();
        reportPdfService.writePdf(response, "121_02_ReceivablesAndReceiptSchedule.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/121-02-receivables-and-receipt-schedule */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt12102ReceivablesAndReceiptScheduleRequest {
        /** inventoryParentCategories -> @ParentCategoryId (required) */
        public String inventoryParentCategories;
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** dueDateFrom -> @DueDateFrom (optional; left out when empty); yyyy-MM-dd */
        public String dueDateFrom;
        /** dueDateTo -> @DueDateTo (optional; left out when empty); yyyy-MM-dd */
        public String dueDateTo;
        /** effectedDate -> @SaleFromDate (optional; left out when empty); yyyy-MM-dd */
        public String effectedDate;
        /** effectedDateTo -> @SaleToDate (optional; left out when empty); yyyy-MM-dd */
        public String effectedDateTo;
        /** balanceFrom -> @BalanceFrom (optional; left out when empty); yyyy-MM-dd */
        public String balanceFrom;
        /** balanceTo -> @BalanceTo (optional; left out when empty); yyyy-MM-dd */
        public String balanceTo;
        /** customGroupId -> @CustomGroupId (optional; left out when empty) */
        public Integer customGroupId;
        /** customerGroupId -> @PartyGroupId (optional; left out when empty) */
        public Integer customerGroupId;
        /** controlAccountIds -> @ControlAccountIds (optional; left out when empty); comma separated */
        public String controlAccountIds;
        /** actionId -> @ActionId (optional; left out when empty) */
        public Integer actionId;
        /** reportTypeId -> @TradeTypeId (optional; left out when empty) */
        public Integer reportTypeId;
        /** branchesIds -> @BranchesIds (optional; left out when empty); comma separated */
        public String branchesIds;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("inventoryParentCategories", inventoryParentCategories);
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("dueDateFrom", dueDateFrom);
            m.put("dueDateTo", dueDateTo);
            m.put("effectedDate", effectedDate);
            m.put("effectedDateTo", effectedDateTo);
            m.put("balanceFrom", balanceFrom);
            m.put("balanceTo", balanceTo);
            m.put("customGroupId", customGroupId);
            m.put("customerGroupId", customerGroupId);
            m.put("controlAccountIds", controlAccountIds);
            m.put("actionId", actionId);
            m.put("reportTypeId", reportTypeId);
            m.put("branchesIds", branchesIds);
            return m;
        }
    }

    /**
     * Print-842 on dashboard/stock_breakup_in_and_out_summary.html
     * Template: 842_ItemAndPMItemMapSlip.rpt  (jasper/converted/842_ItemAndPMItemMapSlip.jrxml)
     * Procedure: [MRP].[USP_ItemAndPMItemMap_SlipAndRegister]
     * Desktop: ItemAndPMItemMap.ItemAndPMItemMapSlipAndRegister
     */
    @RequestMapping(value = "/reports/print/842-item-and-pm-item-map-slip", method = RequestMethod.POST)
    public void print842ItemAndPMItemMapSlip(HttpServletResponse response, @RequestBody(required = false) Rpt842ItemAndPMItemMapSlipRequest request) throws IOException {
        if (request == null) request = new Rpt842ItemAndPMItemMapSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "842_ItemAndPMItemMapSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/842-item-and-pm-item-map-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt842ItemAndPMItemMapSlipRequest {
        /** id -> @Id (required) */
        public Integer id;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** pmItemId -> @PmItemId (optional; left out when empty) */
        public Integer pmItemId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            m.put("itemId", itemId);
            m.put("pmItemId", pmItemId);
            return m;
        }
    }

    /**
     * 121_03_PurchaseAnalyticsItemWise.rpt on dashboard/purchase_analytics_dashboard.html
     * Template: 121_03_PurchaseAnalyticsItemWise.rpt  (jasper/converted/121_03_PurchaseAnalyticsItemWise.jrxml)
     * Procedure: [dbo].[USP-PurchaseAnalyticsDashBoard_Report]
     * Desktop: Dashboard.PurchaseAnalyticsDashBoardReport
     */
    @RequestMapping(value = "/reports/print/121-03-purchase-analytics-item-wise", method = RequestMethod.POST)
    public void print12103PurchaseAnalyticsItemWise(HttpServletResponse response, @RequestBody(required = false) Rpt12103PurchaseAnalyticsItemWiseRequest request) throws IOException {
        if (request == null) request = new Rpt12103PurchaseAnalyticsItemWiseRequest();
        reportPdfService.writePdf(response, "121_03_PurchaseAnalyticsItemWise.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/121-03-purchase-analytics-item-wise */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt12103PurchaseAnalyticsItemWiseRequest {
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** itemCategoryId -> @ItemCategoryId (optional; left out when empty) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional; left out when empty) */
        public Integer itemTypeId;
        /** jobLotId -> @JobLotId (optional; left out when empty) */
        public Integer jobLotId;
        /** supplierCustomerId -> @SupplierCustomerId (optional; left out when empty) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** cropYear -> @CropYear (optional; left out when empty) */
        public String cropYear;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional; left out when empty) */
        public String inventoryParentCategories;
        /** branchesIds -> @BranchesIds (optional; left out when empty); comma separated */
        public String branchesIds;
        /** reportType -> @ReportType (required) */
        public String reportType;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("itemCategoryId", itemCategoryId);
            m.put("itemTypeId", itemTypeId);
            m.put("jobLotId", jobLotId);
            m.put("supplierCustomerId", supplierCustomerId);
            m.put("itemId", itemId);
            m.put("cropYear", cropYear);
            m.put("inventoryParentCategories", inventoryParentCategories);
            m.put("branchesIds", branchesIds);
            m.put("reportType", reportType);
            return m;
        }
    }

    /**
     * 121_04_PurchaseAnalyticsSupplierWise.rpt on dashboard/purchase_analytics_dashboard.html
     * Template: 121_04_PurchaseAnalyticsSupplierWise.rpt  (jasper/converted/121_04_PurchaseAnalyticsSupplierWise.jrxml)
     * Procedure: [dbo].[USP-PurchaseAnalyticsDashBoard_Report]
     * Desktop: Dashboard.PurchaseAnalyticsDashBoardReport
     */
    @RequestMapping(value = "/reports/print/121-04-purchase-analytics-supplier-wise", method = RequestMethod.POST)
    public void print12104PurchaseAnalyticsSupplierWise(HttpServletResponse response, @RequestBody(required = false) Rpt12104PurchaseAnalyticsSupplierWiseRequest request) throws IOException {
        if (request == null) request = new Rpt12104PurchaseAnalyticsSupplierWiseRequest();
        reportPdfService.writePdf(response, "121_04_PurchaseAnalyticsSupplierWise.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/121-04-purchase-analytics-supplier-wise */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt12104PurchaseAnalyticsSupplierWiseRequest {
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** itemCategoryId -> @ItemCategoryId (optional; left out when empty) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional; left out when empty) */
        public Integer itemTypeId;
        /** jobLotId -> @JobLotId (optional; left out when empty) */
        public Integer jobLotId;
        /** supplierCustomerId -> @SupplierCustomerId (optional; left out when empty) */
        public Integer supplierCustomerId;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** cropYear -> @CropYear (optional; left out when empty) */
        public String cropYear;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional; left out when empty) */
        public String inventoryParentCategories;
        /** branchesIds -> @BranchesIds (optional; left out when empty); comma separated */
        public String branchesIds;
        /** reportType -> @ReportType (required) */
        public String reportType;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("itemCategoryId", itemCategoryId);
            m.put("itemTypeId", itemTypeId);
            m.put("jobLotId", jobLotId);
            m.put("supplierCustomerId", supplierCustomerId);
            m.put("itemId", itemId);
            m.put("cropYear", cropYear);
            m.put("inventoryParentCategories", inventoryParentCategories);
            m.put("branchesIds", branchesIds);
            m.put("reportType", reportType);
            return m;
        }
    }
}
