package com.mst.reports.prints;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Print buttons of the export screens: one endpoint per desktop report, each returning the PDF.
 * Body = the report's arguments exactly as its contract (seeder / BLL trace) names them;
 * OrganizationId and CompanyId are taken from the session, never from the body.
 * GENERATED by migration/rpt-to-jasper/gen_print_endpoints.py - re-run it rather than editing by hand.
 */
@RestController
public class ExportPrintController {

    private final ReportPdfService reportPdfService;

    public ExportPrintController(ReportPdfService reportPdfService) {
        this.reportPdfService = reportPdfService;
    }

    /**
     * Print-529A on export/invoice_packing_list.html
     * Template: 529A_ExportInvoiceSlipPackingList.rpt  (jasper/converted/529A_ExportInvoiceSlipPackingList.jrxml)
     * Procedure: usp_ExImInvoicePackingList_Rpt
     * Desktop: ExportPdfReport.InvoicePackingList529A
     */
    @RequestMapping(value = "/reports/print/529a-export-invoice-slip-packing-list", method = RequestMethod.POST)
    public void print529AExportInvoiceSlipPackingList(HttpServletResponse response, @RequestBody(required = false) Rpt529AExportInvoiceSlipPackingListRequest request) throws IOException {
        if (request == null) request = new Rpt529AExportInvoiceSlipPackingListRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "529A_ExportInvoiceSlipPackingList.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/529a-export-invoice-slip-packing-list */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt529AExportInvoiceSlipPackingListRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * Print-529B on export/invoice_packing_list.html
     * Template: 529B_ExportInvoiceSlipPackingList.rpt  (jasper/converted/529B_ExportInvoiceSlipPackingList.jrxml)
     * Procedure: usp_ExImInvoicePackingList_Rpt
     * Desktop: ExportPdfReport.InvoicePackingList529A
     */
    @RequestMapping(value = "/reports/print/529b-export-invoice-slip-packing-list", method = RequestMethod.POST)
    public void print529BExportInvoiceSlipPackingList(HttpServletResponse response, @RequestBody(required = false) Rpt529BExportInvoiceSlipPackingListRequest request) throws IOException {
        if (request == null) request = new Rpt529BExportInvoiceSlipPackingListRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "529B_ExportInvoiceSlipPackingList.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/529b-export-invoice-slip-packing-list */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt529BExportInvoiceSlipPackingListRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * Print-529C on export/invoice_packing_list.html
     * Template: 529C_ExportInvoiceSlipPackingList.rpt  (jasper/converted/529C_ExportInvoiceSlipPackingList.jrxml)
     * Procedure: usp_ExImInvoicePackingList_Rpt
     * Desktop: ExportPdfReport.InvoicePackingList529A
     */
    @RequestMapping(value = "/reports/print/529c-export-invoice-slip-packing-list", method = RequestMethod.POST)
    public void print529CExportInvoiceSlipPackingList(HttpServletResponse response, @RequestBody(required = false) Rpt529CExportInvoiceSlipPackingListRequest request) throws IOException {
        if (request == null) request = new Rpt529CExportInvoiceSlipPackingListRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "529C_ExportInvoiceSlipPackingList.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/529c-export-invoice-slip-packing-list */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt529CExportInvoiceSlipPackingListRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }
}
