package com.mst.reports.prints;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Print buttons of the hrm screens: one endpoint per desktop report, each returning the PDF.
 * Body = the report's arguments exactly as its contract (seeder / BLL trace) names them;
 * OrganizationId and CompanyId are taken from the session, never from the body.
 * GENERATED by migration/rpt-to-jasper/gen_print_endpoints.py - re-run it rather than editing by hand.
 */
@RestController
public class HrmPrintController {

    private final ReportPdfService reportPdfService;

    public HrmPrintController(ReportPdfService reportPdfService) {
        this.reportPdfService = reportPdfService;
    }

    /**
     * 1003-Print on hrm/attendance/daily-attendance.html, hrm/reports/daily-attendance.html
     * Template: 1003-DailyAttendance.rpt  (jasper/converted/1003-DailyAttendance.jrxml)
     * Procedure: Sp_genDailyAttandance_rpt
     * Desktop: HRM_Reports.DailyAttendanceRpt
     */
    @RequestMapping(value = "/reports/print/1003-daily-attendance", method = RequestMethod.POST)
    public void print1003DailyAttendance(HttpServletResponse response, @RequestBody(required = false) Rpt1003DailyAttendanceRequest request) throws IOException {
        if (request == null) request = new Rpt1003DailyAttendanceRequest();
        reportPdfService.writePdf(response, "1003-DailyAttendance.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1003-daily-attendance */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1003DailyAttendanceRequest {
        /** department -> @DepartmentId (required) */
        public String department;
        /** date -> @Date (required); yyyy-MM-dd */
        public String date;
        /** employee -> @EmployeeId (required) */
        public String employee;
        /** shift -> @ShiftId (required) */
        public String shift;
        /** section -> @SectionId (required) */
        public String section;
        /** itemStatus -> @IsMissing (optional; left out when empty) */
        public String itemStatus;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("department", department);
            m.put("date", date);
            m.put("employee", employee);
            m.put("shift", shift);
            m.put("section", section);
            m.put("itemStatus", itemStatus);
            return m;
        }
    }

    /**
     * 1112-Print Slip on hrm/employee/employee_registration.html
     * Template: 1112-Employee_Registration_Slip.rpt  (jasper/converted/1112-Employee_Registration_Slip.jrxml)
     * Procedure: Sp_genEmployee_SlipandRegister
     * Desktop: HRM_Reports.EmployeeRegistrationSlipAndRegister
     */
    @RequestMapping(value = "/reports/print/1112-employee-registration-slip", method = RequestMethod.POST)
    public void print1112EmployeeRegistrationSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1112EmployeeRegistrationSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1112EmployeeRegistrationSlipRequest();
        reportPdfService.writePdf(response, "1112-Employee_Registration_Slip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1112-employee-registration-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1112EmployeeRegistrationSlipRequest {

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            return m;
        }
    }

    /**
     * 1008-Print on hrm/loan/employee-advance.html
     * Template: 1008-EmployeeAdvanceSlip.rpt  (jasper/converted/1008-EmployeeAdvanceSlip.jrxml)
     * Procedure: dbo.USP_EmployeeAdvanceSlip
     * Desktop: EmployeeAdvance.EmployeeAdvanceSlip
     */
    @RequestMapping(value = "/reports/print/1008-employee-advance-slip", method = RequestMethod.POST)
    public void print1008EmployeeAdvanceSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1008EmployeeAdvanceSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1008EmployeeAdvanceSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "1008-EmployeeAdvanceSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1008-employee-advance-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1008EmployeeAdvanceSlipRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 1010-Print on hrm/overtime/over-time-request.html
     * Template: 1010-OverTime_Slip.rpt  (jasper/converted/1010-OverTime_Slip.jrxml)
     * Procedure: [hrm].[USP_OverTimeRequest_SlipAndRegister]
     * Desktop: OverTimeRequest.OTSlipandRegister
     */
    @RequestMapping(value = "/reports/print/1010-over-time-slip", method = RequestMethod.POST)
    public void print1010OverTimeSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1010OverTimeSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1010OverTimeSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "1010-OverTime_Slip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1010-over-time-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1010OverTimeSlipRequest {
        /** id -> @Id (required) */
        public Integer id;
        /** sectionId -> @SectionId (optional; left out when empty) */
        public Integer sectionId;
        /** departmentId -> @DepartmentId (optional; left out when empty) */
        public Integer departmentId;
        /** requestedById -> @RequestById (optional; left out when empty) */
        public Integer requestedById;
        /** toDate -> @RequestToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** fromDate -> @RequestFromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** gpDateT -> @OverTimeToDate (optional; left out when empty); yyyy-MM-dd */
        public String gpDateT;
        /** gpDateF -> @OverTimeFromDate (optional; left out when empty); yyyy-MM-dd */
        public String gpDateF;
        /** entryDateFrom -> @EntryFromDate (optional; left out when empty); yyyy-MM-dd */
        public String entryDateFrom;
        /** entryDateTo -> @EntryToDate (optional; left out when empty); yyyy-MM-dd */
        public String entryDateTo;
        /** modifyDateFrom -> @ModifyFromDate (optional; left out when empty); yyyy-MM-dd */
        public String modifyDateFrom;
        /** modifyDateTo -> @ModifyToDate (optional; left out when empty); yyyy-MM-dd */
        public String modifyDateTo;
        /** approvedDateFrom -> @ApprovedFromDate (optional; left out when empty); yyyy-MM-dd */
        public String approvedDateFrom;
        /** approvedDateTo -> @ApprovedToDate (optional; left out when empty); yyyy-MM-dd */
        public String approvedDateTo;
        /** actionId -> @ActionId (optional; left out when empty) */
        public Integer actionId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            m.put("sectionId", sectionId);
            m.put("departmentId", departmentId);
            m.put("requestedById", requestedById);
            m.put("toDate", toDate);
            m.put("fromDate", fromDate);
            m.put("gpDateT", gpDateT);
            m.put("gpDateF", gpDateF);
            m.put("entryDateFrom", entryDateFrom);
            m.put("entryDateTo", entryDateTo);
            m.put("modifyDateFrom", modifyDateFrom);
            m.put("modifyDateTo", modifyDateTo);
            m.put("approvedDateFrom", approvedDateFrom);
            m.put("approvedDateTo", approvedDateTo);
            m.put("actionId", actionId);
            return m;
        }
    }

    /**
     * 1113-Print on hrm/reports/daily-late-and-early-departure.html
     * Template: 1113-DailyLateandEarlyDeparture.rpt  (jasper/converted/1113-DailyLateandEarlyDeparture.jrxml)
     * Procedure: Sp_hrmDailyLED_rpt
     * Desktop: HRM_Reports.DailyLateandEarlyDeparture
     */
    @RequestMapping(value = "/reports/print/1113-daily-lateand-early-departure", method = RequestMethod.POST)
    public void print1113DailyLateandEarlyDeparture(HttpServletResponse response, @RequestBody(required = false) Rpt1113DailyLateandEarlyDepartureRequest request) throws IOException {
        if (request == null) request = new Rpt1113DailyLateandEarlyDepartureRequest();
        reportPdfService.writePdf(response, "1113-DailyLateandEarlyDeparture.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1113-daily-lateand-early-departure */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1113DailyLateandEarlyDepartureRequest {
        /** partyLocationId -> @PartyLocationId (optional; left out when empty) */
        public Integer partyLocationId;
        /** docDate -> @Date (optional; left out when empty); yyyy-MM-dd */
        public String docDate;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("partyLocationId", partyLocationId);
            m.put("docDate", docDate);
            return m;
        }
    }

    /**
     * 1114-Print on hrm/reports/duty-roster-employee-wise.html
     * Template: 1114-DutyRosterEmployeeWise.rpt  (jasper/converted/1114-DutyRosterEmployeeWise.jrxml)
     * Procedure: Sp_genDutyRosterEmployeeWise_rpt
     * Desktop: HRM_Reports.genDutyRosterEmployeeWise
     */
    @RequestMapping(value = "/reports/print/1114-duty-roster-employee-wise", method = RequestMethod.POST)
    public void print1114DutyRosterEmployeeWise(HttpServletResponse response, @RequestBody(required = false) Rpt1114DutyRosterEmployeeWiseRequest request) throws IOException {
        if (request == null) request = new Rpt1114DutyRosterEmployeeWiseRequest();
        reportPdfService.writePdf(response, "1114-DutyRosterEmployeeWise.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1114-duty-roster-employee-wise */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1114DutyRosterEmployeeWiseRequest {
        /** employeeId -> @EmployeeId (optional; left out when empty) */
        public Integer employeeId;
        /** docDate -> @Date (optional; left out when empty); yyyy-MM-dd */
        public String docDate;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("employeeId", employeeId);
            m.put("docDate", docDate);
            return m;
        }
    }

    /**
     * 1004-Print on hrm/reports/employee-attendence.html, hrm/reports/employee-monthly-register.html
     * Template: 1004-EmployeeAttendance.rpt  (jasper/converted/1004-EmployeeAttendance.jrxml)
     * Procedure: Sp_genEmployeeAttendence_rpt
     * Desktop: HRM_Reports.genEmployeeAttendence
     */
    @RequestMapping(value = "/reports/print/1004-employee-attendance", method = RequestMethod.POST)
    public void print1004EmployeeAttendance(HttpServletResponse response, @RequestBody(required = false) Rpt1004EmployeeAttendanceRequest request) throws IOException {
        if (request == null) request = new Rpt1004EmployeeAttendanceRequest();
        reportPdfService.writePdf(response, "1004-EmployeeAttendance.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1004-employee-attendance */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1004EmployeeAttendanceRequest {
        /** employeeId -> @EmployeeId (optional; left out when empty) */
        public Integer employeeId;
        /** departmentId -> @DepartmentId (optional; left out when empty) */
        public Integer departmentId;
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("employeeId", employeeId);
            m.put("departmentId", departmentId);
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            return m;
        }
    }

    /**
     * 1005-Print Summary on hrm/reports/employee-attendence.html
     * Template: 1005-MonthlyAttendanceRegister_New.rpt  (jasper/converted/1005-MonthlyAttendanceRegister_New.jrxml)
     * Procedure: Sp_MonthlyAttendanceRegister_Rpt
     * Desktop: HRM_Reports.MonthlyAttendanceRegisterNew
     */
    @RequestMapping(value = "/reports/print/1005-monthly-attendance-register-new", method = RequestMethod.POST)
    public void print1005MonthlyAttendanceRegisterNew(HttpServletResponse response, @RequestBody(required = false) Rpt1005MonthlyAttendanceRegisterNewRequest request) throws IOException {
        if (request == null) request = new Rpt1005MonthlyAttendanceRegisterNewRequest();
        reportPdfService.writePdf(response, "1005-MonthlyAttendanceRegister_New.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1005-monthly-attendance-register-new */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1005MonthlyAttendanceRegisterNewRequest {
        /** month -> @Month (required) */
        public Integer month;
        /** year -> @Year (required) */
        public Integer year;
        /** employee -> @EmployeeId (required) */
        public String employee;
        /** department -> @DepartmentId (required) */
        public String department;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("month", month);
            m.put("year", year);
            m.put("employee", employee);
            m.put("department", department);
            return m;
        }
    }

    /**
     * 1001-Print on hrm/reports/employee-monthly-register.html
     * Template: 1001-EmployeeAttendenceMonthly.rpt  (jasper/converted/1001-EmployeeAttendenceMonthly.jrxml)
     * Procedure: Sp_genEmployeeMonthlyAttendence_rpt
     * Desktop: HRM_Reports.EmployeeMonthlyAttendenceRpt
     */
    @RequestMapping(value = "/reports/print/1001-employee-attendence-monthly", method = RequestMethod.POST)
    public void print1001EmployeeAttendenceMonthly(HttpServletResponse response, @RequestBody(required = false) Rpt1001EmployeeAttendenceMonthlyRequest request) throws IOException {
        if (request == null) request = new Rpt1001EmployeeAttendenceMonthlyRequest();
        reportPdfService.writePdf(response, "1001-EmployeeAttendenceMonthly.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1001-employee-attendence-monthly */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1001EmployeeAttendenceMonthlyRequest {
        /** getMonth -> @Month (required) */
        public String getMonth;
        /** getYear -> @Year (required) */
        public String getYear;
        /** employeeId -> @EmployeeId (optional; left out when empty) */
        public Integer employeeId;
        /** departmentId -> @DepartmentId (optional; left out when empty) */
        public Integer departmentId;
        /** sectionId -> @SectionId (optional; left out when empty) */
        public Integer sectionId;
        /** partyLocationId -> @PartyLocationId (optional; left out when empty) */
        public Integer partyLocationId;
        /** shiftId -> @ShiftId (optional; left out when empty) */
        public Integer shiftId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("getMonth", getMonth);
            m.put("getYear", getYear);
            m.put("employeeId", employeeId);
            m.put("departmentId", departmentId);
            m.put("sectionId", sectionId);
            m.put("partyLocationId", partyLocationId);
            m.put("shiftId", shiftId);
            return m;
        }
    }

    /**
     * 1002-Print on hrm/reports/employee-monthly-register.html
     * Template: 1002-AttendanceRegister.rpt  (jasper/converted/1002-AttendanceRegister.jrxml)
     * Procedure: Sp_AttendanceRegister_Rpt
     * Desktop: HRM_Reports.MonthlyAttendanceRegisterRpt
     */
    @RequestMapping(value = "/reports/print/1002-attendance-register", method = RequestMethod.POST)
    public void print1002AttendanceRegister(HttpServletResponse response, @RequestBody(required = false) Rpt1002AttendanceRegisterRequest request) throws IOException {
        if (request == null) request = new Rpt1002AttendanceRegisterRequest();
        reportPdfService.writePdf(response, "1002-AttendanceRegister.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1002-attendance-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1002AttendanceRegisterRequest {
        /** dutyMonth -> @Month (required) */
        public String dutyMonth;
        /** dutyYear -> @Year (required) */
        public String dutyYear;
        /** department -> @DepartmentId (required) */
        public String department;
        /** employee -> @EmployeeId (required) */
        public String employee;
        /** shift -> @ShiftId (required) */
        public String shift;
        /** section -> @SectionId (required) */
        public String section;
        /** partyLocation -> @PartyLocationId (required) */
        public String partyLocation;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("dutyMonth", dutyMonth);
            m.put("dutyYear", dutyYear);
            m.put("department", department);
            m.put("employee", employee);
            m.put("shift", shift);
            m.put("section", section);
            m.put("partyLocation", partyLocation);
            return m;
        }
    }

    /**
     * 1101-Print on hrm/reports/employee-register.html
     * Template: 1101-EmployeeListDepartmentWiseActiveInactive.rpt  (jasper/converted/1101-EmployeeListDepartmentWiseActiveInactive.jrxml)
     * Procedure: Sp_genEmployeeHistory_Rpt
     * Desktop: HRM_Reports.EmployeeHistoryRpt
     */
    @RequestMapping(value = "/reports/print/1101-employee-list-department-wise-active-inactive", method = RequestMethod.POST)
    public void print1101EmployeeListDepartmentWiseActiveInactive(HttpServletResponse response, @RequestBody(required = false) Rpt1101EmployeeListDepartmentWiseActiveInactiveRequest request) throws IOException {
        if (request == null) request = new Rpt1101EmployeeListDepartmentWiseActiveInactiveRequest();
        reportPdfService.writePdf(response, "1101-EmployeeListDepartmentWiseActiveInactive.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1101-employee-list-department-wise-active-inactive */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1101EmployeeListDepartmentWiseActiveInactiveRequest {
        /** shiftId -> @ShiftId (optional; left out when empty) */
        public Integer shiftId;
        /** sectionId -> @SectionId (optional; left out when empty) */
        public Integer sectionId;
        /** departmentId -> @DepartmentId (optional; left out when empty) */
        public Integer departmentId;
        /** branchesId -> @BranchId (optional; left out when empty) */
        public Integer branchesId;
        /** partyLocationId -> @DesignationId (optional; left out when empty) */
        public Integer partyLocationId;
        /** employeeId -> @EmployeeId (optional; left out when empty) */
        public Integer employeeId;
        /** isApproved -> @Active (optional; left out when empty) */
        public Boolean isApproved;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("shiftId", shiftId);
            m.put("sectionId", sectionId);
            m.put("departmentId", departmentId);
            m.put("branchesId", branchesId);
            m.put("partyLocationId", partyLocationId);
            m.put("employeeId", employeeId);
            m.put("isApproved", isApproved);
            return m;
        }
    }

    /**
     * 1101_01-Print on hrm/reports/employee-register.html
     * Template: 1101_01-EmployeeListDepartmentWiseActiveInactive.rpt  (jasper/converted/1101_01-EmployeeListDepartmentWiseActiveInactive.jrxml)
     * Procedure: Sp_genEmployeeHistory_Rpt
     * Desktop: HRM_Reports.EmployeeHistoryRpt
     */
    @RequestMapping(value = "/reports/print/1101-01-employee-list-department-wise-active-inactive", method = RequestMethod.POST)
    public void print110101EmployeeListDepartmentWiseActiveInactive(HttpServletResponse response, @RequestBody(required = false) Rpt110101EmployeeListDepartmentWiseActiveInactiveRequest request) throws IOException {
        if (request == null) request = new Rpt110101EmployeeListDepartmentWiseActiveInactiveRequest();
        reportPdfService.writePdf(response, "1101_01-EmployeeListDepartmentWiseActiveInactive.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1101-01-employee-list-department-wise-active-inactive */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt110101EmployeeListDepartmentWiseActiveInactiveRequest {
        /** shiftId -> @ShiftId (optional; left out when empty) */
        public Integer shiftId;
        /** sectionId -> @SectionId (optional; left out when empty) */
        public Integer sectionId;
        /** departmentId -> @DepartmentId (optional; left out when empty) */
        public Integer departmentId;
        /** branchesId -> @BranchId (optional; left out when empty) */
        public Integer branchesId;
        /** partyLocationId -> @DesignationId (optional; left out when empty) */
        public Integer partyLocationId;
        /** employeeId -> @EmployeeId (optional; left out when empty) */
        public Integer employeeId;
        /** isApproved -> @Active (optional; left out when empty) */
        public Boolean isApproved;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("shiftId", shiftId);
            m.put("sectionId", sectionId);
            m.put("departmentId", departmentId);
            m.put("branchesId", branchesId);
            m.put("partyLocationId", partyLocationId);
            m.put("employeeId", employeeId);
            m.put("isApproved", isApproved);
            return m;
        }
    }

    /**
     * 1011-EmployeeOverTimeSlip.rpt on hrm/overtime/employee-over-time.html
     * Template: 1011-EmployeeOverTimeSlip.rpt  (jasper/converted/1011-EmployeeOverTimeSlip.jrxml)
     * Procedure: [hrm].[USP_EmployeeOverTime_SlipAndRegister]
     * Desktop: EmployeeOverTime.EmployeeOverTime_SlipAndRegister
     */
    @RequestMapping(value = "/reports/print/1011-employee-over-time-slip", method = RequestMethod.POST)
    public void print1011EmployeeOverTimeSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1011EmployeeOverTimeSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1011EmployeeOverTimeSlipRequest();
        reportPdfService.writePdf(response, "1011-EmployeeOverTimeSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1011-employee-over-time-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1011EmployeeOverTimeSlipRequest {
        /** monthHistory -> @Month (required) */
        public String monthHistory;
        /** yearHistory -> @Year (required) */
        public String yearHistory;
        /** employeeHistory -> @EmployeeId (required) */
        public String employeeHistory;
        /** dutyRoasterId -> @Id (optional; left out when empty) */
        public Integer dutyRoasterId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("monthHistory", monthHistory);
            m.put("yearHistory", yearHistory);
            m.put("employeeHistory", employeeHistory);
            m.put("dutyRoasterId", dutyRoasterId);
            return m;
        }
    }
}
