package com.mst.reports.prints;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Print buttons of the inventory screens: one endpoint per desktop report, each returning the PDF.
 * Body = the report's arguments exactly as its contract (seeder / BLL trace) names them;
 * OrganizationId and CompanyId are taken from the session, never from the body.
 * GENERATED by migration/rpt-to-jasper/gen_print_endpoints.py - re-run it rather than editing by hand.
 */
@RestController
public class InventoryPrintController {

    private final ReportPdfService reportPdfService;

    public InventoryPrintController(ReportPdfService reportPdfService) {
        this.reportPdfService = reportPdfService;
    }

    /**
     * Print on inventory/item_min_max_rate.html
     * Template: 326-GetItemsFromMinAndMaxRateSchedule.rpt  (jasper/converted/326-GetItemsFromMinAndMaxRateSchedule.jrxml)
     * Procedure: usp_GetItemsFromMinAndMaxRateSchedule
     * Desktop: ItemMinMaxRateSchedule.GetItemsFromMinAndMaxRateSchedule
     */
    @RequestMapping(value = "/reports/print/326-get-items-from-min-and-max-rate-schedule", method = RequestMethod.POST)
    public void print326GetItemsFromMinAndMaxRateSchedule(HttpServletResponse response, @RequestBody(required = false) Rpt326GetItemsFromMinAndMaxRateScheduleRequest request) throws IOException {
        if (request == null) request = new Rpt326GetItemsFromMinAndMaxRateScheduleRequest();
        reportPdfService.writePdf(response, "326-GetItemsFromMinAndMaxRateSchedule.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/326-get-items-from-min-and-max-rate-schedule */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt326GetItemsFromMinAndMaxRateScheduleRequest {
        /** itemCategoryId -> @ItemCategoryId (optional; left out when empty) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional; left out when empty) */
        public Integer itemTypeId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional; left out when empty) */
        public String inventoryParentCategories;
        /** effectedDate -> @EffectedDate (optional; left out when empty); yyyy-MM-dd */
        public String effectedDate;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("itemCategoryId", itemCategoryId);
            m.put("itemTypeId", itemTypeId);
            m.put("inventoryParentCategories", inventoryParentCategories);
            m.put("effectedDate", effectedDate);
            return m;
        }
    }

    /**
     * Print on inventory/item_min_max_rate.html
     * Template: 326_01_ItemsFromMinAndMaxRateSchedule_FormHistory.rpt  (jasper/converted/326_01_ItemsFromMinAndMaxRateSchedule_FormHistory.jrxml)
     * Procedure: usp_GetLastItemMinAndMaxRateByItemIdAndUomId
     * Desktop: ItemMinMaxRateSchedule.GetLastItemMinAndMaxRateByItemIdAndUomId
     */
    @RequestMapping(value = "/reports/print/326-01-items-from-min-and-max-rate-schedule-form-history", method = RequestMethod.POST)
    public void print32601ItemsFromMinAndMaxRateScheduleFormHistory(HttpServletResponse response, @RequestBody(required = false) Rpt32601ItemsFromMinAndMaxRateScheduleFormHistoryRequest request) throws IOException {
        if (request == null) request = new Rpt32601ItemsFromMinAndMaxRateScheduleFormHistoryRequest();
        reportPdfService.writePdf(response, "326_01_ItemsFromMinAndMaxRateSchedule_FormHistory.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/326-01-items-from-min-and-max-rate-schedule-form-history */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt32601ItemsFromMinAndMaxRateScheduleFormHistoryRequest {
        /** itemId -> @ItemId (required) */
        public Integer itemId;
        /** rateUOM -> @RateUomId (optional; left out when empty) */
        public String rateUOM;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("itemId", itemId);
            m.put("rateUOM", rateUOM);
            return m;
        }
    }

    /**
     * 417-Stock Report on inventory/stock_transactions.html
     * Template: 417-InventoryStockTransactionsReport.rpt  (jasper/converted/417-InventoryStockTransactionsReport.jrxml)
     * Procedure: [pcc].[USP-EvaluationStockTransactionsReport]
     * Desktop: InventoryStockEvalautionDetail.EvaluationStockTransactionsReport
     */
    @RequestMapping(value = "/reports/print/417-inventory-stock-transactions-report", method = RequestMethod.POST)
    public void print417InventoryStockTransactionsReport(HttpServletResponse response, @RequestBody(required = false) Rpt417InventoryStockTransactionsReportRequest request) throws IOException {
        if (request == null) request = new Rpt417InventoryStockTransactionsReportRequest();
        reportPdfService.writePdf(response, "417-InventoryStockTransactionsReport.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/417-inventory-stock-transactions-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt417InventoryStockTransactionsReportRequest {
        /** supplierCustomerId -> @SupplierCustomerId (optional; left out when empty) */
        public Integer supplierCustomerId;
        /** documentTypeId -> @DocumentTypeId (optional; left out when empty) */
        public Integer documentTypeId;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** fromDate -> @DateFrom (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** warehouseId -> @WarehouseId (optional; left out when empty) */
        public Integer warehouseId;
        /** jobLotId -> @JobLotId (optional; left out when empty) */
        public Integer jobLotId;
        /** itemClassGroupId -> @ItemClassGroupId (optional; left out when empty) */
        public Integer itemClassGroupId;
        /** parentCategoryId -> @InventoryParentCategoriesId (optional; left out when empty) */
        public Integer parentCategoryId;
        /** itemCategoryId -> @ItemCategoryId (optional; left out when empty) */
        public Integer itemCategoryId;
        /** itemTypeId -> @ItemTypeId (optional; left out when empty) */
        public Integer itemTypeId;
        /** itemTypeIds -> @ItemTypeIds (optional; left out when empty); comma separated */
        public String itemTypeIds;
        /** warehouseIds -> @WarehouseIds (optional; left out when empty); comma separated */
        public String warehouseIds;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("supplierCustomerId", supplierCustomerId);
            m.put("documentTypeId", documentTypeId);
            m.put("itemId", itemId);
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("warehouseId", warehouseId);
            m.put("jobLotId", jobLotId);
            m.put("itemClassGroupId", itemClassGroupId);
            m.put("parentCategoryId", parentCategoryId);
            m.put("itemCategoryId", itemCategoryId);
            m.put("itemTypeId", itemTypeId);
            m.put("itemTypeIds", itemTypeIds);
            m.put("warehouseIds", warehouseIds);
            return m;
        }
    }
}
