package com.mst.reports.prints;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Print buttons of the production screens: one endpoint per desktop report, each returning the PDF.
 * Body = the report's arguments exactly as its contract (seeder / BLL trace) names them;
 * OrganizationId and CompanyId are taken from the session, never from the body.
 * GENERATED by migration/rpt-to-jasper/gen_print_endpoints.py - re-run it rather than editing by hand.
 */
@RestController
public class ProductionPrintController {

    private final ReportPdfService reportPdfService;

    public ProductionPrintController(ReportPdfService reportPdfService) {
        this.reportPdfService = reportPdfService;
    }

    /**
     * Print-666 on production/daily_plant_consumed_hours.html
     * Template: 666-DailyPlantConsumedHours_FormHistoryReport.rpt  (jasper/converted/666-DailyPlantConsumedHours_FormHistoryReport.jrxml)
     * Procedure: [dbo].[USP_DailyPlantConsumedHours_FormHistoryReport]
     * Desktop: DailyPlantConsumedHours.FormHistoryAndReport
     */
    @RequestMapping(value = "/reports/print/666-daily-plant-consumed-hours-form-history-report", method = RequestMethod.POST)
    public void print666DailyPlantConsumedHoursFormHistoryReport(HttpServletResponse response, @RequestBody(required = false) Rpt666DailyPlantConsumedHoursFormHistoryReportRequest request) throws IOException {
        if (request == null) request = new Rpt666DailyPlantConsumedHoursFormHistoryReportRequest();
        reportPdfService.writePdf(response, "666-DailyPlantConsumedHours_FormHistoryReport.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/666-daily-plant-consumed-hours-form-history-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt666DailyPlantConsumedHoursFormHistoryReportRequest {
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** entryDateFrom -> @EntryFromDate (optional; left out when empty); yyyy-MM-dd */
        public String entryDateFrom;
        /** entryDateTo -> @EntryToDate (optional; left out when empty); yyyy-MM-dd */
        public String entryDateTo;
        /** modifyDateFrom -> @ModifyFromDate (optional; left out when empty); yyyy-MM-dd */
        public String modifyDateFrom;
        /** modifyDateTo -> @ModifyToDate (optional; left out when empty); yyyy-MM-dd */
        public String modifyDateTo;
        /** jobOrderId -> @JobOrderId (optional; left out when empty) */
        public Integer jobOrderId;
        /** id -> @Id (optional; left out when empty) */
        public Integer id;
        /** reasonId -> @ReasonId (optional; left out when empty) */
        public Integer reasonId;
        /** monthDate -> @MonthDate (optional; left out when empty); yyyy-MM-dd */
        public String monthDate;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("entryDateFrom", entryDateFrom);
            m.put("entryDateTo", entryDateTo);
            m.put("modifyDateFrom", modifyDateFrom);
            m.put("modifyDateTo", modifyDateTo);
            m.put("jobOrderId", jobOrderId);
            m.put("id", id);
            m.put("reasonId", reasonId);
            m.put("monthDate", monthDate);
            return m;
        }
    }

    /**
     * Print-627 on production/output_allocation_export_invoice.html
     * Template: 627-ProductionOutputAllocationWithExportInvoice.rpt  (jasper/converted/627-ProductionOutputAllocationWithExportInvoice.jrxml)
     * Procedure: [dbo].[usp_ProductionOutputAllocationWithExportInvoice_SlipAndRegister]
     * Desktop: ProductionOutputAllocationWithExportInvoice.ProductionOutputAllocationWithExportInvoice_SlipAndRegister
     */
    @RequestMapping(value = "/reports/print/627-production-output-allocation-with-export-invoice", method = RequestMethod.POST)
    public void print627ProductionOutputAllocationWithExportInvoice(HttpServletResponse response, @RequestBody(required = false) Rpt627ProductionOutputAllocationWithExportInvoiceRequest request) throws IOException {
        if (request == null) request = new Rpt627ProductionOutputAllocationWithExportInvoiceRequest();
        reportPdfService.writePdf(response, "627-ProductionOutputAllocationWithExportInvoice.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/627-production-output-allocation-with-export-invoice */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt627ProductionOutputAllocationWithExportInvoiceRequest {
        /** jobOrderId -> @JobOrderId (optional; left out when empty) */
        public Integer jobOrderId;
        /** invoiceId -> @ExImInvoiceId (optional; left out when empty) */
        public Integer invoiceId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("jobOrderId", jobOrderId);
            m.put("invoiceId", invoiceId);
            return m;
        }
    }

    /**
     * 601-Print on production/p280_input.html, production/p280_output.html
     * Template: 601-InvFoodProductionSlip.rpt  (jasper/converted/601-InvFoodProductionSlip.jrxml)
     * Procedure: Sp_InvFoodProduction_Rpt
     * Desktop: InvFoodProductionReports.InvFoodProductionSlip
     */
    @RequestMapping(value = "/reports/print/601-inv-food-production-slip", method = RequestMethod.POST)
    public void print601InvFoodProductionSlip(HttpServletResponse response, @RequestBody(required = false) Rpt601InvFoodProductionSlipRequest request) throws IOException {
        if (request == null) request = new Rpt601InvFoodProductionSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "601-InvFoodProductionSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/601-inv-food-production-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt601InvFoodProductionSlipRequest {
        /** branchesId -> @BranchesId (optional; left out when empty) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional; left out when empty) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional; left out when empty) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional; left out when empty) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** warehouseId -> @WarehouseId (optional; left out when empty) */
        public Integer warehouseId;
        /** jobOrderFrom -> @JobOrderFrom (optional; left out when empty); yyyy-MM-dd */
        public String jobOrderFrom;
        /** jobOrderTo -> @JobOrderTo (optional; left out when empty); yyyy-MM-dd */
        public String jobOrderTo;
        /** jobOrderId -> @JobOrderId (optional; left out when empty) */
        public Integer jobOrderId;
        /** reqType -> @EntryType (required) */
        public String reqType;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("branchesId", branchesId);
            m.put("projectsId", projectsId);
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("fromDocNo", fromDocNo);
            m.put("toDocNo", toDocNo);
            m.put("id", id);
            m.put("warehouseId", warehouseId);
            m.put("jobOrderFrom", jobOrderFrom);
            m.put("jobOrderTo", jobOrderTo);
            m.put("jobOrderId", jobOrderId);
            m.put("reqType", reqType);
            return m;
        }
    }

    /**
     * Print-606 on production/p280_overhead.html, production/p280_packing_material.html
     * Template: 606-InvFoodProductionPackingAndOverHeadReportByJobOrder.rpt  (jasper/converted/606-InvFoodProductionPackingAndOverHeadReportByJobOrder.jrxml)
     * Procedure: Sp_InvFoodProductionPackingAndOverHeadReportByJobOrder
     * Desktop: InvFoodProductionReports.InvFoodProductionPackingAndOverHeadReportByJobOrder
     */
    @RequestMapping(value = "/reports/print/606-inv-food-production-packing-and-over-head-report-by-job-order", method = RequestMethod.POST)
    public void print606InvFoodProductionPackingAndOverHeadReportByJobOrder(HttpServletResponse response, @RequestBody(required = false) Rpt606InvFoodProductionPackingAndOverHeadReportByJobOrderRequest request) throws IOException {
        if (request == null) request = new Rpt606InvFoodProductionPackingAndOverHeadReportByJobOrderRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "606-InvFoodProductionPackingAndOverHeadReportByJobOrder.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/606-inv-food-production-packing-and-over-head-report-by-job-order */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt606InvFoodProductionPackingAndOverHeadReportByJobOrderRequest {
        /** reportType -> @ReportType (required) */
        public String reportType;
        /** jobOrderId -> @JobOrderId (optional; left out when empty) */
        public Integer jobOrderId;
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("reportType", reportType);
            m.put("jobOrderId", jobOrderId);
            m.put("id", id);
            return m;
        }
    }

    /**
     * 602A_Print on production/p280_settlement.html
     * Template: 602A-InvRptProductionSummeryWithValues.rpt  (jasper/converted/602A-InvRptProductionSummeryWithValues.jrxml)
     * Procedure: Sp_InvFoodProduction_Summery_Rpt
     * Desktop: InvFoodProductionReports.InvFoodProductionRecoverySummeryReport
     */
    @RequestMapping(value = "/reports/print/602a-production-summery-with-values", method = RequestMethod.POST)
    public void print602AProductionSummeryWithValues(HttpServletResponse response, @RequestBody(required = false) Rpt602AProductionSummeryWithValuesRequest request) throws IOException {
        if (request == null) request = new Rpt602AProductionSummeryWithValuesRequest();
        reportPdfService.writePdf(response, "602A-InvRptProductionSummeryWithValues.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/602a-production-summery-with-values */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt602AProductionSummeryWithValuesRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;
        /** plantId -> @PlantId (optional; left out when empty) */
        public Integer plantId;
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** branchesIds -> @BranchesIds (optional; left out when empty); comma separated */
        public String branchesIds;
        /** actionId -> @ActionId (optional; left out when empty) */
        public Integer actionId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("jobOrderId", jobOrderId);
            m.put("plantId", plantId);
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("branchesIds", branchesIds);
            m.put("actionId", actionId);
            return m;
        }
    }

    /**
     * 613_Print on production/p280_settlement.html
     * Template: 613-InvRptProductionSummeryWithExpValues.rpt  (jasper/converted/613-InvRptProductionSummeryWithExpValues.jrxml)
     * Procedure: Sp_InvFoodProduction_Summery2_Rpt
     * Desktop: InvFoodProductionReports.InvFoodProduction_Summery2_Rpt
     */
    @RequestMapping(value = "/reports/print/613-production-summery-with-exp-values", method = RequestMethod.POST)
    public void print613ProductionSummeryWithExpValues(HttpServletResponse response, @RequestBody(required = false) Rpt613ProductionSummeryWithExpValuesRequest request) throws IOException {
        if (request == null) request = new Rpt613ProductionSummeryWithExpValuesRequest();
        reportPdfService.writePdf(response, "613-InvRptProductionSummeryWithExpValues.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/613-production-summery-with-exp-values */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt613ProductionSummeryWithExpValuesRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;
        /** actionId -> @ActionId (optional; left out when empty) */
        public Integer actionId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("jobOrderId", jobOrderId);
            m.put("actionId", actionId);
            return m;
        }
    }

    /**
     * 615_Print on production/p280_settlement.html
     * Template: 615-InvRptProductionSummery.rpt  (jasper/converted/615-InvRptProductionSummery.jrxml)
     * Procedure: Sp_InvFoodProduction_Summery3_Rpt
     * Desktop: InvFoodProductionReports.InvFoodProduction_Summery3_Rpt
     */
    @RequestMapping(value = "/reports/print/615-production-summery", method = RequestMethod.POST)
    public void print615ProductionSummery(HttpServletResponse response, @RequestBody(required = false) Rpt615ProductionSummeryRequest request) throws IOException {
        if (request == null) request = new Rpt615ProductionSummeryRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "615-InvRptProductionSummery.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/615-production-summery */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt615ProductionSummeryRequest {
        /** id -> @JobOrderId (required) */
        public Integer id;
        /** actionId -> @ActionId (optional; left out when empty) */
        public Integer actionId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            m.put("actionId", actionId);
            return m;
        }
    }

    /**
     * 623-Print on production/production_against_job_order.html
     * Template: 623-InvFoodProduction_ConsumptionReport.rpt  (jasper/converted/623-InvFoodProduction_ConsumptionReport.jrxml)
     * Procedure: [dbo].[USP_InvFoodProduction_ConsumptionReport]
     * Desktop: InvFoodProductionReports.FoodProduction_ConsumptionReport
     */
    @RequestMapping(value = "/reports/print/623-inv-food-production-consumption-report", method = RequestMethod.POST)
    public void print623InvFoodProductionConsumptionReport(HttpServletResponse response, @RequestBody(required = false) Rpt623InvFoodProductionConsumptionReportRequest request) throws IOException {
        if (request == null) request = new Rpt623InvFoodProductionConsumptionReportRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "623-InvFoodProduction_ConsumptionReport.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/623-inv-food-production-consumption-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt623InvFoodProductionConsumptionReportRequest {
        /** branchesId -> @BranchesId (optional; left out when empty) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional; left out when empty) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional; left out when empty) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional; left out when empty) */
        public Integer toDocNo;
        /** id -> @Id (required) */
        public Integer id;
        /** warehouseId -> @WarehouseId (optional; left out when empty) */
        public Integer warehouseId;
        /** jobOrderFrom -> @JobOrderFrom (optional; left out when empty); yyyy-MM-dd */
        public String jobOrderFrom;
        /** jobOrderTo -> @JobOrderTo (optional; left out when empty); yyyy-MM-dd */
        public String jobOrderTo;
        /** jobOrderId -> @JobOrderId (optional; left out when empty) */
        public Integer jobOrderId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("branchesId", branchesId);
            m.put("projectsId", projectsId);
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("fromDocNo", fromDocNo);
            m.put("toDocNo", toDocNo);
            m.put("id", id);
            m.put("warehouseId", warehouseId);
            m.put("jobOrderFrom", jobOrderFrom);
            m.put("jobOrderTo", jobOrderTo);
            m.put("jobOrderId", jobOrderId);
            return m;
        }
    }

    /**
     * 620-Print on production/production_job_order_main.html
     * Template: 620-ProductionJobOrderSlip.rpt  (jasper/converted/620-ProductionJobOrderSlip.jrxml)
     * Procedure: Sp_InvProductionJobOrder_Slip_Rpt
     * Desktop: InvProductionJobOrder.GetPrintSlipAndReport
     */
    @RequestMapping(value = "/reports/print/620-production-job-order-slip", method = RequestMethod.POST)
    public void print620ProductionJobOrderSlip(HttpServletResponse response, @RequestBody(required = false) Rpt620ProductionJobOrderSlipRequest request) throws IOException {
        if (request == null) request = new Rpt620ProductionJobOrderSlipRequest();
        reportPdfService.writePdf(response, "620-ProductionJobOrderSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/620-production-job-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt620ProductionJobOrderSlipRequest {
        /** id -> @hId (optional; left out when empty) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 605-Print on production/stock_conversion.html
     * Template: 605-StockConversionSummaryNewRpt.rpt  (jasper/converted/605-StockConversionSummaryNewRpt.jrxml)
     * Procedure: SpInvStockConversion_Summery_Rpt
     * Desktop: InvFoodProductionReports.StockConversionSummeryReport
     */
    @RequestMapping(value = "/reports/print/605-stock-conversion-summary-new", method = RequestMethod.POST)
    public void print605StockConversionSummaryNew(HttpServletResponse response, @RequestBody(required = false) Rpt605StockConversionSummaryNewRequest request) throws IOException {
        if (request == null) request = new Rpt605StockConversionSummaryNewRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "605-StockConversionSummaryNewRpt.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/605-stock-conversion-summary-new */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt605StockConversionSummaryNewRequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 812-Print on production/reports/packing_material_consumption.html
     * Template: 812-ProductionKamPackMaterialConsumption.rpt  (jasper/converted/812-ProductionKamPackMaterialConsumption.jrxml)
     * Procedure: Sp_InvProductionCumPackMaterialConsumption_Register
     * Desktop: InvFoodProductionReports.ProductionCumPackMaterialConsumption_Register_812
     */
    @RequestMapping(value = "/reports/print/812-production-kam-pack-material-consumption", method = RequestMethod.POST)
    public void print812ProductionKamPackMaterialConsumption(HttpServletResponse response, @RequestBody(required = false) Rpt812ProductionKamPackMaterialConsumptionRequest request) throws IOException {
        if (request == null) request = new Rpt812ProductionKamPackMaterialConsumptionRequest();
        reportPdfService.writePdf(response, "812-ProductionKamPackMaterialConsumption.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/812-production-kam-pack-material-consumption */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt812ProductionKamPackMaterialConsumptionRequest {
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** pmItemId -> @PmItemId (optional; left out when empty) */
        public Integer pmItemId;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** branchesIds -> @BranchesIds (optional; left out when empty); comma separated */
        public String branchesIds;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("pmItemId", pmItemId);
            m.put("itemId", itemId);
            m.put("branchesIds", branchesIds);
            return m;
        }
    }

    /**
     * 604-Print-Register on production/reports/production_comparison.html
     * Template: 604-FoodProductionComparisonRpt.rpt  (jasper/converted/604-FoodProductionComparisonRpt.jrxml)
     * Procedure: SpInvFoodProductionComparisons_Rpt
     * Desktop: InvFoodProduction.FoodProductionComparisons_Rpt
     */
    @RequestMapping(value = "/reports/print/604-food-production-comparison", method = RequestMethod.POST)
    public void print604FoodProductionComparison(HttpServletResponse response, @RequestBody(required = false) Rpt604FoodProductionComparisonRequest request) throws IOException {
        if (request == null) request = new Rpt604FoodProductionComparisonRequest();
        reportPdfService.writePdf(response, "604-FoodProductionComparisonRpt.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/604-food-production-comparison */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt604FoodProductionComparisonRequest {
        /** reportType -> @ProductionType (required) */
        public String reportType;
        /** fromDocNo -> @DocNoFrom (optional; left out when empty) */
        public Integer fromDocNo;
        /** toDocNo -> @DocNoTo (optional; left out when empty) */
        public Integer toDocNo;
        /** itemId -> @PlantId (optional; left out when empty) */
        public Integer itemId;
        /** jobOrderId -> @JobOrderId (optional; left out when empty) */
        public Integer jobOrderId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("reportType", reportType);
            m.put("fromDocNo", fromDocNo);
            m.put("toDocNo", toDocNo);
            m.put("itemId", itemId);
            m.put("jobOrderId", jobOrderId);
            return m;
        }
    }

    /**
     * 625-Print For Detail Grid Data on production/reports/production_summary.html
     * Template: 625_FoodProduction_DocWiseSummeryReport.rpt  (jasper/converted/625_FoodProduction_DocWiseSummeryReport.jrxml)
     * Procedure: [dbo].[USP_FoodProduction_DocWiseSummeryReport]
     * Desktop: InvFoodProductionReports.FoodProduction_DocWiseSummeryReport
     */
    @RequestMapping(value = "/reports/print/625-food-production-doc-wise-summery-report", method = RequestMethod.POST)
    public void print625FoodProductionDocWiseSummeryReport(HttpServletResponse response, @RequestBody(required = false) Rpt625FoodProductionDocWiseSummeryReportRequest request) throws IOException {
        if (request == null) request = new Rpt625FoodProductionDocWiseSummeryReportRequest();
        reportPdfService.writePdf(response, "625_FoodProduction_DocWiseSummeryReport.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/625-food-production-doc-wise-summery-report */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt625FoodProductionDocWiseSummeryReportRequest {
        /** jobOrderId -> @JobOrderId (required) */
        public Integer jobOrderId;
        /** plantId -> @PlantId (optional; left out when empty) */
        public Integer plantId;
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** branchesIds -> @BranchesIds (optional; left out when empty); comma separated */
        public String branchesIds;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("jobOrderId", jobOrderId);
            m.put("plantId", plantId);
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("branchesIds", branchesIds);
            return m;
        }
    }
}
