package com.mst.reports.prints;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Print buttons of the sale screens: one endpoint per desktop report, each returning the PDF.
 * Body = the report's arguments exactly as its contract (seeder / BLL trace) names them;
 * OrganizationId and CompanyId are taken from the session, never from the body.
 * GENERATED by migration/rpt-to-jasper/gen_print_endpoints.py - re-run it rather than editing by hand.
 */
@RestController
public class SalePrintController {

    private final ReportPdfService reportPdfService;

    public SalePrintController(ReportPdfService reportPdfService) {
        this.reportPdfService = reportPdfService;
    }

    /**
     * 260-Print on sale/gdn.html
     * Template: 260-InvRptGdnRiceSlip.rpt  (jasper/converted/260-InvRptGdnRiceSlip.jrxml)
     * Procedure: Sp_InvGdn_SlipAndRegisterRice_Rpt
     * Desktop: InvGrnandGdnReports.InvGdnSlip260
     */
    @RequestMapping(value = "/reports/print/260-gdn-rice-slip", method = RequestMethod.POST)
    public void print260GdnRiceSlip(HttpServletResponse response, @RequestBody(required = false) Rpt260GdnRiceSlipRequest request) throws IOException {
        if (request == null) request = new Rpt260GdnRiceSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "260-InvRptGdnRiceSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/260-gdn-rice-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt260GdnRiceSlipRequest {
        /** fromDate -> @GrnDateF (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @GrnDateT (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** id -> @gdnId (required) */
        public Integer id;
        /** documentTypeId -> @DocumentTypeId (optional; left out when empty) */
        public Integer documentTypeId;
        /** fromDocNo -> @GpSrNoF (optional; left out when empty) */
        public Integer fromDocNo;
        /** toDocNo -> @GpSrNoT (optional; left out when empty) */
        public Integer toDocNo;
        /** supplierCustomerId -> @SupplierCustomerId (optional; left out when empty) */
        public Integer supplierCustomerId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("id", id);
            m.put("documentTypeId", documentTypeId);
            m.put("fromDocNo", fromDocNo);
            m.put("toDocNo", toDocNo);
            m.put("supplierCustomerId", supplierCustomerId);
            return m;
        }
    }

    /**
     * 703-Print on sale/gdn_purchase_return.html
     * Template: 703_Gdn_PurchaseReturnSlip.rpt  (jasper/converted/703_Gdn_PurchaseReturnSlip.jrxml)
     * Procedure: [dbo].[USP_InvGdn_PurchaseReturnReport]
     * Desktop: InvGrnandGdnReports.InvGdn_PurchaseReturnReport
     */
    @RequestMapping(value = "/reports/print/703-gdn-purchase-return-slip", method = RequestMethod.POST)
    public void print703GdnPurchaseReturnSlip(HttpServletResponse response, @RequestBody(required = false) Rpt703GdnPurchaseReturnSlipRequest request) throws IOException {
        if (request == null) request = new Rpt703GdnPurchaseReturnSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "703_Gdn_PurchaseReturnSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/703-gdn-purchase-return-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt703GdnPurchaseReturnSlipRequest {
        /** fromDate -> @GrnDateF (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @GrnDateT (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** id -> @gdnId (required) */
        public Integer id;
        /** documentTypeId -> @DocumentTypeId (optional; left out when empty) */
        public Integer documentTypeId;
        /** fromDocNo -> @GpSrNoF (optional; left out when empty) */
        public Integer fromDocNo;
        /** toDocNo -> @GpSrNoT (optional; left out when empty) */
        public Integer toDocNo;
        /** supplierCustomerId -> @SupplierCustomerId (optional; left out when empty) */
        public Integer supplierCustomerId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("id", id);
            m.put("documentTypeId", documentTypeId);
            m.put("fromDocNo", fromDocNo);
            m.put("toDocNo", toDocNo);
            m.put("supplierCustomerId", supplierCustomerId);
            return m;
        }
    }

    /**
     * 703A-Print on sale/gdn_purchase_return.html
     * Template: 703A_Gdn_PurchaseReturnSlip.rpt  (jasper/converted/703A_Gdn_PurchaseReturnSlip.jrxml)
     * Procedure: [dbo].[USP_InvGdn_PurchaseReturnReport]
     * Desktop: InvGrnandGdnReports.InvGdn_PurchaseReturnReport
     */
    @RequestMapping(value = "/reports/print/703a-gdn-purchase-return-slip", method = RequestMethod.POST)
    public void print703AGdnPurchaseReturnSlip(HttpServletResponse response, @RequestBody(required = false) Rpt703AGdnPurchaseReturnSlipRequest request) throws IOException {
        if (request == null) request = new Rpt703AGdnPurchaseReturnSlipRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "703A_Gdn_PurchaseReturnSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/703a-gdn-purchase-return-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt703AGdnPurchaseReturnSlipRequest {
        /** fromDate -> @GrnDateF (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @GrnDateT (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** id -> @gdnId (required) */
        public Integer id;
        /** documentTypeId -> @DocumentTypeId (optional; left out when empty) */
        public Integer documentTypeId;
        /** fromDocNo -> @GpSrNoF (optional; left out when empty) */
        public Integer fromDocNo;
        /** toDocNo -> @GpSrNoT (optional; left out when empty) */
        public Integer toDocNo;
        /** supplierCustomerId -> @SupplierCustomerId (optional; left out when empty) */
        public Integer supplierCustomerId;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("id", id);
            m.put("documentTypeId", documentTypeId);
            m.put("fromDocNo", fromDocNo);
            m.put("toDocNo", toDocNo);
            m.put("supplierCustomerId", supplierCustomerId);
            return m;
        }
    }

    /**
     * 273-Print on sale/sale_order.html
     * Template: 273-InvRptSaleOrderSlip.rpt  (jasper/converted/273-InvRptSaleOrderSlip.jrxml)
     * Procedure: Sp_SaleOrder_RiceSlip_Rpt
     * Desktop: SaleOrderReports.SaleOrderReports273
     */
    @RequestMapping(value = "/reports/print/273-sale-order-slip", method = RequestMethod.POST)
    public void print273SaleOrderSlip(HttpServletResponse response, @RequestBody(required = false) Rpt273SaleOrderSlipRequest request) throws IOException {
        if (request == null) request = new Rpt273SaleOrderSlipRequest();
        reportPdfService.writePdf(response, "273-InvRptSaleOrderSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/273-sale-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt273SaleOrderSlipRequest {
        /** branchesId -> @BranchesId (optional; left out when empty) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional; left out when empty) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional; left out when empty) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional; left out when empty) */
        public Integer toDocNo;
        /** id -> @OrderId (optional; left out when empty) */
        public Integer id;
        /** supplierCustomerId -> @SupplierCustomerId (optional; left out when empty) */
        public Integer supplierCustomerId;
        /** documentTypeId -> @DocumentTypeId (optional; left out when empty) */
        public Integer documentTypeId;
        /** status -> @OrderStatus (optional; left out when empty) */
        public String status;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** isApproved -> @IsApproved (optional; left out when empty) */
        public Boolean isApproved;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("branchesId", branchesId);
            m.put("projectsId", projectsId);
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("fromDocNo", fromDocNo);
            m.put("toDocNo", toDocNo);
            m.put("id", id);
            m.put("supplierCustomerId", supplierCustomerId);
            m.put("documentTypeId", documentTypeId);
            m.put("status", status);
            m.put("itemId", itemId);
            m.put("isApproved", isApproved);
            return m;
        }
    }

    /**
     * 273_01-Print on sale/sale_order.html
     * Template: 273_01_SaleOrderSlip.rpt  (jasper/converted/273_01_SaleOrderSlip.jrxml)
     * Procedure: Sp_SaleOrder_RiceSlip_Rpt
     * Desktop: SaleOrderReports.SaleOrderReports273
     */
    @RequestMapping(value = "/reports/print/273-01-sale-order-slip", method = RequestMethod.POST)
    public void print27301SaleOrderSlip(HttpServletResponse response, @RequestBody(required = false) Rpt27301SaleOrderSlipRequest request) throws IOException {
        if (request == null) request = new Rpt27301SaleOrderSlipRequest();
        reportPdfService.writePdf(response, "273_01_SaleOrderSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/273-01-sale-order-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt27301SaleOrderSlipRequest {
        /** branchesId -> @BranchesId (optional; left out when empty) */
        public Integer branchesId;
        /** projectsId -> @ProjectsId (optional; left out when empty) */
        public Integer projectsId;
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional; left out when empty) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional; left out when empty) */
        public Integer toDocNo;
        /** id -> @OrderId (optional; left out when empty) */
        public Integer id;
        /** supplierCustomerId -> @SupplierCustomerId (optional; left out when empty) */
        public Integer supplierCustomerId;
        /** documentTypeId -> @DocumentTypeId (optional; left out when empty) */
        public Integer documentTypeId;
        /** status -> @OrderStatus (optional; left out when empty) */
        public String status;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** isApproved -> @IsApproved (optional; left out when empty) */
        public Boolean isApproved;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("branchesId", branchesId);
            m.put("projectsId", projectsId);
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("fromDocNo", fromDocNo);
            m.put("toDocNo", toDocNo);
            m.put("id", id);
            m.put("supplierCustomerId", supplierCustomerId);
            m.put("documentTypeId", documentTypeId);
            m.put("status", status);
            m.put("itemId", itemId);
            m.put("isApproved", isApproved);
            return m;
        }
    }

    /**
     * Print on sale/driver_bio.html
     * Template: 07_RptGatepassOutwardDriverInfoSlipA.rpt  (jasper/converted/07_RptGatepassOutwardDriverInfoSlipA.jrxml)
     * Procedure: Sp_GatePassOutwardDriverInfo_rpt
     * Desktop: GatePassOutwardDriverInfo.GatePassOutwardDriverInfoRpt
     */
    @RequestMapping(value = "/reports/print/07-gatepass-outward-driver-info-slip-a", method = RequestMethod.POST)
    public void print07GatepassOutwardDriverInfoSlipA(HttpServletResponse response, @RequestBody(required = false) Rpt07GatepassOutwardDriverInfoSlipARequest request) throws IOException {
        if (request == null) request = new Rpt07GatepassOutwardDriverInfoSlipARequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "07_RptGatepassOutwardDriverInfoSlipA.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/07-gatepass-outward-driver-info-slip-a */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt07GatepassOutwardDriverInfoSlipARequest {
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * Print on sale/outward_gate_pass.html
     * Template: 258-OutwardGatePassWithWbAndLabSlip.rpt  (jasper/converted/258-OutwardGatePassWithWbAndLabSlip.jrxml)
     * Procedure: Sp_GatePassOutward_SlipAndRegister_Rpt
     * Desktop: GatePassOutwardReports.GatePassOutwardSlipandRegister
     */
    @RequestMapping(value = "/reports/print/258-outward-gate-pass-with-wb-and-lab-slip", method = RequestMethod.POST)
    public void print258OutwardGatePassWithWbAndLabSlip(HttpServletResponse response, @RequestBody(required = false) Rpt258OutwardGatePassWithWbAndLabSlipRequest request) throws IOException {
        if (request == null) request = new Rpt258OutwardGatePassWithWbAndLabSlipRequest();
        reportPdfService.writePdf(response, "258-OutwardGatePassWithWbAndLabSlip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/258-outward-gate-pass-with-wb-and-lab-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt258OutwardGatePassWithWbAndLabSlipRequest {
        /** supplierCustomerId -> @SupplierCustomerId (optional; left out when empty) */
        public Integer supplierCustomerId;
        /** fromDate -> @FromDate (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @ToDate (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** fromDocNo -> @FromDocNo (optional; left out when empty) */
        public Integer fromDocNo;
        /** toDocNo -> @ToDocNo (optional; left out when empty) */
        public Integer toDocNo;
        /** id -> @Id (optional; left out when empty) */
        public Integer id;
        /** gatepassType -> @GatepassType (optional; left out when empty) */
        public String gatepassType;
        /** status -> @Status (optional; left out when empty) */
        public String status;
        /** branchesIds -> @BranchesIds (optional; left out when empty); comma separated */
        public String branchesIds;
        /** invoiceNo -> @InvoiceIds (optional; left out when empty) */
        public String invoiceNo;
        /** invoiceId -> @InvoiceId (optional; left out when empty) */
        public Integer invoiceId;
        /** pendingForView -> @OnlyPending (optional; left out when empty) */
        public String pendingForView;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("supplierCustomerId", supplierCustomerId);
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("fromDocNo", fromDocNo);
            m.put("toDocNo", toDocNo);
            m.put("id", id);
            m.put("gatepassType", gatepassType);
            m.put("status", status);
            m.put("branchesIds", branchesIds);
            m.put("invoiceNo", invoiceNo);
            m.put("invoiceId", invoiceId);
            m.put("pendingForView", pendingForView);
            return m;
        }
    }

    /**
     * 1856-SaleInvoiceDirect_Slip.rpt on sale/sale_invoice_direct.html
     * Template: 1856-SaleInvoiceDirect_Slip.rpt  (jasper/converted/1856-SaleInvoiceDirect_Slip.jrxml)
     * Procedure: pcc.USP_InvSaleInvoice_DirectSlip
     * Desktop: InvSaleInvoice.SaleInvoiceDirectSlip
     */
    @RequestMapping(value = "/reports/print/1856-sale-invoice-direct-slip", method = RequestMethod.POST)
    public void print1856SaleInvoiceDirectSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1856SaleInvoiceDirectSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1856SaleInvoiceDirectSlipRequest();
        reportPdfService.writePdf(response, "1856-SaleInvoiceDirect_Slip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1856-sale-invoice-direct-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1856SaleInvoiceDirectSlipRequest {
        /** id -> @Id (optional; left out when empty) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }

    /**
     * 1862-SaleInvoiceRetrurn_Slip.rpt on sale/sale_invoice_return.html
     * Template: 1862-SaleInvoiceRetrurn_Slip.rpt  (jasper/converted/1862-SaleInvoiceRetrurn_Slip.jrxml)
     * Procedure: pcc.USP_InvSaleInvoice_DirectSlip
     * Desktop: InvSaleInvoice.SaleInvoiceDirectSlip
     */
    @RequestMapping(value = "/reports/print/1862-sale-invoice-retrurn-slip", method = RequestMethod.POST)
    public void print1862SaleInvoiceRetrurnSlip(HttpServletResponse response, @RequestBody(required = false) Rpt1862SaleInvoiceRetrurnSlipRequest request) throws IOException {
        if (request == null) request = new Rpt1862SaleInvoiceRetrurnSlipRequest();
        reportPdfService.writePdf(response, "1862-SaleInvoiceRetrurn_Slip.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/1862-sale-invoice-retrurn-slip */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt1862SaleInvoiceRetrurnSlipRequest {
        /** id -> @Id (optional; left out when empty) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", id);
            return m;
        }
    }
}
