package com.mst.reports.prints;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Print buttons of the stocks screens: one endpoint per desktop report, each returning the PDF.
 * Body = the report's arguments exactly as its contract (seeder / BLL trace) names them;
 * OrganizationId and CompanyId are taken from the session, never from the body.
 * GENERATED by migration/rpt-to-jasper/gen_print_endpoints.py - re-run it rather than editing by hand.
 */
@RestController
public class StocksPrintController {

    private final ReportPdfService reportPdfService;

    public StocksPrintController(ReportPdfService reportPdfService) {
        this.reportPdfService = reportPdfService;
    }

    /**
     * 416-Print on stocks/opening_stock.html, stocks/stock_opening_form.html, store/opening_stock_store.html
     * Template: 416-InvStockOpeningBalanceHeader_Register.rpt  (jasper/converted/416-InvStockOpeningBalanceHeader_Register.jrxml)
     * Procedure: Sp_InvStockOpeningBalanceHeader_RegisterRpt
     * Desktop: GeneralReprots.StockopeningBalanceRegister
     */
    @RequestMapping(value = "/reports/print/416-inv-stock-opening-balance-header-register", method = RequestMethod.POST)
    public void print416InvStockOpeningBalanceHeaderRegister(HttpServletResponse response, @RequestBody(required = false) Rpt416InvStockOpeningBalanceHeaderRegisterRequest request) throws IOException {
        if (request == null) request = new Rpt416InvStockOpeningBalanceHeaderRegisterRequest();
        try { ReportPdfService.require(request.id, "id"); }
        catch (IllegalArgumentException e) { response.sendError(400, e.getMessage()); return; }
        reportPdfService.writePdf(response, "416-InvStockOpeningBalanceHeader_Register.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/416-inv-stock-opening-balance-header-register */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt416InvStockOpeningBalanceHeaderRegisterRequest {
        /** documentTypeId -> @DocumentTypeIds (required) */
        public Integer documentTypeId;
        /** id -> @Id (required) */
        public Integer id;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("documentTypeId", documentTypeId);
            m.put("id", id);
            return m;
        }
    }

    /**
     * Print on stocks/store_stock_report.html
     * Template: 202_ItemStockSummary.rpt  (jasper/converted/202_ItemStockSummary.jrxml)
     * Procedure: Sp_ItemStockReportWithValues_Store
     * Desktop: StocksReport.ItemStockReportWithValues_Store
     */
    @RequestMapping(value = "/reports/print/202-item-stock-summary", method = RequestMethod.POST)
    public void print202ItemStockSummary(HttpServletResponse response, @RequestBody(required = false) Rpt202ItemStockSummaryRequest request) throws IOException {
        if (request == null) request = new Rpt202ItemStockSummaryRequest();
        reportPdfService.writePdf(response, "202_ItemStockSummary.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/202-item-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt202ItemStockSummaryRequest {
        /** fromDate -> @DateFrom (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional; left out when empty) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional; left out when empty) */
        public Integer itemCategoryId;
        /** warehouseId -> @WarehouseId (optional; left out when empty) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional; left out when empty) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional; left out when empty) */
        public String purchaseGLAC;
        /** rateUOM -> @IsPackTypeOn (optional; left out when empty) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional; left out when empty) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional; left out when empty) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional; left out when empty); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional; left out when empty) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional; left out when empty) */
        public String zeroBalanceType;
        /** stockPartyId -> @StockPartyId (optional; left out when empty) */
        public Integer stockPartyId;
        /** itemConditionId -> @ItemConditionId (optional; left out when empty) */
        public Integer itemConditionId;
        /** branchesIds -> @BranchesIds (optional; left out when empty); comma separated */
        public String branchesIds;
        /** storeRackId -> @RackId (optional; left out when empty) */
        public Integer storeRackId;
        /** activity -> @Activity (required) */
        public String activity;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("itemTypeId", itemTypeId);
            m.put("itemCategoryId", itemCategoryId);
            m.put("warehouseId", warehouseId);
            m.put("itemId", itemId);
            m.put("stockUOM", stockUOM);
            m.put("purchaseGLAC", purchaseGLAC);
            m.put("rateUOM", rateUOM);
            m.put("itemClassGroupId", itemClassGroupId);
            m.put("inventoryParentCategories", inventoryParentCategories);
            m.put("ids", ids);
            m.put("actionId", actionId);
            m.put("zeroBalanceType", zeroBalanceType);
            m.put("stockPartyId", stockPartyId);
            m.put("itemConditionId", itemConditionId);
            m.put("branchesIds", branchesIds);
            m.put("storeRackId", storeRackId);
            m.put("activity", activity);
            return m;
        }
    }

    /**
     * 202_02_ItemandWarehouseStockSummary on stocks/store_stock_report.html
     * Template: 202_02_ItemandWarehouseStockSummary.rpt  (jasper/converted/202_02_ItemandWarehouseStockSummary.jrxml)
     * Procedure: Sp_ItemStockReportWithValues_Store
     * Desktop: StocksReport.ItemStockReportWithValues_Store
     */
    @RequestMapping(value = "/reports/print/202-02-itemand-warehouse-stock-summary", method = RequestMethod.POST)
    public void print20202ItemandWarehouseStockSummary(HttpServletResponse response, @RequestBody(required = false) Rpt20202ItemandWarehouseStockSummaryRequest request) throws IOException {
        if (request == null) request = new Rpt20202ItemandWarehouseStockSummaryRequest();
        reportPdfService.writePdf(response, "202_02_ItemandWarehouseStockSummary.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/202-02-itemand-warehouse-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt20202ItemandWarehouseStockSummaryRequest {
        /** fromDate -> @DateFrom (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional; left out when empty) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional; left out when empty) */
        public Integer itemCategoryId;
        /** warehouseId -> @WarehouseId (optional; left out when empty) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional; left out when empty) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional; left out when empty) */
        public String purchaseGLAC;
        /** rateUOM -> @IsPackTypeOn (optional; left out when empty) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional; left out when empty) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional; left out when empty) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional; left out when empty); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional; left out when empty) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional; left out when empty) */
        public String zeroBalanceType;
        /** stockPartyId -> @StockPartyId (optional; left out when empty) */
        public Integer stockPartyId;
        /** itemConditionId -> @ItemConditionId (optional; left out when empty) */
        public Integer itemConditionId;
        /** branchesIds -> @BranchesIds (optional; left out when empty); comma separated */
        public String branchesIds;
        /** storeRackId -> @RackId (optional; left out when empty) */
        public Integer storeRackId;
        /** activity -> @Activity (required) */
        public String activity;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("itemTypeId", itemTypeId);
            m.put("itemCategoryId", itemCategoryId);
            m.put("warehouseId", warehouseId);
            m.put("itemId", itemId);
            m.put("stockUOM", stockUOM);
            m.put("purchaseGLAC", purchaseGLAC);
            m.put("rateUOM", rateUOM);
            m.put("itemClassGroupId", itemClassGroupId);
            m.put("inventoryParentCategories", inventoryParentCategories);
            m.put("ids", ids);
            m.put("actionId", actionId);
            m.put("zeroBalanceType", zeroBalanceType);
            m.put("stockPartyId", stockPartyId);
            m.put("itemConditionId", itemConditionId);
            m.put("branchesIds", branchesIds);
            m.put("storeRackId", storeRackId);
            m.put("activity", activity);
            return m;
        }
    }

    /**
     * 202_03_ItemandPackSizeStockSummary on stocks/store_stock_report.html
     * Template: 202_03_ItemandPackSizeStockSummary.rpt  (jasper/converted/202_03_ItemandPackSizeStockSummary.jrxml)
     * Procedure: Sp_ItemStockReportWithValues_Store
     * Desktop: StocksReport.ItemStockReportWithValues_Store
     */
    @RequestMapping(value = "/reports/print/202-03-itemand-pack-size-stock-summary", method = RequestMethod.POST)
    public void print20203ItemandPackSizeStockSummary(HttpServletResponse response, @RequestBody(required = false) Rpt20203ItemandPackSizeStockSummaryRequest request) throws IOException {
        if (request == null) request = new Rpt20203ItemandPackSizeStockSummaryRequest();
        reportPdfService.writePdf(response, "202_03_ItemandPackSizeStockSummary.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/202-03-itemand-pack-size-stock-summary */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt20203ItemandPackSizeStockSummaryRequest {
        /** fromDate -> @DateFrom (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** itemTypeId -> @ItemTypeId (optional; left out when empty) */
        public Integer itemTypeId;
        /** itemCategoryId -> @ItemCategoryId (optional; left out when empty) */
        public Integer itemCategoryId;
        /** warehouseId -> @WarehouseId (optional; left out when empty) */
        public Integer warehouseId;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** stockUOM -> @IsPackSizeOn (optional; left out when empty) */
        public String stockUOM;
        /** purchaseGLAC -> @ItemStockAc (optional; left out when empty) */
        public String purchaseGLAC;
        /** rateUOM -> @IsPackTypeOn (optional; left out when empty) */
        public String rateUOM;
        /** itemClassGroupId -> @ItemClassGroupId (optional; left out when empty) */
        public Integer itemClassGroupId;
        /** inventoryParentCategories -> @InventoryParentCategoriesId (optional; left out when empty) */
        public String inventoryParentCategories;
        /** ids -> @InventoryParentCategoriesIds (optional; left out when empty); comma separated */
        public String ids;
        /** actionId -> @SaleValue (optional; left out when empty) */
        public Integer actionId;
        /** zeroBalanceType -> @SkipZero (optional; left out when empty) */
        public String zeroBalanceType;
        /** stockPartyId -> @StockPartyId (optional; left out when empty) */
        public Integer stockPartyId;
        /** itemConditionId -> @ItemConditionId (optional; left out when empty) */
        public Integer itemConditionId;
        /** branchesIds -> @BranchesIds (optional; left out when empty); comma separated */
        public String branchesIds;
        /** storeRackId -> @RackId (optional; left out when empty) */
        public Integer storeRackId;
        /** activity -> @Activity (required) */
        public String activity;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("itemTypeId", itemTypeId);
            m.put("itemCategoryId", itemCategoryId);
            m.put("warehouseId", warehouseId);
            m.put("itemId", itemId);
            m.put("stockUOM", stockUOM);
            m.put("purchaseGLAC", purchaseGLAC);
            m.put("rateUOM", rateUOM);
            m.put("itemClassGroupId", itemClassGroupId);
            m.put("inventoryParentCategories", inventoryParentCategories);
            m.put("ids", ids);
            m.put("actionId", actionId);
            m.put("zeroBalanceType", zeroBalanceType);
            m.put("stockPartyId", stockPartyId);
            m.put("itemConditionId", itemConditionId);
            m.put("branchesIds", branchesIds);
            m.put("storeRackId", storeRackId);
            m.put("activity", activity);
            return m;
        }
    }

    /**
     * 621 -Register on stocks/transaction_vehicle_wise.html
     * Template: 621-StockEvalautionDetailTransactionVehiclesWise.rpt  (jasper/converted/621-StockEvalautionDetailTransactionVehiclesWise.jrxml)
     * Procedure: USP_GetStockEvalautionDetailByRefRefIds
     * Desktop: InventoryStockEvalautionDetail.GetStockEvalautionDetailByRefIds
     */
    @RequestMapping(value = "/reports/print/621-stock-evalaution-detail-transaction-vehicles-wise", method = RequestMethod.POST)
    public void print621StockEvalautionDetailTransactionVehiclesWise(HttpServletResponse response, @RequestBody(required = false) Rpt621StockEvalautionDetailTransactionVehiclesWiseRequest request) throws IOException {
        if (request == null) request = new Rpt621StockEvalautionDetailTransactionVehiclesWiseRequest();
        reportPdfService.writePdf(response, "621-StockEvalautionDetailTransactionVehiclesWise.rpt", request.toArgs());
    }

    /** Body of POST /reports/print/621-stock-evalaution-detail-transaction-vehicles-wise */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rpt621StockEvalautionDetailTransactionVehiclesWiseRequest {
        /** fromDate -> @DateFrom (optional; left out when empty); yyyy-MM-dd */
        public String fromDate;
        /** toDate -> @DateTo (optional; left out when empty); yyyy-MM-dd */
        public String toDate;
        /** inventoryParentCategories -> @InventoryParentCategories (optional; left out when empty) */
        public String inventoryParentCategories;
        /** itemId -> @ItemId (optional; left out when empty) */
        public Integer itemId;
        /** supplierCustomerId -> @SupplierCustomerId (optional; left out when empty) */
        public Integer supplierCustomerId;
        /** warehouseId -> @WarehouseId (optional; left out when empty) */
        public Integer warehouseId;
        /** jobLotId -> @JobLotId (optional; left out when empty) */
        public Integer jobLotId;
        /** cropYear -> @CropYear (optional; left out when empty) */
        public String cropYear;
        /** refDocumentTypeId -> @ReferenceDocumentTypeId (optional; left out when empty) */
        public Integer refDocumentTypeId;
        /** packingTypeId -> @PackingTypeId (optional; left out when empty) */
        public Integer packingTypeId;
        /** stockUOM -> @ItemUomId (optional; left out when empty) */
        public String stockUOM;

        Map<String, Object> toArgs() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("fromDate", fromDate);
            m.put("toDate", toDate);
            m.put("inventoryParentCategories", inventoryParentCategories);
            m.put("itemId", itemId);
            m.put("supplierCustomerId", supplierCustomerId);
            m.put("warehouseId", warehouseId);
            m.put("jobLotId", jobLotId);
            m.put("cropYear", cropYear);
            m.put("refDocumentTypeId", refDocumentTypeId);
            m.put("packingTypeId", packingTypeId);
            m.put("stockUOM", stockUOM);
            return m;
        }
    }
}
