package com.mst.security;

import java.util.Set;

/**
 * Every authority string fixed_sidebar.html gates a menu item or section on
 * (th:if="${#authorization.expression('hasAuthority(''X'')')}"), captured verbatim
 * from that template. An ADMIN-role user is granted every one of these (see
 * CustomUserDetailsService) so the full desktop-equivalent menu renders for admins
 * even though most of these screens aren't ported yet; a non-admin user instead only
 * gets the specific authorities tied to Screens they've been granted VIEW rights to
 * (see UserRight / ScreenSeeder) - which today is a subset of this list.
 */
public final class SidebarAuthorities {

	private SidebarAuthorities() {
	}

	public static final Set<String> ALL = Set.of(
			"ACCOUNTS", "ACCOUNTS_TRANSACTION", "ACCOUNT_CUSTOM_GROUP", "ACCOUNT_HIST", "ACCOUNT_OPENING_BALANCE",
			"ADD_MILL_RATE", "ADD_NEW_BRANCH", "ADD_NEW_COMPANY", "ADD_NEW_USER", "ADMIN",
			"BALANCE_SHEET", "CHART_OF_ACCOUNT", "CHEQUES_IN_HAND", "CHEQUE_BOOK_REGISTRATION",
			"CLOSING_VOUCHER", "COMBINE_VOUCHER", "COMBINE_VOUCHER_REPORT", "CONTACT_LIST",
			"CUSTOMER_STATUS_REPORT", "DAILY_CLOSING", "DAILY_SUMMARY_REPORT", "DATA_COLLECTION",
			"DAY_PAYMENT_ENTRY", "DEFINE_SUPPLIER", "DETAIL_GENERAL_LEDGER", "GENERAL_LEDGER",
			"INFO", "INVENTORY",
			"LAB", "LAB_ITEM_ANALYSIS_PARAMETER", "LAB_SAMPLE_LOG_REGISTER", "LAB_ANALYSIS_GROUP", "LAB_GROUP_ANALYSIS_STANDARDS", "LAB_SAMPLE_ANALYSIS", "LAB_PURCHASE_ANALYSIS", "LAB_SALE_ANALYSIS", "LAB_INPROCESS_ANALYSIS", "LAB_INPROCESS_ANALYSIS_STEPS", "LAB_QC_DEDUCTION_POLICY", "LAB_STANDARD_POLICY_FOR_DEDUCTION", "LAB_EXPORT_PRE_SHIPMENT_ANALYSIS", "LAB_VCI_PARAMETER", "LAB_RPT_PURCHASE_ANALYSIS_BY_VEHICLE", "LAB_RPT_LAB_PURCHASE_REPORT", "LAB_RPT_LAB_SALE_REGISTER", "LAB_RPT_LAB_SAMPLE_ANALYSIS", "LAB_RPT_PURCHASE_ANALYSIS_PERIODIC", "LAB_RPT_INPROCESS_ANALYSIS", "LAB_RPT_SAMPLE_ANALYSIS_REGISTER", "LAB_RPT_PURCHASE_ANALYSIS_REGISTER",
			"INVENTORY_BRANDS", "INVENTORY_COSTING", "INVENTORY_ITEM_CATEGORIES",
			"INVENTORY_ITEM_GROUPS", "INVENTORY_ITEM_TYPES", "INVENTORY_ITEMS",
			"INVENTORY_PRODUCT_TYPES", "INVENTORY_RACKS", "INVENTORY_WAREHOUSES", "ITEM_RECIPE",
			"MILL_RATE_VIEW", "NEW_ACCOUNT", "NEW_CITY", "NEW_CONTACT", "NEW_MILL",
			"NEW_PURCHASE_VOUCHER", "NEW_SALE_VOUCHER", "PAYABLES", "PAYMENT_SCHEDULE_REPORT",
			"PAY_PAYMENT_VIEW", "PRE_PURCHASE_ENTRY", "PRE_PURCHASE_REPORT", "PRINT_CHECK",
			"PACKING_MATERIAL", "PM_ITEM", "PM_PURCHASE_ORDER", "PM_GRN", "PM_PURCHASE_INVOICE", "PM_PURCHASE_INVOICE_DIRECT", "PM_STORE_SEND_RECEIPT", "PM_STOCK_TRANSFER_STORE", "PM_STOCK_ADJUSTMENT", "PM_STORE_STOCK_CONVERSION", "PM_DELIVERY_ORDER", "PM_SALE_INVOICE_DIRECT", "PRODUCTION_FORM", "PRODUCTION", "PRODUCTION_JOB_ORDER", "PRODUCTION_STOCK_CONVERSION", "PRODUCTION_DEFINE_TYPE", "PRODUCTION_DEFINE_PLAN_TYPE", "PRODUCTION_DEFINE_PLANT", "EXPORT", "EXP_GD_BREAK_UP_BY_INVOICE", "EXP_INVOICE_PACKING_LIST", "EXP_EXPORT_OPENING", "EXP_RETURN_GRN", "EXP_RETURN_INVOICE", "EXP_PERFORMA_INVOICE", "EXP_DELIVERY_ORDER_NEW", "EXP_COMMERCIAL_INVOICE_TRANSFER", "EXP_PRE_SHIPMENT_ANALYSIS", "EXP_DEFINE_DOCUMENTS", "EXP_CONTRACT_SCHEDULE_PERIODIC_A", "EXP_COMPARISON_SUMMARY", "EXP_INVOICE_AGAINST_FORWARDING_PRE_INVOICES", "EXP_BILL_OF_LADING_REPORT", "EXP_CONTAINER_LIST", "EXP_PRE_INVOICE_REGISTER", "EXP_BANK_GD_SUMMARY", "EXP_SALES_CONTRACT", "EXP_CONTRACT_III", "EXP_CONTRACT_SCHEDULE", "EXP_PACKING_DETAIL_BY_CONTRACT", "EXP_COMMERCIAL_INVOICE", "EXP_COMMERCIAL_INVOICE_III", "EXP_PRE_INVOICE", "EXP_PACKING_DETAIL", "EXP_OPENING_BALANCE", "EXP_PROFORMA_INVOICE", "EXP_FORWARDING", "EXP_FORWARDING_NEW", "EXP_DELIVERY_ORDER", "EXP_FORWARDING_DIRECT", "EXP_FORWARDING_WITHOUT_WEIGHBRIDGE", "EXP_LC_ORDER", "EXP_EFORM_REGISTRATION", "EXP_FINANCIAL_INSTRUMENT", "EXP_PACKING_MATERIAL_REQUIREMENT", "EXP_THIRD_PARTY_INSPECTION", "EXP_LAB_AGAINST_THIRD_PARTY_INSPECTION", "EXP_FCY_RECEIPTS", "EXP_RECEIVABLE_BY_DUE_DATE", "EXP_CONTRACT_SCHEDULE_PERIODIC", "EXP_SHIPMENT_COSTING", "EXP_SHIPMENTS_DOCUMENT_STATUS", "EXP_DETAIL_HISTORY", "EXP_DELIVERY_ORDER_REPORT", "EXP_CONTRACT_REGISTER", "EXP_SHIPMENT_TRACKING_FOLLOW_UP", "EXP_SHIPMENT_WEIGHT_AUDIT", "EXP_LOADING_SHEET", "EXP_SHIPMENT_CRO_BOOKING_REPORT", "EXP_FORWARDING_REPORT", "EXP_SALE_REPORT", "EXP_SALE_COMPARISONS_REPORT", "EXP_SERVICE_BILL_REGISTER", "EXP_FORWARDING_COSTING_REPORT", "EXP_SHIPMENT_COSTING_SUMMARY", "EXP_FI_UTILIZATION_REPORT", "EXP_FCY_RECEIPTS_SUMMARY_REGISTER", "EXP_SHIPMENT_DATA_FOR_BROKERY_TAX", "EXP_PACKING_LIST_REGISTER", "EXP_PENDING_FORWARDING_FOR_COMMERCIAL_INVOICE", "EXP_GD_BREAK_UP_AND_REALIZED_REGISTER", "EXP_FI_BALANCE_SUMMARY", "EXP_COMMISSION_AGENT_FCY_LEDGER", "EXP_EE_REPORT_EXPORT_GD", "EXP_COMMERCIAL_INVOICE_SHIPMENTS", "EXP_CONSIGNMENT_FOLLOW_UP", "EXP_THIRD_PARTY_INSPECTION_LOT_TRACKING_REPORT", "EXP_DOC_DUE_COLOR_SCHEDULE", "EXP_DEFINE_CHART_OF_DOCUMENT", "EXP_DEFINE_CUSTOM_GROUP", "EXP_CLIENT_ASSIGN_TO_GROUP", "EXP_DOCUMENT_ASSIGN_TO_GROUP", "EXP_SHIPMENT_DOC_SCHEDULE", "EXP_DOCUMENT_TRACKING_REPORT", "EXP_CUSTOM_INVOICE", "EXP_GD_BANK_INVOICE_MAPPING", "EXP_FCY_RECEIPT_GD_UTILIZATION", "EXP_GD_BANK_REQUEST", "EXP_GD_BREAK_UP_MANUAL", "EXP_PARTIES_DEFINE", "EXP_BILL_OF_LADING", "EXP_SHIPPING_BOOKING_INFO", "EXP_CONTAINER_INSPECTION", "EXP_PRE_SHIPMENT_INSPECTION", "EXP_MULTI_INVOICES_ALLOCATE_TO_GDN", "EXP_ADVANCE_UTILIZE_AGAINST_INVOICE", "MASTER_DATA_DEFINITION", "MDD_COUNTRY", "MDD_CITY", "MDD_CURRENCY", "MDD_SEA_PORTS", "MDD_PROVINCE", "MDD_DATE_LOCK", "MDD_TEHSIL", "MDD_DISTRICT", "MDD_OTHER_ITEMS", "MDD_BANK", "MDD_BSPL_SETTING", "MDD_PDC_BANK", "MDD_TAX_LOOKUP", "MDD_DOCUMENT_GROUP", "MDD_SHIPMENT_DOCUMENTS", "PROFIT", "PROFIT_LOSS", "PURCHASE_ORDER", "PURCHASE_ORDER_LIST",
			"PURCHASE_REPORT", "PURCHASE_VOUCHER_LIST", "QTY", "RATE_ENTRY", "RECIPE_VOUCHER_FORM",
			"REPORTS", "SALE", "SALE_INVOICE_VOUCHER", "SALE_ORDER", "SALE_ORDER_LIST", "SALE_REPORT",
			"SALE_VOUCHER_LIST", "SEND_ACCOUNT_HISTORY", "SEND_BANK_ACCOUNT", "SEND_OR_CREATE_BANK_ACCOUNT",
			"STOCK_LEDGER", "STORE_MANAGEMENT", "STORE_ISSUANCE", "STORE_ISSUANCE_DIRECT", "STORE_RETURN", "STORE_DEPARTMENT_REQUEST", "STORE_STOCK_ADJUSTMENT", "STORE_STOCK_TRANSFER", "STORE_PURCHASE_DEMAND", "STORE_GRN_STORE", "STORE_PURCHASE_INVOICE_DIRECT", "STORE_PURCHASE_INVOICE_RETURN_STORE", "STORE_PURCHASE_INVOICE_STORE_MANAGEMENT", "STORE_PURCHASE_PRE_BILL", "STORE_DELIVERY_CHALLAN_PREBILL", "STORE_STOCK_TRANSFER_MANUAL", "STORE_DELIVERY_ORDER_TRANSFER", "STORE_ITEM", "STORE_ITEM_CATEGORY_STORE", "STORE_ITEM_TYPE_STORE", "STORE_OPENING_STOCK_STORE", "STORE_PARTY_TO_PARTY_PM_TRANSFER", "STORE_ISSUANCE_TO_CONSUMABLE_STORE", "STORE_DEPARTMENT_REQUEST_TO_CONSUMABLE", "STORE_RPT_STORE_PURCHASE_REGISTER", "STORE_RPT_STORE_PURCHASE_DEMAND_REGISTER", "STORE_RPT_STORE_ISSUANCE_RETURN_REGISTER", "STORE_RPT_STOCK_ADJUSTMENT_REGISTER", "STORE_RPT_DEPARTMENT_REQUEST_HISTORY", "STORE_RPT_STOCK_TRANSFER_REGISTER", "STORE_RPT_STORE_ISSUANCE_HISTORY", "STORE_RPT_GENERAL_GATE_PASS", "STOCK_OPENING_FORM", "STOCK_REPORT_QUANTITY", "SUPPLIER_STATUS_REPORT",
			"THIRD_PARTY", "TRADING_REPORT", "TRIAL_BALANCE", "UPDATE_ACCOUNT", "UTILITIES",
			"USER_ROLES", "USER_RIGHTS", "VOUCHER_CASH_PAYMENT", "VOUCHER_BANK_PAYMENT", "VOUCHER_CASH_RECEIPT", "VOUCHER_BANK_RECEIPT", "VOUCHER_JOURNAL", "VOUCHER_CONTRA", "VOUCHER_EXPENSE", "VOUCHER_PARTY_RECEIPT", "VOUCHER_PARTY_PAYMENT", "VOUCHERS", "VOUCHER_ALL", "VOUCHER_BPV_BRV_JV_OJV",
			"VOUCHER_CPV_CRV_JV", "VOUCHER_LIST", "WEIGHT");
}
