package com.mst.security;

import java.util.Set;

/**
 * Every authority string fixed_sidebar.html gates a menu item or section on
 * (th:if="${#authorization.expression('hasAuthority(''X'')')}"), captured verbatim
 * from that template. An ADMIN-role user is granted every one of these (see
 * CustomUserDetailsService) so the full desktop-equivalent menu renders for admins
 * even though most of these screens aren't ported yet; a non-admin user instead only
 * gets the specific authorities tied to Screens they've been granted VIEW rights to
 * (see UserRight / ScreenSeeder) - which today is a subset of this list.
 */
public final class SidebarAuthorities {

	private SidebarAuthorities() {
	}

	public static final Set<String> ALL = Set.of(
			"ACCOUNTS", "ACCOUNTS_TRANSACTION", "ACCOUNT_CUSTOM_GROUP", "ACCOUNT_HIST", "ACCOUNT_OPENING_BALANCE",
			"ADD_MILL_RATE", "ADD_NEW_BRANCH", "ADD_NEW_COMPANY", "ADD_NEW_USER", "ADMIN",
			"BALANCE_SHEET", "CHART_OF_ACCOUNT", "CHEQUES_IN_HAND", "CHEQUE_BOOK_REGISTRATION",
			"CLOSING_VOUCHER", "COMBINE_VOUCHER", "COMBINE_VOUCHER_REPORT", "CONTACT_LIST",
			"CUSTOMER_STATUS_REPORT", "DAILY_CLOSING", "DAILY_SUMMARY_REPORT", "DATA_COLLECTION",
			"DAY_PAYMENT_ENTRY", "DEFINE_SUPPLIER", "DETAIL_GENERAL_LEDGER", "GENERAL_LEDGER",
			"INFO", "INVENTORY",
			"LAB", "LAB_ITEM_ANALYSIS_PARAMETER", "INVENTORY_BRANDS", "INVENTORY_COSTING", "INVENTORY_ITEM_CATEGORIES",
			"INVENTORY_ITEM_GROUPS", "INVENTORY_ITEM_TYPES", "INVENTORY_ITEMS",
			"INVENTORY_PRODUCT_TYPES", "INVENTORY_RACKS", "INVENTORY_WAREHOUSES", "ITEM_RECIPE",
			"MILL_RATE_VIEW", "NEW_ACCOUNT", "NEW_CITY", "NEW_CONTACT", "NEW_MILL",
			"NEW_PURCHASE_VOUCHER", "NEW_SALE_VOUCHER", "PAYABLES", "PAYMENT_SCHEDULE_REPORT",
			"PAY_PAYMENT_VIEW", "PRE_PURCHASE_ENTRY", "PRE_PURCHASE_REPORT", "PRINT_CHECK",
			"PACKING_MATERIAL", "PM_ITEM", "PM_PURCHASE_ORDER", "PM_GRN", "PM_PURCHASE_INVOICE", "PM_PURCHASE_INVOICE_DIRECT", "PM_STORE_SEND_RECEIPT", "PM_STOCK_TRANSFER_STORE", "PM_STOCK_ADJUSTMENT", "PM_STORE_STOCK_CONVERSION", "PM_DELIVERY_ORDER", "PRODUCTION_FORM", "PRODUCTION", "PRODUCTION_JOB_ORDER", "PRODUCTION_STOCK_CONVERSION", "PROFIT", "PROFIT_LOSS", "PURCHASE_ORDER", "PURCHASE_ORDER_LIST",
			"PURCHASE_REPORT", "PURCHASE_VOUCHER_LIST", "QTY", "RATE_ENTRY", "RECIPE_VOUCHER_FORM",
			"REPORTS", "SALE", "SALE_INVOICE_VOUCHER", "SALE_ORDER", "SALE_ORDER_LIST", "SALE_REPORT",
			"SALE_VOUCHER_LIST", "SEND_ACCOUNT_HISTORY", "SEND_BANK_ACCOUNT", "SEND_OR_CREATE_BANK_ACCOUNT",
			"STOCK_LEDGER", "STORE_MANAGEMENT", "STORE_ISSUANCE", "STORE_ISSUANCE_DIRECT", "STORE_RETURN", "STORE_DEPARTMENT_REQUEST", "STORE_STOCK_ADJUSTMENT", "STORE_STOCK_TRANSFER", "STORE_PURCHASE_DEMAND", "STORE_GRN_STORE", "STORE_PURCHASE_INVOICE_DIRECT", "STORE_PURCHASE_INVOICE_RETURN_STORE", "STORE_PURCHASE_INVOICE_STORE_MANAGEMENT", "STORE_PURCHASE_PRE_BILL", "STORE_DELIVERY_CHALLAN_PREBILL", "STORE_STOCK_TRANSFER_MANUAL", "STORE_DELIVERY_ORDER_TRANSFER", "STORE_ITEM", "STORE_ITEM_CATEGORY_STORE", "STORE_ITEM_TYPE_STORE", "STORE_OPENING_STOCK_STORE", "STORE_PARTY_TO_PARTY_PM_TRANSFER", "STORE_ISSUANCE_TO_CONSUMABLE_STORE", "STORE_DEPARTMENT_REQUEST_TO_CONSUMABLE", "STORE_RPT_STORE_PURCHASE_REGISTER", "STORE_RPT_STORE_PURCHASE_DEMAND_REGISTER", "STORE_RPT_STORE_ISSUANCE_RETURN_REGISTER", "STORE_RPT_STOCK_ADJUSTMENT_REGISTER", "STORE_RPT_DEPARTMENT_REQUEST_HISTORY", "STORE_RPT_STOCK_TRANSFER_REGISTER", "STORE_RPT_STORE_ISSUANCE_HISTORY", "STORE_RPT_GENERAL_GATE_PASS", "STOCK_OPENING_FORM", "STOCK_REPORT_QUANTITY", "SUPPLIER_STATUS_REPORT",
			"THIRD_PARTY", "TRADING_REPORT", "TRIAL_BALANCE", "UPDATE_ACCOUNT", "UTILITIES",
			"USER_ROLES", "USER_RIGHTS", "VOUCHER_CASH_PAYMENT", "VOUCHER_BANK_PAYMENT", "VOUCHER_CASH_RECEIPT", "VOUCHER_BANK_RECEIPT", "VOUCHER_JOURNAL", "VOUCHER_CONTRA", "VOUCHER_EXPENSE", "VOUCHER_PARTY_RECEIPT", "VOUCHER_PARTY_PAYMENT", "VOUCHERS", "VOUCHER_ALL", "VOUCHER_BPV_BRV_JV_OJV",
			"VOUCHER_CPV_CRV_JV", "VOUCHER_LIST", "WEIGHT");
}
