package com.mst.models.logistics;

import com.mst.models.hrm.DesktopModel;

import java.time.LocalDateTime;

/** Generated from 1044_Architecture.Model.Inventory.Item.cs - every non-virtual property, as GenericProvider.SetProc binds it. */
public class LgsAItem extends DesktopModel {
    public boolean ApplyExciese;
    public boolean ApplyGST;
    public boolean ApplyVAT;
    public boolean ItemStatus;
    public boolean OtherTax;
    public boolean PostState;
    public boolean IsCompany;
    public boolean IsThirdParty;
    public LocalDateTime EntryDate;
    public LocalDateTime ModifyDate;
    public LocalDateTime PostDate;
    public double CostPrice;
    public double MaxStockLevel;
    public double OptimalStockLevel;
    public double MinStockLevel;
    public double PackQty;
    public double PurchasePrice;
    public double ReorderLevel;
    public double ReOrderQty;
    public double RetailPrice;
    public double WholeSalePrice;
    public double EmptyBagWeight;
    public java.math.BigDecimal WeightKgs = java.math.BigDecimal.ZERO;
    public java.math.BigDecimal MaxMeaurement = java.math.BigDecimal.ZERO;
    public int LeadTimeDay;
    public double PackSize;
    public int PackSizeId;
    public boolean AllowMultiUom;
    public int CropYearId;
    public int BaseUnitId;
    public int BranchesId;
    public int BuyerSupplierId;
    public int COGSGLAC;
    public int CompanyId;
    public int EntryUser;
    public int ServicesMasterItemId;
    public int Id;
    public int ItemCategoryId;
    public int ItemClassId;
    public int ItemTypeId;
    public int ManufactureId;
    public int ModifyUser;
    public int OrganizationId;
    public int PostUser;
    public int ProjectsId;
    public int PurchaseGLAC;
    public int SaleGLAC;
    public int DepreciationExpenseAcId;
    public int accumulatedDepreciationAcId;
    public int ExpenseMaintenanceAccountId;
    public int CapitalWipAcId;
    public int UOMScheduleIdCostRate;
    public int UOMScheduleIdPurRate;
    public int UOMScheduleIdRetailRate;
    public int UOMScheduleIdWhsRate;
    public int ItemQcGradeId;
    public String AmountCalcType;
    public String BaseCropYear;
    public String BuyerPartNo;
    public String HSCode;
    public String ItemCode;
    public String ItemCodeNew;
    public String ItemName;
    public String ItemNameOtherLingo;
    public String ManufacturePartNo;
    public String Pic1;
    public String Pic2;
    public String ProductNo;
    public String BarcodeImage;
    public String BarcodeNo;
    public String ProductType;
    public String ModelName;
    public int ItemOriginId;
    public String ItemAliasName;
    public String ItemSpecification;
    public int MaxMeaurementUnitId;
    public int itemModalId;
    public int UomLookUpId;
    public int MasterItemId;
    public int PurchaseTypeLookUpId;
    public boolean IsExpirable;
    public boolean IsDiscountable;
    public boolean IsTaxable;
    public boolean IsImport;
    public int ShelfLife;
    public double SaleTaxPurPercent;
    public boolean AtRetailPriceTax;
    public boolean AtPurcahsePriceTax;
    public boolean ItemWithVarient;
    public double SaleTaxSalesPercent;
    public double WeightSemiFinish;
    public double WeightSemiFinishSand;
    public double WeightFinishGoods;
    public int MotherItemId;
    public int RackId;
}
